### ISSUE TITLE
Stream query results to browser

### ISSUE THREAD

**Issue by rickbergfalk** [rickbergfalk/sqlpad#10]
Followup from issue #6. I don't have the time to work on this enhancement right now, nor am I familiar enough with streams, but if I had the resources this is something I'd like to do...

Investigate streaming query results to the browser over websockets. The results would still need to be limited by max rows so we don't crash the browser. All uses of the runQuery functionality would need to support the streaming results, not just the core query editor (schema sidebar and connection test).

It would be something like the following:

- query results are streamed from database to nodejs (already done). 
- rows then piped to a metadata categorizer/collector (the metadata would be sent to browser separately)
- rows stream is then duplicated/split (is this possible?)
    - one record stream goes into a record limiter thing. records under the limit are piped to browser
    - the other record stream gets piped to csv file (there's no reason the csv can't have all the records) 

SlickGrid wouldn't load the records until the results are fully streamed to the browser. In the grids place, we could have a large font timer running, as well as a large-font record counter. These things would be a good indicator of progress for the end user.

With all these changes, it would also be nice if we could cancel or stop the query at any time from the UI. This depends on the database driver to some extent. Some drivers can be explicitly cancelled (SQL Server) while others need to just be killed/closed.

Thoughts?

**Comment by deepvoice** [comment]
Could use async to do all this in separate functions so that it doesn't kill the browser waiting.
Would also allow kill functionality so you don't get script hangs (happens to me a lot because I have a very large db table tree and I have to wait for that to reload every time before I can run a query :(
https://www.npmjs.com/package/async

**Comment by rickbergfalk** [comment]
@deepvoice I have the same problem with the table tree for some of my large databases. I discovered its actually the way I'm creating the tree in the browser that's causing the problem. 

For the table tree I should really build out a separate thing that gets a list of tables, and then when needed, get the columns for the expanded table. The current solution was a lazy one, and just does it all, for every table and view in the database...

I'm also using jQuery's hide/show which I've recently read is terrible. And I'm also building out each html element as I go... also not very good.

I'll make a separate case to optimize the database tree view :)

**Comment by rickbergfalk** [comment]
I'm going to close this issue for now. The row limiting seems to work for the time being. Plus, it occurred to me that the browser will ultimately be holding the results in memory - if the dataset is too big for node it'll likely be too much for the browser as well.

I'm not opposed to streaming the results to the browser - it'd just involve a lot more rework than I'm interested in the moment.
