### ISSUE TITLE
Setting min/max values

### ISSUE THREAD

**Issue by MichaelAronsen** [rickbergfalk/sqlpad#102]
Is it possible to set min/max values for charts?

Doing simple line charts for temperature measurements, I always have a min y value of 0, even if my minimum value is around 25, makes the chart look bad.

**Comment by rickbergfalk** [comment]
Hi @MichaelAronsen 

Not currently but I can look into this.

**Comment by rickbergfalk** [comment]
I've gotten this implemented for the v2 release this fall. So far I've only implemented for the line chart - I don't know that it would make sense for bar charts. Let me know if you have any additional thoughts on this.
