### ISSUE TITLE
result for 8 hours late

### ISSUE THREAD

**Issue by john5480** [rickbergfalk/sqlpad#103]
Hi, I'm a sqlpd user from China.
I've got confused when excuting a sql which including two datatypes  about 'date' , the result shows 8 hours later than my local time and db time. 
I had excuted the sql in db itself and my local db client , it runs OK.  But in sqlpad shows 8 hours late.
how can I config it to fix the time? Thanks

`SELECT TOP 100 * FROM [CFPAMFTRADE]. [dbo].[t_AIP_QueryRespone] WHERE TranID IN ('67046','67047','67048')   ; `

here's my post
**correct** 
![normal_time](https://cloud.githubusercontent.com/assets/14275178/15772591/83fc714e-29a4-11e6-99d8-8b65ca8754ea.png)

**late**
![late_time](https://cloud.githubusercontent.com/assets/14275178/15772581/7479ee86-29a4-11e6-94f5-e10412c40581.png)

**Comment by john5480** [comment]
i see changelog for 1.14.0 

> Add ability to turn off date localization (add config item "localize" set to "false")

how to turn off that option? does it work?

**Comment by rickbergfalk** [comment]
Hi @john5480 

Just realized that'd not documented yet. Yes if you add a configuration item with the key set to "localize" and the value set to "false", you should start to see the time you are expecting. 

Let me know if this does not resolve your issue.

**Comment by john5480** [comment]
Sorry , many config files here, which file should I edit?

**Comment by john5480** [comment]
i've found the key set, it works , thks very much!

**Comment by yangbo015** [comment]
> i've found the key set, it works , thks very much!

Could you please share the key set file name?
