### ISSUE TITLE
Can only access it from localhost

### ISSUE THREAD

**Issue by leoliu1313** [rickbergfalk/sqlpad#106]
Hello,

Maybe it sounds stupid to you guys, but does anyone know how to access it from my registered domain or my static ip?
For example, http://<domain or ip>/<port>
Currently I use ports other than 20, 80, 443 to avoid this error.
Disabling Google authentication streategy, since there's no GOOGLE_CLIENT_ID or no GOOGLE_CLIENT_SECRET in ENV.

Thanks,
Leo

**Comment by rickbergfalk** [comment]
Hi @leoliu1313 

Running it under from your registered domain or ip depends on your setup and what you're using for your web server and server setup. 

What I've done in the past is use nginx to serve as a front to any web traffic, and then use subdomains to proxy the request to different ports. So for example, mydomain.com:80 would serve your main website, but maybe sqlpad.mydomain.com:80 might proxy to localhost:3000, which would be your sqlpad instance. 

Couldn't find my initial notes on what I did, but here's a stack exchange QA that kind of shows more of what is involved: http://serverfault.com/questions/601332/how-to-configure-nginx-so-it-works-with-express

I'm going to close this issue, but please feel free to continue the discussion and let me know if you have any additional questions :)

**Comment by leoliu1313** [comment]
Thank you for the fast response. I really appreciate it. The thing is I have no problem to set up a node.js instance to any port on Amazon EC2 machine. But, I cannot do the same thing for this sqlpad library. Do I really need to use nginx?

**Comment by leoliu1313** [comment]
It turns out I need the authentication.
The following works for me.
`sudo sqlpad --port 5566`

**Comment by rickbergfalk** [comment]
Glad you got it figured out! let me know if you have any other questions :)
