### ISSUE TITLE
optimize db info tree performance

### ISSUE THREAD

**Issue by rickbergfalk** [rickbergfalk/sqlpad#11]
See previous discussion in issue #10 

Lots of room for improvement for db info tree performance. For databases with few objects things are okay, but for large ones its a pretty rough experience.

Things to for sure do:

- Don't use jQuery hide/show, use CSS and addClass/removeClass instead
- use a view template instead of building each element individually (maybe even do this on server?)

And if that's still not good enough:

- Only get table columns when needed

**Comment by dcelasun** [comment]
You are talking about display performance, but can we also consider the actual query performance?

This is especially a problem with Vertica where even the simplest queries have unpredicatable execution times. For example, on our cluster, the db info query in SqlPad takes around ~40 seconds :)

Maybe we could cache the db info results in memory and only update it in certain intervals, like maybe once every hour? Of course, the exact interval can be configurable.

What do you think?

**Comment by rickbergfalk** [comment]
Oh definitely - I had no idea the queries could be taking that long to run. Most my slow-downs have been UI related. 

I think caching is a good way to go. We could even have a refresh icon or something to manually refresh the schema on demand if needed.

**Comment by dcelasun** [comment]
Hmm, refresh button is a great idea. I'll probably be able to work on it in a few days.

**Comment by deepvoice** [comment]
I think that caching (since I am using vertica with over 4000+ tables under 100+ schemas) would be a GREAT idea!! Yes, it is a pretty big issue.

I am also noticing that it is not pulling tables with dots in the name. I haven't looked at the code that is pulling the tables yet but it might be related to the below:
database.schema.table.with.dots  = Not supported
database.schema."table.with.dots" = Supported

**Comment by dcelasun** [comment]
@deepvoice I'm also working with a 100+ schema Vertica cluster, so I feel your pain!

I have never seen a table with a dot in the name. I can probably check that tomorrow and see if I can replicate (and fix) it.

**Comment by deepvoice** [comment]
I think might have to make this it's own bug. 
I put console.log in and even did a string.replace to escape the "."'s (Didn't make a difference)
It is pulling the tables but not displaying them.
Note: lodash .escapeRegExp() is in version 3.0 which has not been released to NPM yet.

**Comment by dcelasun** [comment]
I've just pushed an initial implementation for caching the schema information. I'd appreciate it if you guys could test it and let me know if anything is missing.

**Comment by rickbergfalk** [comment]
I've just published 1.4.1, which has front-end optimizations for the schema information. The html now renders server-side all at once, and its using jQuery's toggleClass instead of toggle. Between this and the caching (thanks @dcelasun!), schema info should be pretty snappy now.

**Comment by dcelasun** [comment]
Yes, now it's much faster and doesn't freeze the browser. Thanks @rickbergfalk!
