### ISSUE TITLE
cannot create connection with crate 0.55.2

### ISSUE THREAD

**Issue by benbenqiang** [rickbergfalk/sqlpad#111]
test connection returns Success, but not responding when clicking Save butto n

**Comment by tellezb** [comment]
Same results for me. Save button does nothing.

**Comment by rickbergfalk** [comment]
I'm looking into this now... I don't have crate installed but I should be able to see why it isn't saving

**Comment by rickbergfalk** [comment]
Discovered why it wasn't saving - the database input had a required attribute on it, which doesn't hold true for crate connections and prevented the form validation by the browser. 

I've published a fix to npm version 1.17.2. 

Sorry about that! Let me know if you run into any further issues with the crate connection and I'll debug further.

**Comment by tellezb** [comment]
Confirmed working against Crate 0.55.2. Thank you!

**Comment by rickbergfalk** [comment]
You're welcome! Thanks both for filing an issue :)
