### ISSUE TITLE
SQL Server Domain Support

### ISSUE THREAD

**Issue by wrathagom** [rickbergfalk/sqlpad#112]
The mssql package for node has support for domains. Simply if there is a domain present in the config then it uses it. I would like to see an optional field when creating new SQL Server connections for this field.

https://github.com/patriksimek/node-mssql#general-same-for-all-drivers

If I find some time I may try to tackle this on my own, but alas I don't know when that will be. My guess is that this will be of large benefit for many enterprise users.

**Comment by rickbergfalk** [comment]
Hi @wrathagom - Adding this shouldn't be a problem. I'm currently polishing up the sqlpad for a v2 release and can add it then (hoping for release in September). 

If you'd like to take a crack at it, you should be able to follow the same pattern used for the sqlserverEncrypt option.

**Comment by rickbergfalk** [comment]
I have this implemented in the v2 branch :) It'll be available in the beta version which should be published first week of September, with stable v2 release early October.

**Comment by wrathagom** [comment]
Thanks Rick, sorry I wasn't able to contribute.

**Comment by rickbergfalk** [comment]
No worries! I was reworking the connections ui a bit so it wasn't much trouble to take care of :)
