### ISSUE TITLE
error: cannot insert multiple commands into a prepared statement

### ISSUE THREAD

**Issue by nbrustein** [rickbergfalk/sqlpad#12]
I installed a local version of SqlPad, loaded it up in a browser, connected to a remote database, and ran a query with no problem.

I then installed a version of SqlPad on an EC2 instance, loaded it up in a browser, connected to the same remote database, tried the same query, and got the error "error: cannot insert multiple commands into a prepared statement".  I found this page (https://github.com/brianc/node-postgres/issues/33) which seems possibly related, but I couldn't tell for sure.

Is it possible that there is some dependency that is not listed in the package.json that I have locally but am missing on the server? 

The query looks like:

    /* create temporary table */
    create temporary table users_from_acme_company (
        user_id uuid
    );

    /* select data into the temporary table */
    INSERT INTO users_from_acme_company (user_id)
    select user_id from users
    join institutions_users iu on iu.user_id = users.id
    join institutions on institutions.id = iu.institution_id
    where institutions.name = 'ACME';

    select * from users_from_acme_company;

**Comment by rickbergfalk** [comment]
That's interesting - I'm not sure what it would be but I can dig into it a bit. 

May I ask what version of node.js and postgres you are using?

I don't think it would be a missing dependency. If anything it might be slightly different module versions that could cause it. I'll see if there is anything in the node-postgres usage I should be doing differently too. The queries sent to postgres should be sent as text statements, not prepared statements, so its a very confusing error message to be receiving: https://github.com/brianc/node-postgres/wiki/Prepared-Statements

**Comment by nbrustein** [comment]
Thanks for the reply Rick, and things for sharing SqlPad.

Our node version is v0.10.33
Our Postgres version is 9.3.3

Not sure it's helpful, but the AMI we're using on the EC2 instance
is amzn-ami-hvm-2014.09.2.x86_64-ebs (ami-146e2a7c)

Let me know if you figure anything out.  Thanks again.

 - Nate

**Comment by rickbergfalk** [comment]
Thanks, and you're welcome!

The talk about versions got me thinking and I've pinpointed the issue (although its unrelated to node and postgres versions). 

In version 1.2.1 of SqlPad I changed the postgres module used to run queries to https://github.com/brianc/node-pg-cursor. I think it is accidentally handling plain text queries as a prepared statements, because the same queries work in version 1.2.0.

Until there's a fix ready, you can work around this by explicitly install version 1.2.0 on your server. That will allow you to run a query with multiple statements.

**Comment by nbrustein** [comment]
Awesome.  Did you change this in the last few days?  Is that why it works
on the first install I did but not on the second one?

**Comment by rickbergfalk** [comment]
Yep - I did some work on it over the weekend. I didn't think about the timing of your issue, but it makes sense. You likely have 1.2.0 on the first install and 1.2.1 on the second one.

**Comment by nbrustein** [comment]
I downgraded to 1.2.0 and it works.  Thanks again, and good work!

**Comment by rickbergfalk** [comment]
@nbrustein Just a heads up - version 1.3.0 has been published to npm. It has a work-around built in for this issue, so feel free to upgrade.

**Comment by nbrustein** [comment]
awesome.  thanks.

**Comment by nbrustein** [comment]
it worked
