### ISSUE TITLE
Enhancement: Cache schema information

### ISSUE THREAD

**Issue by dcelasun** [rickbergfalk/sqlpad#13]
As discussed in https://github.com/rickbergfalk/sqlpad/issues/11, calculating schema information can be costly, especially for databases with a large number of schemas/tables.

We should cache the schema info and only regenerate it if the user specifically asks for it.

**Comment by dcelasun** [comment]
@rickbergfalk For some reason, `browserified.js` seems to include [my local paths](https://github.com/rickbergfalk/sqlpad/commit/1d0a9f37daaf55648ba1bf0ffcbff4770285ca16#diff-0aa34ebc5c97f08f655edd3ad239b89aR83). Any idea why that happens and how I can prevent it?

**Comment by rickbergfalk** [comment]
I'm not sure why the local paths would be included. I'm not too familiar
with browserify - its just something I was trying out with this project.

**Comment by dcelasun** [comment]
Yeah sorry, it was my fault. Using watchify results in local paths, but running bundle before pushing removes them. I forgot to do that and accidentally pushed. Anyway, it's fixed now :)

**Comment by rickbergfalk** [comment]
Just getting around to testing this out - it works great for postgres but I'm having issues with my mysql database for some reason. Can't quite figure out why but I'll keep poking around at it. 

Good to know about watchify - I set it up but ran into some issues here and there, so I never got around to using it much.

**Comment by dcelasun** [comment]
That's interesting. I've tested with mysql, postgres and vertica and it worked fine. Maybe I missed something.

**Comment by rickbergfalk** [comment]
Yeah I think it might be something with my setup - I noticed sqlpad console.logged an error message about a refused connection. I'll keep looking into it

**Comment by rickbergfalk** [comment]
Figured it out - Number.MAX_SAFE_INTEGER results in undefined which sent back 0 records. (I'm still using node.js 0.10.x). It was okay for my postgres connection because it uses a different approach to limiting the rows. 

I'm thinking I'll just set it to one million or something. Reality is node/browser will crash if a schema is that big...

**Comment by rickbergfalk** [comment]
What version should I bump SqlPad to for this change? Can't decide between minor and patch. Don't know if it matters much since this is an app and not a module...

Thoughts?

**Comment by dcelasun** [comment]
Sounds reasonable. Or, maybe something like this?

    var limit = typeof Number.MAX_SAFE_INTEGER == 'undefined' ? 1000000 : Number.MAX_SAFE_INTEGER

That way the intention of the code would a bit clearer. But, whatever you prefer is fine, it's a minor thing anyway.

I think a minor version bump is better since this adds a feature (schema caching). What do you think?

**Comment by rickbergfalk** [comment]
I like that code approach and I'm good with a minor version bump :) 

I'll publish to npm later tonight. Thanks for adding this!

**Comment by dcelasun** [comment]
Oh, by the way, the value of MAX_SAFE_INTEGER is 9007199254740991, so maybe we should use that?

var limit = typeof Number.MAX_SAFE_INTEGER == 'undefined' ? 9007199254740991 : Number.MAX_SAFE_INTEGER

That way, it'll always evaluate to the same number.

**Comment by rickbergfalk** [comment]
1.3.0 has been published!
