### ISSUE TITLE
Can't select text from query results

### ISSUE THREAD

**Issue by dcelasun** [rickbergfalk/sqlpad#14]
@rickbergfalk Hey Rick, I just realized text selection is disabled on query results. I thought maybe you left it disabled on purpose, so I pushed it to [a new branch](https://github.com/rickbergfalk/sqlpad/commit/6651aabd7d1692c671345d4755774d1353177aec). Should I merge it to master?

**Comment by rickbergfalk** [comment]
Oh for sure! I didn't mean to  leave it disabled - just an oversight on my part. Thanks for catching this!

**Comment by dcelasun** [comment]
OK great, just merged the branch!
