### ISSUE TITLE
"Sign in" and "Sign Up" displayed despite setting DISABLE_USERPASS_AUTH=true

### ISSUE THREAD

**Issue by ktopping** [rickbergfalk/sqlpad#140]
Hi.
I've noticed since upgrading to 2.1.0 (from 1.11.0) that - despite setting DISABLE_USERPASS_AUTH=true - the login/signup screen still displays links to "Sign in" and "Sign Up" (see attached image). It looks as though the signup/signin _actions_ are (correctly) disabled by the flag but the links are still displayed on the page, causing a bit of confusion (rather than a security issue).
![image](https://cloud.githubusercontent.com/assets/91001/20707918/705e59a0-b625-11e6-93ac-b75994f06e78.png)
Apologies for the fact that my first interaction with you has been to report an issue. This is an awesome product that I and my colleagues are using every day! Thanks!

**Comment by rickbergfalk** [comment]
Thanks for reporting this @ktopping! Sorry this was missed with the v2 transition.

A fix for this has been published to npm under version 2.1.1, along with some other improvements.

Glad you and your colleagues are finding sqlpad useful. If you have a moment, I'd love to get your thoughts on the v2 changes sometime (either here or email in github profile). Hopefully sqlpad's db migration worked out and you didn't lose user roles. I'd also be interested in how adjusting to the new ui is going (are the changes for the better? worse? etc.)
