### ISSUE TITLE
multi-cursor much slower in version 2

### ISSUE THREAD

**Issue by nbrustein** [rickbergfalk/sqlpad#142]
Using option+drag to select multiple lines to change (generally either indent or comment) leads to a large lag, sometimes seconds, in version 2, but was essentially immediate in version 1.

**Comment by rickbergfalk** [comment]
Hi Nate - Are you seeing this slowness in development mode or when you are running from the cli package from npm? Also which browser are you using?

React in dev mode can be pretty slow, but I haven't noticed anything running the production build. 

I'll do some digging to see what could be causing this otherwise. I'm using an Ace editor react wrapper, and I'm wondering if that needs some performance optimization...

**Comment by nbrustein** [comment]
I'm not sure.  I'm running the two versions in two different places using two different commands, but I was assuming this wouldn't matter much to the performance of client-side behavior.  Here is a description of the two environments, but maybe the best thing is for me to just try to get to a better apples-to-apples comparison and see if I still see the performance difference, eh?

I'm running version 2, which is slower, from my local machine against a local db using the following command:

    sqlpad --dir ~/sqlpaddata --ip ### --port #### --passphrase ###

The one that is faster I'm running on a remote machine.  I had forgotten I was doing this, but it's actually pointing at a checkout of my own branch of sqlpad.  This is because a long time ago I created a pull request and I wanted to get it on our live sqlpad without waiting for you to merge it in.  After you merged it, though, I reconciled everything, so now it is the same as release 1.9.0.  Since it was a branch though, I was running it with this command:

   node server.js --dir /path/to/dir --port 80 --passphrase PASSPHRASE &

**Comment by rickbergfalk** [comment]
@nbrustein does the database you connect to have a really large schema? 

I wasn't able to reproduce the slow multi-cursor behavior, but I was just able to reproduce extreme slowness in the editor in general. It seems tied to when a large schema is loaded in the schema explorer. 

I'm looking into a fix, hopefully this will address what you are seeing too.

**Comment by rickbergfalk** [comment]
Actually ignore my question @nbrustein - a large schema is not the only thing that can cause the performance issue... It also occurs once you've gotten a decently sized query result back.

**Comment by rickbergfalk** [comment]
@nbrustein just published version 2.1.3 - this should address the slowdown you're seeing.

If this doesn't fix the perf issues you're seeing let me know and we can reopen the issue :)

**Comment by nbrustein** [comment]
Thanks @rickbergfalk rick  I'll update and let you know how it goes.  (And, yes, it is a very large schema)
