### ISSUE TITLE
Instructions to Add new Datasources

### ISSUE THREAD

**Issue by bobbych** [rickbergfalk/sqlpad#143]
I am thinking about adding [snowflake](https://docs.snowflake.net/manuals/user-guide/nodejs-driver.html) as a datasource. Can i get some pointers on where to start

**Comment by rickbergfalk** [comment]
Hi @bobbych! I've never heard of snowflake before but it looks interesting and like a good fit :)

Here's a run down of what you'll be working with. Apologies in advance for the lack of clean separation on these - connections/datasources are sort of overloaded... 

On the upside, you should be able to follow the patterns already in the file and end up ok.

## Backend: 
* [models/Connection.js](https://github.com/rickbergfalk/sqlpad/blob/master/models/Connection.js) - model definition for how connections are saved to sqlpad's embedded database, nedb. If snowflake needs any special fields that aren't common to db drivers like host, username, or password, you'll want to define them here. 
* [routes/connections.js](https://github.com/rickbergfalk/sqlpad/blob/master/routes/connections.js) - handles the api calls that interact with Connection models
* [lib/run-query.js](https://github.com/rickbergfalk/sqlpad/blob/master/lib/run-query.js) - this is responsible for connecting to a database, executing a query, disconnecting, and passing on the results. 

## Frontend: 
* [client-js/ConnectionAdmin.js](https://github.com/rickbergfalk/sqlpad/blob/master/client-js/ConnectionAdmin.js) - UI for adding a connection. If snowflake has any connection fields that don't fit the typical db mold, you'll want to do some showing and hiding of additional fields

I feel like I might be forgetting something... let me know if you have any questions or run into any issues. If you have the skills or ideas on how this could all be better managed I'm open to restructuring this too :)
