### ISSUE TITLE
Disable full paths in production bundle

### ISSUE THREAD

**Issue by vweevers** [rickbergfalk/sqlpad#147]
What's the reason for enabling `fullPaths`?

```js
b = browserify({
    entries: ['./client-js/index.js'],
    fullPaths: true
})
```

Disabling it would bring the bundle size down from 1.5 to 1.3 MB.

**Comment by rickbergfalk** [comment]
Ironically that was in to be able to see the module sizes within the
bundle. It can safely be removed.
