### ISSUE TITLE
How can I add backends for Oracle, MonetDB and possible SciDB? 

### ISSUE THREAD

**Issue by lcota** [rickbergfalk/sqlpad#148]

**Comment by rickbergfalk** [comment]
Hi @lcota - you would need to add support for the necessary database drivers. #143 has a rundown of which files would need updating to support this. 

MonetDB's driver looks promising https://www.npmjs.com/package/monetdb. 

Unfortunately Oracle's node.js driver requires compilation and has a complex install/setup surrounding it. More info can be found in #21. 

I didn't look too hard, but I don't know if node.js has a sciDB driver out there...
