### ISSUE TITLE
SQL Server encryption option

### ISSUE THREAD

**Issue by vincent** [rickbergfalk/sqlpad#16]
Hi, thank you for sharing this.

To create a connection on Azure for example, one need to set the `encrypt` option to `true` [here](https://github.com/rickbergfalk/sqlpad/blob/c53026691c4d9f649c6a6e83d4ec593e2fbe285b/lib/run-query.js#L131), as defined [here](https://github.com/patriksimek/node-mssql#quick-example)

It could be nice to be able to configure it somewhere, or to document it at least.

Cheers,

**Comment by rickbergfalk** [comment]
Hi Vincent! I'll work on adding this to the connection UI. Not completely sure how I want to do it yet since it's an option that only applies to 1 database, but I think stuff like this needs to be supported.

I'll try to get to it this weekend.

**Comment by dcelasun** [comment]
@rickbergfalk I was thinking of something similar for Vertica. Maybe we could have hidden fields for server specific options in the new ui and changing the connection type can toggle them?

**Comment by rickbergfalk** [comment]
@vincent version 1.5.0 has been published to npm and has the ability to set the encrypt option for SQL Server. Could you confirm that it works for me? I don't have an Azure account to test with :)

@dcelasun I went with hidden field approach, toggling them on driver change. Feel free to add vertica specific stuff too. If you have any ideas for a more elegant solution to this kind of thing I'm open. I was almost going to create a core driver object, and extend it for each database driver... but that seemed like it was going to add more code and complication, and wouldn't be useful unless we started using some sort of client-side rendering...

**Comment by dcelasun** [comment]
@rickbergfalk Looks good to me. If we need a lot of driver-specific features in the future, then a core driver object (along with a big refactoring of query execution) could make sense. But right now, your approach is simple and it just works :)

**Comment by vincent** [comment]
hi @rickbergfalk, sorry for the late answer.

I confirm it works here, thank you :)
