### ISSUE TITLE
SQLPad crashing 

### ISSUE THREAD

**Issue by jeffgipson** [rickbergfalk/sqlpad#161]
I installed SQLPad on an Amazon server with the latest ver of node JS. I can login and run a few simple queries but it randomly stops and doesn't not automatically restart. I tried limiting all queries to the top 100 but still seeing same issue. Any help is appreciated

**Comment by rickbergfalk** [comment]
Hi @jeffgipson 

sqlpad itself doesn't handle any restarting if it crashes... that would be something handled if it were running as a service: http://rickbergfalk.github.io/sqlpad/installation-and-administration/

currently logging is just stdout/stderr. You should be able to log the messages to file by running sqlpad with 

```sh
sqlpad --debug &> log.txt
```

Hopefully this helps! Let me know if you can capture why it is crashing

**Comment by rickbergfalk** [comment]
@jeffgipson I'm going to go ahead and close this issue - feel free to continue commenting/discussing if you have any further issues.
