### ISSUE TITLE
leading zeros in text fields are removed if text appears numeric

### ISSUE THREAD

**Issue by freevryheid** [rickbergfalk/sqlpad#163]
Not sure if this is sqlpad or middleware. My sql output includes an id which is a 9 character string, eg.

'123456789',
'012345678',
'001234567',
'000123456', etc

This is tabulated as
123456789,
12345678,
1234567,
123456, etc

The problem extends to charting where, for example, line charts convert text labels to numbers when they appear numeric. 

MS Excel does the same with csv files. My current 'fix' is concat(':',id) and then tabulate or chart using the concat variable.

**Comment by rickbergfalk** [comment]
Hi @freevryheid  - thanks for reporting this. This is something sqlpad is doing. Sometimes the database drivers encode bigint values as text, so I was trying to reverse that and missed this case. 

This will be fixed in next release.
