### ISSUE TITLE
Doesnt support Azure mssql

### ISSUE THREAD

**Issue by pospile** [rickbergfalk/sqlpad#167]
Cannot connect to azure mssql with error: this version of mssql doesnt support Windows login.

**Comment by rickbergfalk** [comment]
Hi @pospile. Unfortunately the javascript-based, community-built Node.js SQL Server driver in use does not support Azure with windows login, and will likely not support this in the future. 

There is an official native SQL Server driver by Microsoft was sort of abandoned, but that's being revived? It might allow this functionality, but being native and requiring compilation limits its audience for sqlpad. 

I'll keep this in mind but I don't see it being supported any time soon.
