### ISSUE TITLE
Support for postgre SSL CA

### ISSUE THREAD

**Issue by johicks** [rickbergfalk/sqlpad#168]
I have need to connect to a PostgreSQL instance that has a root cert signed using a custom CA, so I get the following error:

{ [Error: write EPROTO 4148144448:error:14094418:SSL routines:ssl3_read_bytes:tlsv1 alert unknown ca:s3_pkt.c:1566:SSL alert number 48
4148144448:error:1409E0E5:SSL routines:ssl3_write_bytes:ssl handshake failure:s3_pkt.c:696:
] code: 'EPROTO', errno: 'EPROTO', syscall: 'write' }

Possible to add a field to specify sslrootcert?

**Comment by rickbergfalk** [comment]
Hi @johicks - You're in luck. I think this might be covered by @nikicat 's pr #153, which will be in the next release. It'll allow you to specify a path to a cert and key. 

I'm aiming to publish a beta release to test the changes this weekend. I'll let you know when its available to try out

**Comment by johicks** [comment]
@rickbergfalk I am currently using that version (latest master) and it does have support for ssl client cert and key, I need additional support for including the CA chain.

I was looking at nikicat's change and I might be able to use it as a basis to include a CA field...

**Comment by rickbergfalk** [comment]
This is now available in latest beta version published to npm
