### ISSUE TITLE
cannot connect to presto

### ISSUE THREAD

**Issue by liugaopeng** [rickbergfalk/sqlpad#173]
when i create new connection using presto database driver, there is no password field in the form???
So the connection always cannot pass the test.

anyone can give me a demo that how to configure presto connection?

**Comment by rickbergfalk** [comment]
Hi @liugaopeng - I'm not too familiar with presto myself, but the driver in use does not specify a password option. I think it connects over a rest api endpoint? 

Skimming through the presto docs, it looks like there are some advanced methods of authentication (ldap, kerberos). Unfortunately these are not supported by this driver.

**Comment by ebuildy** [comment]
Also, the driver seems calling "/v1/execute" which is not found :/

**Comment by simple365** [comment]
I got the same problem.Error message 
```
execution error:<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
<title>Error 404 Not Found</title>
</head>
<body><h2>HTTP ERROR 404</h2>
<p>Problem accessing /v1/execute. Reason:
<pre>    Not Found</pre></p>
</body>
</html>

```
