### ISSUE TITLE
no update strategy

### ISSUE THREAD

**Issue by freevryheid** [rickbergfalk/sqlpad#174]
I understand that sqlpad is still beta, but is it possible to update an existing installation without reinstalling?
I have sqlpad installed locally. npm update sqlpad broke it. I guess one option would be to backup the db folder, re-install and then overwrite the re-installed db folder with the backup.

**Comment by rickbergfalk** [comment]
Hi @freevryheid - restoring a backup db folder should work. Out of curiosity what version of sqlpad were you using?

When you ran ```npm update sqlpad``` did you specify the -g flag? Running without might yield unexpected behavior. I'm not sure what would happen to be honest.

I always use ```npm install -g sqlpad``` which installs the latest version. If you prefer, you can specify a specific version to install by running ```npm install -g sqlpad@2.1.3```. 

Hope this helps - let me know how it goes.

**Comment by freevryheid** [comment]
Thanks, yes I'm running 2.1.3. I'll explore these options and let you know how it goes before closing this issue.

**Comment by rickbergfalk** [comment]
@freevryheid I going to go ahead and close this ticket.

I realized I missed your question about baseurls on https - baseurls should work under https. That search/replace operation is looking for a specific value in the file built by the front end build system, which is set to always have http://BASEURL.
