### ISSUE TITLE
Docker config for sqlpad

### ISSUE THREAD

**Issue by talevizos** [rickbergfalk/sqlpad#175]
Hi,

We're configuring sqlpad to run containerized. I'm almost there, but want to hand in a valid rcfile. I tried various syntax to launch sqlpad but the urls aren't working out. My assumption is that sqlpad reads an rc file from /home/<username>/.sqlpadrc 
but it's not getting read, so not working.
Hopefully this question makes sense? Do you have a command line flag to force sqlpad to read an rc file? Thanks in advance!

**Comment by rickbergfalk** [comment]
Hi @talevizos - sqlpad will read the .sqlpadrc file if it exists, but only for the cli flag values. It is expected to be json. I haven't tested this, but I believe it'd be something like this: 

```js
{
  "ip": "",
  "port": 80,
  "https-port": 443,
  "dir": "",
  "base-url": "",
  // ... and so on
}
```

This .toml file describes all the config points available: https://github.com/rickbergfalk/sqlpad/blob/master/resources/config-items.toml. The keys in the rc file would need to be the same as the cliFlag for each config item. Env vars might be an easier config entry.

Lastly, not sure if it is of help but there is a sqlpad repo out on docker hub: https://hub.docker.com/r/sqlpad/sqlpad/.

**Comment by rickbergfalk** [comment]
Closing this issue - let me know if there are any additional questions
