### ISSUE TITLE
Can you support history of execute sql?

### ISSUE THREAD

**Issue by chenlingmin** [rickbergfalk/sqlpad#178]

**Comment by rickbergfalk** [comment]
Hi @chenlingmin  - sqlpad uses a database that holds everything in memory, so it some limits would need to be put in place... If history was limited to say maybe the last 1000 queries would that be of interest to you?

Are you thinking history more for reference by end user or more of audit-log purposes?

**Comment by chenlingmin** [comment]
@rickbergfalk Yeah! And I want use LDAP auth user, can you consider it？

**Comment by rickbergfalk** [comment]
In progress by @koszti in #512

**Comment by rickbergfalk** [comment]
history is now available in v4 release
