### ISSUE TITLE
Make update check optional / document calls to npmjs.com

### ISSUE THREAD

**Issue by kessler** [rickbergfalk/sqlpad#179]
I've noticed that sqlpad makes repeated calls to npm while it's running:
![image](https://cloud.githubusercontent.com/assets/147367/25700260/92ea378a-30cf-11e7-98aa-3f7642360384.png)

I verified that the node process is indeed the sqlpad process.

Initially I thought it's for some lazy package installation but it happens every time the server is running and several times as well.

Can you please shed some light on this?

**Comment by vweevers** [comment]
@kessler I suspect this the update-check that sqlpad does periodically.

**Comment by rickbergfalk** [comment]
Yeah it's for the update check. Would it be preferred to be able to disable this?

**Comment by kessler** [comment]
Making it an opt out configuration sounds like a good idea.
It might be helpful to give some indication of that in the readme.

Also, just want to use this opportunity to say that this is a wonderful project!

**Comment by rickbergfalk** [comment]
Thanks @kessler! An opt out will be easy enough to add. I've been meaning to update documentation so I can expand on some of the security/behavior aspects of sqlpad there too

**Comment by rickbergfalk** [comment]
This was added in #186, but has not made it to a release yet. Will leave this issue open until documentation is added.

**Comment by kessler** [comment]
thanks for the update!

**Comment by rickbergfalk** [comment]
This feature is in release 2.3.0, and I've put a blurb on the installation/administration page about it in the configuration section.
