### ISSUE TITLE
Are query tags useful?

### ISSUE THREAD

**Issue by rickbergfalk** [rickbergfalk/sqlpad#18]
I'm thinking about getting rid of query tags. Anyone want to talk me out of it? :)

I thought they'd be useful, but now I'm not so sure. I haven't tagged most the queries/charts I've written, and there isn't really a way to mass-manage tags at all. If query tags are in fact useful, I think the UI should be built out a bit to make using them more pleasant - auto-complete, mass tag assignment, tag renaming, tag merging, etc. (something like gmail labels, except without the nested part) 

Any thoughts? 

cc @dcelasun

**Comment by dcelasun** [comment]
I think improving them would be much better than removing :) Gmail labels is a great example that works, something like that would be awesome.

**Comment by rickbergfalk** [comment]
Maybe start with something like this with typeahead support? http://timschlechter.github.io/bootstrap-tagsinput/examples/

**Comment by dcelasun** [comment]
Typeahead would be great! We could use [Bloodhound](https://github.com/twitter/typeahead.js/blob/master/doc/bloodhound.md#remote) to query the db on the server.

**Comment by deepvoice** [comment]
I thought that I had commented on this. Please keep the tags! I have a lot of users that are ummm.. sql deficient. The tags tell them right where to go to run what they need. It was one of the things that, when I first looked at this project, I said :+1:

**Comment by rickbergfalk** [comment]
Alright then tags are here to stay! In a few weeks I'll plan on taking another pass through the front end code, and add in the boostrap tag input library and work in the typeahead support. Or if there are any other tag-input ui libraries out there to consider, I'd be open to looking into those as well.

**Comment by rickbergfalk** [comment]
Just published 1.7.0 with some tag improvements :)

Threw in bootstrap-tagsinput and typeahead. Right now it's a lazy implementation - the bloodhound prefetch for typeahead will get all tags and not cache anything. If this is slow for anyone let me know, but it shouldn't be noticeable at all.
