### ISSUE TITLE
IE 11 issues at login

### ISSUE THREAD

**Issue by sldorman** [rickbergfalk/sqlpad#181]
I have a problem similar to issue #171 but it's not a case where I forgot the password.  I am setting up SQLPad for the first time.  I brought it up and hit Sign Up.  I entered my email address and password/confirm password.  It then brought me to the Sign In page where I entered my information and hit Sign In - nothing happens.  I followed the recommendation in #171 by renaming the users.db and went through the process again.  I get the same issue - the Sign In button does not do anything.

I had a few issues with the install and execution.  There seem to be 2 sets of instructions - the Installation and Administration page and the v2 Development Guide.  Some of the commands did not work.  I had to do a 'npm install' and 'npm build' then 'npm start'.  Perhaps I missed something?

**Comment by rickbergfalk** [comment]
Hi @sldorman - Sorry for the delay in getting to this. 

The installation and administration page is the preferred method of install. The development guide is more for setting sqlpad up for development and making changes. 

May I ask what version of Node.js and SQLPad you are running? You should be able to find out by running `node --version` and `sqlpad --version` at a command prompt.

**Comment by sldorman** [comment]
Hi @rickbergfalk - I had problems when I did the install via the installation and adminstration page which is why I opted for the development guide.  I will try from scratch again.  Thank you.

Node version = 6.10.3
SQLPad version = 2.2.0-beta1

**Comment by sldorman** [comment]
I tried to remove anything I originally installed to start over.  I manually removed files I downloaded and did 'npm uninstall sqlpad -g' to remove files added from the install (I don't know if -g was correct or not but it didn't work without it). I removed the $HOME/sqlpad directory.  I then ran 'npm install sqlpad -g'.  I did a Sign Up then a Sign In.  When I hit the Sign In button, nothing happened.  I looked in the users.db file and it looks like only the first 3 letters of my email address were saved:

..."email":"suz","role":"admin",.....

I tried to edit the users.db by putting my full email address in there but when I sign in I get "Username or Password incorrect".

**Comment by sldorman** [comment]
A little more info - I uninstalled/installed everything again. When I did Sign Up, I typed in the entire email address instead of typing a few characters and selecting it from the browser's field fill-in history.  The entire email address persisted to the users.db. But when I signed in, I got the same error - the username and password are incorrect.  Any subsequent hits to the Sign In button result in nothing, not even the error message.

**Comment by rickbergfalk** [comment]
Thanks for the info! May I ask what browser/version are you using? Are there any browser plugins enabled by chance?

**Comment by sldorman** [comment]
Hi Rick, I thought I had tried different browsers earlier but I guess I was just dreaming.  The issue is only occurring with IE.  I was able to log into Chrome and FireFox.  I have IE 11.0.9600.... with all plugins disabled. When I hit the Sign In button, it looks like the page quickly refreshes but stays on the sign in page.  No error appears. 

At least I can log in now, thanks for the great response time!

**Comment by rickbergfalk** [comment]
Turns out SQLPad is broken in IE 11 due to IE's behavior in caching fetch/ajax requests? Have a fix ready for this. 

Officially I don't want to support IE nor would I recommend it for use with SQLPad given the heavy JavaScript requirements, however it should work again next release once the fix lands :)
