### ISSUE TITLE
Stored dates and calculated dates have different times.

### ISSUE THREAD

**Issue by sldorman** [rickbergfalk/sqlpad#182]
Node version = 6.10.3
SQLPad version = 2.2.0-beta1
SQL Server 2012
Everything running on same computer

This is probably related to issue #176 but I'm not sure so opening a new issue. If they are the same, then maybe this will provide more information.

I am querying a table from a SQL Server db.  The datetime columns are showing the times as being 4 hours earlier than what is stored.  If I add a column to show the difference between 2 dates (column OnlineTime in the example), the result in SQL Server Management Studio is a date/time starting at January 1, 1900 00:00:00.  In SQLPad, the date/time is 5 hours earlier than in SSMS.

Here is my query:

SELECT UsersLogTimesId
      ,UsersId
      ,LoginTime
      ,LogoutTime
	  ,(LogoutTime-LoginTime) AS OnlineTime
  FROM tb_UsersLogTimes WHERE LogoutTime is not null
  ORDER BY OnlineTime DESC

SQL Server Management Studio results:

![sqlpaddatediffinsqlserver](https://cloud.githubusercontent.com/assets/7422621/26169459/b4f82990-3b0b-11e7-9663-e1538b5bf155.png)

SQLPad results:

![sqlpaddatediffinsqlpad](https://cloud.githubusercontent.com/assets/7422621/26174713/4478403e-3b1e-11e7-8807-89eb2cc156c3.png)

The first row shows a date difference (OnlineTime) of 2 hours 10 minutes from 1/1/1900 00:00:00 in SQL Server Management Studio.  In SQLPad, the calculated date is 5 hours earlier than SSMS but only 4 hours earlier for stored dates.

**Comment by rickbergfalk** [comment]
Fix in #212 - will be available in next release (planning for later this weekend)

**Comment by Chumbaloo** [comment]
Hi, 

I am seeing the same issue on version 2.3.2, where the data is stored in 'UTC' but local offset is applied on the sqlpad result, but nothing of the sort is applied when the exact same query is executed directly on the db.

Querying the db directly:
![good_dates](https://user-images.githubusercontent.com/13964651/33912834-7f9f2930-dfeb-11e7-8e1a-3b1ed6849f39.png)

Querying via SQLPad:
![bad_dates](https://user-images.githubusercontent.com/13964651/33912849-8aa99676-dfeb-11e7-8ac0-c16364d7d6fe.png)


Is there a setting on SQLPad that can just stop all conversions of dates?

**Comment by rickbergfalk** [comment]
@Chumbaloo See if updating to latest SQLPad and setting the TZ environment variable to UTC addresses your issue: `TZ=UTC sqlpad --port 3000 ...`

**Comment by Chumbaloo** [comment]
@rickbergfalk  Works perfectly in the latest version (2.4.2).

**Comment by rickbergfalk-uptycs** [comment]
@Chumbaloo awesome great to hear
