### ISSUE TITLE
Front end cleanup

### ISSUE THREAD

**Issue by rickbergfalk** [rickbergfalk/sqlpad#19]
@dcelasun I'm going to be cleaning up the front-end query/chart editor code a bit. Just wanted to give you a heads up in case you are doing anything with it, so you don't end up with a bunch of conflicted code.

**Comment by dcelasun** [comment]
I don't have anything that could conflict, so go ahead. Thanks for the heads up!

**Comment by rickbergfalk** [comment]
Great - How do you feel about the location of the Run Query button? I'm thinking about moving it up near the save button and query name textbox. It was up there initially, but I moved it into the SQL tab, since it is the tab with the SQL. However, I miss having the ability to refresh the query results from the Vis tab.

**Comment by rickbergfalk** [comment]
I decided to keep the run query button where it currently is. I forgot how weird it felt in the query menu/nav bar. I've merged my branch into master, but I'm going to hold off publishing for now.

**Comment by dcelasun** [comment]
Just tested it, looks great! The code is much cleaner, and your reload button is certainly much better than mine :)

**Comment by rickbergfalk** [comment]
Thanks! There's definitely a lot more cleanup I want to do, but I think this is a step in the right direction :)

I'll publish to npm shortly.
