### ISSUE TITLE
pSQL Booleans fail to render in the results table

### ISSUE THREAD

**Issue by rsbrinkman** [rickbergfalk/sqlpad#191]
Hi - Running sqlpad on top of psql and querying for a boolean column renders nothing in the results table, yet in the actual csv results return the correct value.

<img width="158" alt="screen shot 2017-05-31 at 1 03 23 pm" src="https://cloud.githubusercontent.com/assets/5083820/26646596/d6689b9a-4601-11e7-97e3-6408e768eda2.png">
<img width="69" alt="screen shot 2017-05-31 at 1 03 42 pm" src="https://cloud.githubusercontent.com/assets/5083820/26646598/d844da1e-4601-11e7-8a1d-2b648a51b23c.png">

I've got a quick PR that should fix it, if you'd like me to open it.

**Comment by rickbergfalk** [comment]
Sure! Definitely welcome the PR. 

Out of curiosity what version of SQLPad are you running? And by psql do you mean postgres or are you querying psql somehow? When I test on latest against postgres I see booleans rendered... but I do remember this being an issue in the past.

**Comment by rsbrinkman** [comment]
Hi - We're running 2.0.0 and yep I meant postgres. Was the issue fixed in a more recent version?

**Comment by rickbergfalk** [comment]
Yep! The changelog has it fixed at 2.1. https://github.com/rickbergfalk/sqlpad/blob/master/CHANGELOG.md

Give 2.1.3 or 2.2.0 a shot and let me know. Should definitely see some UI performance improvements too if you have large schemas/large result sets.
