### ISSUE TITLE
how to change the view page

### ISSUE THREAD

**Issue by SongGary** [rickbergfalk/sqlpad#197]
I want to modify the page on the browser, adjust some items, but I can not to do it ,I can not find any useful page in the view layer. how I to do it?

**Comment by rickbergfalk** [comment]
Hi @SongGary. Which page are you trying to modify? 

All the view layer stuff is in the client-js folder, written in React: https://github.com/rickbergfalk/sqlpad/tree/master/client-js

Unfortunately it's not very organized and some of the React code is pretty rough (it was my first React project). 

Let me know if there's anything particular you are looking to change. 

If you're unfamiliar with the setup, clone the repo, and run `npm install` in the root of the project. From there open 2 terminal sessions. In one run `npm run start-client-dev` and in the other `npm run start-server-dev`. Once everything starts up you'll be able to change files and have the page refresh automatically.

**Comment by rickbergfalk** [comment]
Feel free to ask more questions about this too even though this issue is closed.
