### ISSUE TITLE
mysql Database select invalid

### ISSUE THREAD

**Issue by 279838089** [rickbergfalk/sqlpad#198]
mysql Database select invalid.
if i have too many Database,it can't work!

**Comment by rickbergfalk** [comment]
Hi @279838089 not sure I understand the issue. Do you mean the database selector and connection management is difficult to use if you have a lot of databases to set up?

**Comment by 279838089** [comment]
![](http://ww4.sinaimg.cn/large/006tNc79gy1fh6gh1boz0j30hm0ap74s.jpg)
In this，I have selected cms database,but it have show all my database.I want to only show cms.
My other mysql have many database , it can't show database .it is loading all the time!

**Comment by rickbergfalk** [comment]
@279838089 PR #218 changes the way mysql connections are handled. In the next release, when you specify a database in the connection, that should be the only database you see. If you don't provide a database, all the databases/schemas your db user has access to will display on the sidebar. When this happens the `mysql` and `performance_schema` schemas/databases will be hidden from view to cut down on number of schemas in the browser.
