### ISSUE TITLE
enhancement： query  copy

### ISSUE THREAD

**Issue by lishoujun** [rickbergfalk/sqlpad#202]
other already creater a good query , I want to add some line but not want to modify that public one.
so I think add a query  copy is a good idea

**Comment by rickbergfalk** [comment]
Hi @lishoujun - I agree this would be a great addition. Not sure when I'll be able to get around to adding this but I'll keep this request open :)

**Comment by lishoujun** [comment]
OK!  

Thank you again for such an amazing tool that I can share SQL with my fellows and don't have to edit the SQL again and again.

**Comment by rickbergfalk** [comment]
I've added a Clone button/link to the query editor as of version 2.4.0, that makes a copy of the query in the editor so that changes made and saved do not overwrite the original :)
