### ISSUE TITLE
Support for Apache Drill

### ISSUE THREAD

**Issue by cgivre** [rickbergfalk/sqlpad#206]
Hello all, 
I'm really impressed with SQLPad.  I started messing with getting Drill to support Apache Drill, and I've made some progress.  You can check out my branch here: (https://github.com/cgivre/sqlpad/tree/drill-support).

I had to write a NodeJS driver for Drill which I will at some point post to NPM.  
Anyway, at this point, I got SQLPad to connect to Drill via the RESTful interface.  It successfully can test a connection, and execute a query, but the results do not display yet.   Also, I have to figure out how to display schemata, but one thing at a time.  If everyone is ok with it, I'll submit a PR once it is working reasonably well.

**Comment by rickbergfalk** [comment]
Thanks @cgivre! Definitely send in a PR when you have things working. Drill support would be great. Let me know if you have any questions.

**Comment by cgivre** [comment]
Hi @rickbergfalk , 
I worked on it today and I got SQLPad to successfully execute Drill queries and display the results!  You can check out my branch if you want.  I am a little stuck on how the schema tree works.  
If I can get that to work, then I think we're good. 
My plan is/was to execute a SHOW DATABASES query in Drill, then for every database, if it is a file-system based storage plugin, execute a 'SHOW FILES IN <workspace>' query for each work space.  
For databases, I was just going to use a SHOW SCHEMA` query.   
However... the SQLPad architecture is a little confusing for me. 
Thanks for your help!

**Comment by rickbergfalk** [comment]
Good to hear! 

The way existing drivers work is a schema query is executed and the query results are converted into the nested object used to build the tree on the front end. 

The schema sql (defined in the resources folder) is executed at https://github.com/rickbergfalk/sqlpad/blob/master/routes/schema-info.js#L91. The queryResult.rows are an array of row objects... ultimately looking something like 

```js
[ 
  { table_type: 'Tables', table_schema: 'public', table_name: 'foo_table', column_name: 'column_bar', data_type: 'INT', is_nullable: 'YES' },
  { table_type: 'Tables', table_schema: 'public', table_name: 'foo_table', column_name: 'column_baz', data_type: 'INT', is_nullable: 'YES' },
  // and so on
]
```

If you can supply a SQL query to Drill to get the data in the above format you can feed it through the rest of the process and let the formatResults convert it to the tree structure. Otherwise you'll want to get the data looking something like the res.locals.tree... 

I can see how this section might be difficult if a SQL query isn't an option... The bulk of the schema-info route is implemented as a bunch of express middleware functions to avoid deep nesting of callbacks. 

If you'd like to use a different method of control flow and switch to promises or something I'd be okay with that.

**Comment by cgivre** [comment]
Hi Rick,
I’m working on a Drill driver that I’m planning on submitting to NPM.  Would it work do have a function in the driver like getSchemata() or something such that it would return results in that format?   
—c

**Comment by rickbergfalk** [comment]
A drill driver on npm would be great! I'd recommend having the drill driver do whatever makes sense for the general use case. Definitely write the getSchemata() function, but I'd maybe have the return format be whatever makes the most sense for drill. SQLPad can always map it into a different format it needs.

I imagine others might start using it especially since a drill driver doesn't exist yet :)

**Comment by cgivre** [comment]
Here’s the module.  I’m trying to figure out how to get it on NPM… ;-)  This largely duplicates the functionality of the python module pydrill.  I’m going to write the getSchmata() function because Drill has a few wrenches in the works that need to be dealt with. 

https://github.com/cgivre/drill-nodejs

—C

**Comment by rickbergfalk** [comment]
Publishing to npm is pretty slick. Once you create/log in to your npm account using npm the cli, it is just a matter of running `npm publish` in the root of your project. 

Noticed a self-reference `drill` in the package.json dependencies - is that causing problems?

**Comment by rickbergfalk** [comment]
@cgivre I'm going to be changing up the way schema queries are handled to address issue #198. The change will also benefit your integration though and make it easier for you to work your drill lib in. Just wanted to give you a heads up so you pull in the changes prior to modifying the schema-info.js route

**Comment by rickbergfalk** [comment]
Broke the logic for getting the schema for a connection out into its own file. It no longer uses express.js routing middleware for flow control and instead uses simple callback style: https://github.com/rickbergfalk/sqlpad/blob/master/lib/get-schema-for-connection.js

I'm open to this being changed around. It should be a lot easier to change up logic based on the connection passed in.

**Comment by cgivre** [comment]
Thanks,
Fixed!
I mocked up the getSchemata() function in python.  The issue is that Drill doesn’t really have a useful information schemata when it is querying file-based systems.  It does for databases, or other systems.  So I’ve had to do some hackery to duplicate the functionality.  I’m going to figure out how to port that to NodeJS and then I’ll submit a PR for sqlpad.
— C

**Comment by m1sta** [comment]
@cgivre Any update on this?

**Comment by cgivre** [comment]
HI @rickbergfalk 
I was wondering if you could help me out here.  I'm not really a NodeJS programmer so its slow going, but anyway I got SqlPad to successfully connect to and query Drill.   However, I'm getting the error below when I try to test the connection.  

```
TypeError: Cannot read property 'then' of undefined
[0]     at /Users/cgivre/github/sqlpad/server/routes/test-connection.js:12:5
[0]     at Layer.handle [as handle_request] (/Users/cgivre/github/sqlpad/node_modules/express/lib/router/layer.js:95:5)
[0]     at next (/Users/cgivre/github/sqlpad/node_modules/express/lib/router/route.js:137:13)
[0]     at mustBeAdmin (/Users/cgivre/github/sqlpad/server/middleware/must-be-admin.js:7:14)
[0]     at Layer.handle [as handle_request] (/Users/cgivre/github/sqlpad/node_modules/express/lib/router/layer.js:95:5)
[0]     at next (/Users/cgivre/github/sqlpad/node_modules/express/lib/router/route.js:137:13)
[0]     at mustBeAuthenticated (/Users/cgivre/github/sqlpad/server/middleware/must-be-authenticated.js:9:12)
[0]     at Layer.handle [as handle_request] (/Users/cgivre/github/sqlpad/node_modules/express/lib/router/layer.js:95:5)
[0]     at next (/Users/cgivre/github/sqlpad/node_modules/express/lib/router/route.js:137:13)
[0]     at Route.dispatch (/Users/cgivre/github/sqlpad/node_modules/express/lib/router/route.js:112:3)
[0] POST /sqlpad/api/test-connection 500 19.312 ms - 1300
[0] { 'EXPR$0': 'success' }
```

My code can be found here:
https://github.com/cgivre/sqlpad/tree/drill/server/drivers/drill
Any suggestions would be greatly appreciated.
Thanks!

**Comment by cgivre** [comment]
All, 
I just posted a PR which has working code for Apache Drill.
