### ISSUE TITLE
Date shown in preview and date shown within CSV/XLSX differs

### ISSUE THREAD

**Issue by MSchneider123** [rickbergfalk/sqlpad#207]
sqlpad 2.2.0
PostgreSQL 9.6.4
running on CentOS

Running a simple SQL like
select event_date from bmwza.pdi_data where sample_id = '000104393771';
from SQLPad Query shows following in GUI: 08/04/2017 00:00:00

Exporting this result either within CSV or XLSX gives: 08/03/2017 22:00:00
It probably comes from my timezone setting which is "Europe/Berlin" which means 2 hours ahead from UTC.

I've already tested by adding 
  export TZ="UTC"
in from of starting the sqlpad process.
As a result both times will be shown with 2 hours added but the difference between GUI result and CSV/XLSX result remains the same.

Is there a way to show same results within GUI and CSV/XLSX export?

Thanks
Martin

**Comment by rickbergfalk** [comment]
Sorry Martin I wasn't aware this was still happening. The intent is that UTC times in the database are presented in the UI and in files as UTC. I'll have to track down where the conversion occurs.

**Comment by rickbergfalk** [comment]
Fix in #212 - will be available in next release (planning for later this weekend)
