### ISSUE TITLE
Filter Parameters For Queries like dates

### ISSUE THREAD

**Issue by dewelloper** [rickbergfalk/sqlpad#208]
Hello all,
I need to send parameters as argument of any query like stored procedure
How can i add this kind of arguments,
If there is no any oppurtunuty like this i want to implement some moduls like that.
If anyone gives me support for this i will very pleased.
Iam sending pull request. 10x

**Comment by rickbergfalk** [comment]
Hi @dewelloper sorry I missed this - there currently isn't any support for query parameters at all. A PR to add that functionality would be welcome

**Comment by rickbergfalk** [comment]
Cleaning up old issues. Unfortunately I have less time for SQLPad so I'm leaning towards considering it "finished" and will not be adding much new functionality.
