### ISSUE TITLE
Support Oracle

### ISSUE THREAD

**Issue by mallim** [rickbergfalk/sqlpad#21]
Oracle has a Javascript Driver [oracledb](https://github.com/oracle/node-oracledb). Perhaps good to include it in this great application?

**Comment by rickbergfalk** [comment]
Hi @mallim - Thanks for the kind words! 

I'd love to expand the database support. I wasn't aware Oracle had a pure-javascript driver. Would you be willing to help test it out? 

I probably won't get around to adding this for another week or two...

**Comment by rickbergfalk** [comment]
@mallim - I took a quick look at the driver and it looks like it requires some native compilation of c++ code unfortunately. I'm not sure if we'll be able to integrate it into SqlPad quite yet... C++ modules require a lot of extra setup and can be difficult to install in some environments. :( I was hoping to keep SqlPad purely JS based so it is easy to install. 

There are some issues on the node-oracledb project concerned with addressing this (see https://github.com/oracle/node-oracledb/issues/18 for example)

I'll keep doing some research though and see if there's a way to add Oracle support. Maybe there's a way for oracle users to install the driver module separately? That way non-oracle users would not have to support the oracle compilation...

I'll keep this issue updated with what I find out :)

**Comment by cjbj** [comment]
@rickbergfalk if a SqlPad user creates an Oracle connection you could simply return an error if oracledb can't be loaded.  Users would have to pre-install oracledb themselves, just like they need to install other optional modules for SqlPad like nodemon. 

Let me know if you want a hand with Oracle.

**Comment by rickbergfalk** [comment]
@cjbj unfortunately I wasn't quite understanding how globally installed modules work. I was thinking you could require() them within another node.js script but that doesn't seem to be the case. Or at least it isn't by default. 

Or am I missing something? 

googling led me here http://stackoverflow.com/questions/15636367/nodejs-require-a-global-module-package and https://nodejs.org/api/modules.html#modules_loading_from_the_global_folders

**Comment by rickbergfalk** [comment]
And I caught up on https://github.com/oracle/node-oracledb/issues/18 too - that'd be awesome of pre-built binaries were made available via pre-gyp

**Comment by cjbj** [comment]
@rickbergfalk you don't need to install oracledb globally.  We used to document using a global install before oracledb was out on npmjs.org. The current instructions do a local install: https://github.com/oracle/node-oracledb/blob/master/INSTALL.md

So, a SqlPad Oracle user would be able to do 'npm install sqlpad oracledb ...'.  

SqlPad would want to do a  require('oracledb') only if a user configured an Oracle connection.  A try/catch around the require() will handle failure gracefully.

**Comment by rickbergfalk** [comment]
@cjbj SqlPad is only ever installed on a users machine globally, so I'm not sure how a user would go about adding modules to it. Wouldn't a SqlPad Oracle user need to install oracledb in whatever directory holds the global SqlPad installation in order for SqlPad to be able to require('oracledb')?

**Comment by rickbergfalk** [comment]
@cjbj Or I just realized - I suppose someone could install sqlpad locally, and call node node_modules/sqlpad/server.js directly. Then the oracledb installed in node_modules would be available right?

**Comment by cjbj** [comment]
The user could install like:
```
cd   /usr/local/lib/node_modules/sqlpad
npm install oracledb
```
This will install oracledb in `sqlpad/node_modules_oracledb`

Or, if node-oracledb was installed with `npm install -g oracledb` then it would be at the same hierarchy level as sqlpad and you can traverse here or ask them to set NODE_PATH.  There are probably other solutions too.  

Yes, not as clean as an integrated solution that installs with `npm install -g sqlpad` but it is only a small extra step and would extend the reach of SqlPad considerably.

**Comment by rickbergfalk** [comment]
@cjbj ah that makes sense. if I add support for the driver would you be willing to test it out and troubleshoot if necessary for me? :)

**Comment by cjbj** [comment]
@rickbergfalk sure, I can take a look.

**Comment by aaronrobertson** [comment]
Has there been any progress on this recently? I'd be willing to help out.

**Comment by rickbergfalk** [comment]
Hi @aaronrobertson There hasn't been. For a while I was watching the progress on the oracle driver offering pre-built binaries but haven't followed up on it lately.

If you have access to some Oracle databases and would be willing to assist we'd love the help :)

**Comment by aaronrobertson** [comment]
Definitely, I'll start taking a look on my own, but if you have anything specific that needs attention let me know.

**Comment by rickbergfalk** [comment]
Thanks!

**Comment by rickbergfalk** [comment]
I was almost going to close this as a wontfix but decided to leave it open as a help wanted instead. I have no intention on supporting oracle, but if someone would like to own the oracle driver implementation, documentation, and support I'd be open to a pull request.

**Comment by rickbergfalk** [comment]
Closing this for now but not 100% opposed to someone sending in a PR for this if they put the effort in. Trying to clean up and take inventory of issues. I have less time for SQLPad these days and I don't see getting this up and running and providing the support for it (sorry :( )
