### ISSUE TITLE
VoltDB support

### ISSUE THREAD

**Issue by dcelasun** [rickbergfalk/sqlpad#22]
If there are no objections, I'd like to introduce [VoltDB](http://voltdb.com/) support in the next few weeks/months.

VoltDB is a bit different compared to other SQL databases, but the [node client](https://github.com/VoltDB/voltdb-client-nodejs) would allow us to at least introduce basic query support in sqlpad.

**Comment by rickbergfalk** [comment]
Sure! I think it'd be great to support all sorts of sql databases, as long as the drivers are javascript-based and don't need any extra compilation when installing. Eventually I'd like a way to support those too though... maybe there's a way to opt-in to those driver installations or something?

**Comment by dcelasun** [comment]
Yeah, maybe we could have a small bash script that can provide different installation options. Something like:

    ./sqlpad-install (For common js-only drivers, simply runs "npm install")
    ./sqlpad install --with-oracle (Includes all common options, but compiles oracle as well)

**Comment by rickbergfalk** [comment]
@dcelasun is it alright if I close this? 

I was looking at the [voltdb driver documentation](https://github.com/VoltDB/voltdb-client-nodejs) and it looks like voltdb only supports stored procedures?

**Comment by dcelasun** [comment]
@rickbergfalk Yeah, we can close this. VoltDB supports regular queries as well, but I have far too little time nowadays to look into this :(

**Comment by rickbergfalk** [comment]
Oh I see - there's an adhoc sproc you pass the query to. https://docs.voltdb.com/UsingVoltDB/sysprocadhoc.php

I'll leave it open. It would be nice to support.

**Comment by rickbergfalk** [comment]
Going to close this since I'm realistically not going to be working on it 😅
