### ISSUE TITLE
Support trusted connections for sql server, including Kerberos and delegation

### ISSUE THREAD

**Issue by MarkGStacey** [rickbergfalk/sqlpad#220]
Referencing a previous issue, I see that MS SQL has released a version that allows for trusted connections.

This would be an absolute requirement for my use case, and if support was built in, I'd be happy to do a how to on setting up the environment for delegation (the double hop problem)

https://www.npmjs.com/package/mssql#microsoft--contributors-node-v8-driver-for-nodejs-for-sql-server

**Comment by MarkGStacey** [comment]
Original issue
https://github.com/rickbergfalk/sqlpad/issues/56

**Comment by rickbergfalk** [comment]
It looks like the new mssql lib still uses a native/compiled dependency under the hood for that, and is windows only. 

That said, I might be able to add it in as an optional dependency.

I'll try adding it in next release and see what it is like for non-windows environments...

**Comment by rickbergfalk** [comment]
Going to close this issue. Unfortunately native dependencies complicate the build of lead to a lot of confusion for people not familiar with node module dependency installation. (the optional odbc driver included triggers messages that mislead people into thinking the install of dependencies is in a bad state).

I'm also winding this project down somewhat and not looking to add more complexity to the project (#471)
