### ISSUE TITLE
Altering the base url.

### ISSUE THREAD

**Issue by martinchapman** [rickbergfalk/sqlpad#229]
Is supplying a new base url alone sufficient to run the app at a different path?

Using the self-contained node application with a specified base url (i.e. `sqlpad --base-url=/sqlpad`), the app fails to load properly, seemingly because the paths to public resources (stylesheets, js etc.) aren't updated along with the base url.

**Comment by rickbergfalk** [comment]
It should be... I'll look into this. Thanks for reporting the bug!

**Comment by rickbergfalk** [comment]
Published a fix for this to npm in version 2.3.2. Thanks again for reporting the issue!
