### ISSUE TITLE
No password for DB

### ISSUE THREAD

**Issue by Trudko** [rickbergfalk/sqlpad#23]
Hi, password for DB is mandatory when creating connection, but our test DB doesn't have password. Would it be possible to make password optional here?

**Comment by rickbergfalk** [comment]
Sure - I can look into that @Trudko. 

Whether it works might depend on the database driver in use. What database you are using?

**Comment by Trudko** [comment]
Postgres. Btw typing empty space actually worked as workaround.

**Comment by rickbergfalk** [comment]
oh great - I'll plan on making the field optional next release and go from there.

**Comment by rickbergfalk** [comment]
@Trudko sqlpad has been updated to 1.7.0 in npm. It should allow you to save a connection without a password now :)
