### ISSUE TITLE
Configuration option for client side connection handling

### ISSUE THREAD

**Issue by KingOfTheBlues** [rickbergfalk/sqlpad#234]
Would it be possible to have a configuration option to allow the queries to be run client side?

We have a use case where only a small set of users are granted VPN access, so creating a static connection for the sqlpad server is not a viable option.

**Comment by rickbergfalk** [comment]
Unfortunately not - The javascript drivers to make the database connections only work in node.js, not the browser. With SQLPad you'd need to have it installed and running behind the VPN as well.

There are some alternative SQL editors/data explorers that have some different architectures that might work out better for your use case depending on if your database is supported, listed in no particular order:

- [PopSQL](https://popsql.io/) is a traditional desktop application where the connection is made from the client-side, but has some sharing/collaboration features. 
- [SQL Tabs](http://www.sqltabs.com/) is also a traditional desktop application, but has a server component that enables sharing (https://github.com/sasha-alias/sqlshare)
- [Franchise](https://franchise.cloud/) is a web-app, but uses a fancy web technology and a tunnel you install locally to connect to your database, so the connection is made from wherever the tunnel is running.

**Comment by KingOfTheBlues** [comment]
Okay, thank you for your response - very much appreciated
