### ISSUE TITLE
how can I  run it with a  established port

### ISSUE THREAD

**Issue by sgjr** [rickbergfalk/sqlpad#240]
Now，when  I restart the sqlpad,its port will change ,how can I  run it with a  established port.

**Comment by rickbergfalk** [comment]
Hi sgjr. 

You should be able to supply the port using the cli flag --port or environment var SQLPAD_PORT. If you specify that port, and SQLPad picks a different one it is because the port you picked is already in use.

Let me know if this doesn't work for you.

**Comment by sgjr** [comment]
thanks
