### ISSUE TITLE
about sql reformat

### ISSUE THREAD

**Issue by KochamCie** [rickbergfalk/sqlpad#242]
emmm. I m new to this amazing project :)
I wonder if we can reformat sql ...would be nice

**Comment by rickbergfalk** [comment]
Hi @KochamCie - I'm glad you like the project! 

I was *almost* going to close this request as SQL formatters in JavaScript haven't been that great. However I spent some time googling and found this library that might work out https://www.npmjs.com/package/sql-formatter

I'll leave this issue open as a feature request. 

If this lib can be integrated and can stand up to some test queries I throw at it I'll consider adding it in some time :)

**Comment by KochamCie** [comment]
thx~~

**Comment by KochamCie** [comment]
hi 
i just integrated the sql-formatter this afternoon.
But , honestly, i'm a javaer 0-0, I'm very noob to react or node .
And it wll be nice of you If you can review my pull-request .
I am worried that it will affect other functions

**Comment by rickbergfalk** [comment]
No worries! Would love to! Thanks for taking the time to contribute :)

**Comment by rickbergfalk** [comment]
implemented in #260

**Comment by rickbergfalk** [comment]
@KochamCie just a heads up - I'm going to remap reformat to `shift+return` since `alt+r` is kind of hard to get to on Mac. 

Running a query is changing to `ctrl+return` / `command+return` to match other editors so the shortcuts tie together nicely I think. 

Also adding a button for reformat :)
