### ISSUE TITLE
A problem and a suggestion

### ISSUE THREAD

**Issue by sgjr** [rickbergfalk/sqlpad#243]
I have used sqlpad for some day,It's a good tools.I have some problems need your help:

- I used the sqlpad to query the data, and the resulting time zone was UTC. 
- How  can I change the time zone

and  I have a suggestion for sqlpad:
- The prompt is not so perfect, after adding an alias to a table, it can't be prompted.like:
`select * from test as t1 where t1.XXX`

**Comment by rickbergfalk** [comment]
Hi @sgjr - What database are you querying against? Is this SQL Server by chance? 

Appreciate the suggestion about the prompt. That's on my todo list someday :)

The autocomplete is pretty hacked together. I'll add a separate issue to track that work

**Comment by sgjr** [comment]
Hi @rickbergfalk -The database I used is MySQL.
For example,I query a colunm in mysql server ,the value is
```
'2017-03-06 09:06:46'
```
then,I query it with sqlpad ,its value is 
```
03/06/2017 01:06:46
```
they are a difference of 8 hours. How can I fix it?

**Comment by rickbergfalk** [comment]
I'm looking into this - this is a recurring problem with the date logic in SQLPad right now. As it stands, If the time is a UTC timestamp or a timestamp with timezone, it should display properly in the grid. If not, it gets modified by whatever the timezone offset is.

To address this the mysql driver has a setting where the timezone of the server can be set, and it'll use that to handle things accordingly.

However, I'm thinking about the possibility of handling all dates as text, and only converting them for the chart? I don't know that this functionality is supported across the board though by all the different db drivers...

I'm going to experiment with things further and see what I can find out.

For the time being - you can try casting the date as text, or converting it to UTC timezone if you want it to display properly in SQLPad :(

Or perhaps running SQLPad under the same timezone as your db server?

**Comment by rickbergfalk** [comment]
@sgjr is the timezone of your MySQL server different than the timezone of wherever SQLPad is hosted? 

If so, on the box SQLPad is hosted, try setting the TZ env var to the time zone to the same as your MySQL server. For example if utc: `TZ=UTC sqlpad --port 3000 ...`

**Comment by rickbergfalk** [comment]
Actually thinking about this last night - I think the ideal case is to set SQLPad's node process to use UTC time all the time. When dates are encoded into JSON and sent to the browser, the assumption is they are UTC dates.

**Comment by sgjr** [comment]
I'm sorry, these days are a bit busy and I have no time to reply. I modified the configuration the day before yesterday to solve this problem. Today, I see you fix this problem on GitHub. You are very hardworking and very good.

**Comment by rickbergfalk** [comment]
The date fixes are now in place on npm in version 2.4.0
