### ISSUE TITLE
Highlight if Query Edits are Unsaved

### ISSUE THREAD

**Issue by saqshamagrawal** [rickbergfalk/sqlpad#263]
First, thanks for the software, it's been a real help. 

Issue: Any edits to a saved query do not tell the user that there are unsaved edits. While browsing through multiple queries, this creates a chance that edited queries will not be saved. I have lost more than a few edits due to this. Now, I end up clicking Save all the time, even on queries that have been saved, since I don't recall which queries might need saving.

Potential solution: If a query has unsaved changes, the query page should show that. 

Thanks a bunch either way!

**Comment by rickbergfalk** [comment]
Thanks @saqshamagrawal! Glad you like it. 

I've been thinking about this too - How about an * in the query name to indicate it being unsaved, and if the user tries to navigate away on unsaved work, a pop-up could appear to make sure the action is intended?

**Comment by saqshamagrawal** [comment]
That would solve it perfectly, and in line with what most users are
familiar with.

Appreciate the quick response.

**Comment by rickbergfalk** [comment]
I've added this in to version 2.4.0 now available on npm. Instead of putting the * in the query name, its on the save button... there were changes to the query editor that made putting it on the name impractical. Navigating away with unsaved changes will now prompt the user.
