### ISSUE TITLE
Assigning Connections to Users

### ISSUE THREAD

**Issue by marcosfreccia** [rickbergfalk/sqlpad#264]
Sorry if this is not the right place for it. I found it this tool a few days ago and I am still testing it. So far, really good! So, thanks for the work put into it.

However, I would like to understand if it is or it would be possible to assign specific connections created to users. The practical example for that would be.

1) I have a central environment with hundreds of databases
2) UserA can only connect to Databases: DB_A, DB_B and DB_C.
3) Using SQLPAD I create 3 connections, one to each DB and assign the rights to the UserA to see those connections only.

Do you see that as an improvement? Would that be difficult to implement?

**Comment by rickbergfalk** [comment]
Thanks glad you like it! And this is the perfect place for this request 👍 

Currently this is not possible. 

Difficulty of implementation depends on the implementation... There is a related request in issue #145, solved in a private repo via an ACL implementation. A simpler implementation would probably work, but it would start to get messy as more rules are added and customizations are wanted... I think some form of an ACL would be the ideal route to go but that's a larger more difficult change.

I think if a flexible, not-too-complicated ACL/RBAC implementation would be a great improvement to SQLPad though...

**Comment by rickbergfalk** [comment]
Unfortunately I'm at the point where something like this is beyond the scope of SQLPad. I have less and less time these days for the project, so I won't be bringing much of any new features. I'm sure this is probably clear by the lack of response to these tickets :)

**Comment by rickbergfalk** [comment]
Re-opening this issue as it is being addressed in a way by #502

**Comment by rickbergfalk** [comment]
#502 has been merged and now available in v4 release
