### ISSUE TITLE
How to run docker with predefined config

### ISSUE THREAD

**Issue by VladimirKovalenko** [rickbergfalk/sqlpad#272]
Hello.

Thank you for such a good application. 
I want to use sqlpad for visualize data for my team.
My idea is to run docker image on the VM in cloud.
Docker is something new for me, and I spent a lot of time tring making workable configuration.
I want to run sqlp with predefined configuration users.db/queries.db etc.
I just do not want to configure all users/query each time when docker is restarted.

I tried different approaches, but no success:
i bound volume to the sqlpad with all my custom configuration and tried

1. run my custom docker-entrypoint which references to the custom directory
2. copy custom configs to the /var/lib/sqlpad
3. remap entrypoint from config to another file
4. set custom directory as a parameter
and other options, no result, usually i have such error

/usr/local/lib/node_modules/sqlpad/server.js:183
  if (err) throw err
           ^

Error: Failed to flush to storage
    at /usr/local/lib/node_modules/sqlpad/node_modules/nedb/lib/storage.js:63:19
    at FSReqWrap.oncomplete (fs.js:123:15)

I hope the you can make a hint or share your own experience how you use it.

Thank you in advance.

**Comment by rickbergfalk** [comment]
Thanks @VladimirKovalenko - 

I haven't done much with using SQLPad via docker. I have several different installations installed from npm.

This has been something I've been meaning to explore though. Instead of copying the configs, are you able to mount a volume to the docker container with the files, and set that directory as the SQLPad --dir (or SQLPAD_DB_PATH env var)?

I think the error you're running into deals with a permissions issue with nedb not being able to write to the file or some sort of cache mismatch...

**Comment by VladimirKovalenko** [comment]
Hello, thank you for response.

Sorry for postpone with answer, new year holiday, you know)

I tried different options how to put my own config from repository to the VM with docker container.
Below you can find my example with comments, maybe it will be helpful for somebody.
It is the simplest and shortest way that I found.

```
# open shell (can be done in cmd with openSSH)
start sh.exe
# copy files and folders to remote server
scp -r C:/configRepository/db username@sitename.eastus.cloudapp.azure.com:/tmp
# connect to the VM machine
ssh username@sitename.eastus.cloudapp.azure.com
# create a new docker container
docker create -it --restart="always" --name monitor -p 3000:3000 sqlpad/sqlpad
# copy files from temporary volume to the configuration folder
docker cp /tmp/db/. monitor:/var/lib/sqlpad
# start container
docker start monitor
# connect to the container to check config filed
docker exec -it monitor sh
```

> Instead of copying the configs, are you able to mount a volume to the docker container with the files, and set that directory as the SQLPad --dir (or SQLPAD_DB_PATH env var)?

I do not find the way to change SQLPad --dir from the command line, without forking and adjusting container.
