### ISSUE TITLE
Query result table sorter

### ISSUE THREAD

**Issue by 2048** [rickbergfalk/sqlpad#273]
It's really a good tools for generating the data report from database. 

But is there any plan for adding the sorter for the query result table ? and the global filter for the table too.

(For now, we should download the data from website and filter it in excel file. )

**Comment by rickbergfalk** [comment]
Thanks @2048! 

There's no plan for a filter - that should be done in the SQL query since it'd be the most efficient for the database, network, and application. I'm thinking about adding query parameters though.

Sorting the result table is something I'd consider adding though

**Comment by rickbergfalk** [comment]
Going to close this request. Working on another product that uses SQL as an interface and this request comes up in that product as well every now and then. In discussions with users of that product, users are generally hoping that the grid filtering or sorting is somehow applied at the query level, rerunning a query and returning the new result. 

In addition to potentially adding some confusion, it adds some complexity to SQLPad, which I'm trying to limit.
