### ISSUE TITLE
Gratitude

### ISSUE THREAD

**Issue by JaleelLiu** [rickbergfalk/sqlpad#276]
Thanks for this project. to replace phpmyadmin. i just want to thank your team.

**Comment by rickbergfalk** [comment]
Thanks @JaleelLiu glad you are finding it useful :)

**Comment by jmgarnier** [comment]
thank you, I was able to see some charts after 15min of reading the doc and playing around.

Ping me if you need a linkedin recommendation someday

**Comment by rickbergfalk** [comment]
Not sure how I missed this -- thanks for the kind words @jmgarnier! They are much appreciated :)
