### ISSUE TITLE
Is it possible to plot arrays without unpacking them with each index,entry as a separate row.

### ISSUE THREAD

**Issue by Chumbaloo** [rickbergfalk/sqlpad#283]
I.e. is it possible to plot something like this:

![image](https://user-images.githubusercontent.com/13964651/35075781-28649f04-fc49-11e7-999a-0244765ebf79.png)

**Comment by rickbergfalk** [comment]
Hi @Chumbaloo. Unfortunately not. There are a lot of assumptions based on a more normalized result set.
