### ISSUE TITLE
about the cache.db

### ISSUE THREAD

**Issue by guohao111** [rickbergfalk/sqlpad#31]
when I run the sqlpad, I notice that every time when I reload the schema-info of the connections(I use a mysql connection),it will porduce a new cache-key in the cache.db file, so  I think in the schema-info.js 
if(!cache || reload) should change to if(!cache). In that case, when reload it, it will not produce a new cache record.

**Comment by dcelasun** [comment]
Reloading is supposed to fetch the latest schema info from the db so `if (!cache)` wouldn't work. Though we could simply update the existing key instead of creating a new.

**Comment by rickbergfalk** [comment]
I took a look into this. A new row is being added each save, but it is reusing the cache key and _id. The data storage library SqlPad uses, NeDB.js, does this by design. Every so often it will go through and compact the .db files.

Currently SqlPad compacts the NEDB.js .db files once a day, which means if you refresh the schema a lot the schema cache .db file could get quite large.

Should I make this more frequent? Maybe once an hour? 30 minutes?

**Comment by guohao111** [comment]
Since you have designed that, I think the frequence is not matter.Thank you.

**Comment by rickbergfalk** [comment]
Just to follow up on this - I've decided to have SqlPad compact the database files every 10 minutes. Frequently saving queries and refreshing schemas could cause some file bloat. Taking care of this more frequently also means less work each pass, so I don't anticipate any noticeable impact.

**Comment by deepvoice** [comment]
Apologize for reopening but ran into an issue.
One of our DB's became seriously overloaded and after a weekend we had queries stacked to the ceiling. 
Would it be possible to add a manual refresh button and a config entry that would allow the disabling of the automagic schema requests?
I envision that the manual button would work always, but with auto-refresh not disabled, it would continue to work as it does now.

**Comment by rickbergfalk** [comment]
@deepvoice was SqlPad's schema autorefresh the source of the query backlog? I'll have to check but I believe SqlPad defaults to using the schema cached in it's local database. The only time a schema query should be run is when a cached copy isn't available or an updated schema is requested via the refresh button.

**Comment by rickbergfalk** [comment]
I should add - this issue was regarding the automatic database compacting for the embedded database SqlPad uses.

**Comment by deepvoice** [comment]
This query:
SELECT (CASE t.table_type WHEN 'BASE TABLE' THEN 'Tables' WHEN 'VIEW' THEN 'Views' ELSE t.table_type END) AS table_type, t.table_schema, t.table_name, c.column_name, c.data_type, c.is_nullable FROM INFORMATION_SCHEMA.tables t JOIN INFORMATION_SCHEMA.columns c ON t.table_schema = c.table_schema AND t.table_name = c.table_name WHERE t.table_schema NOT IN ('information_schema', 'pg_catalog') ORDER BY t.table_type, t.table_schema, t.table_name, c.ordinal_position
