### ISSUE TITLE
Multiple queries no longer display all results. 

### ISSUE THREAD

**Issue by Chumbaloo** [rickbergfalk/sqlpad#321]
The following used to work:

```
select * from myFunction(x1,y1);
select * from myFunction(x2,y2);
select * from myFunction(x3,y3);
```

Now I only get results when I do a single query in the query pane. 

`select * from myFunction(x1,y1);`

Any more than one produces a blank response.

The only workaround at the moment is to have something like this, which produces the desired result:

```
(select * from myFunction(x1,y1))
union all 
(select * from myFunction(x2,y2))
union all
(select * from myFunction(x3,y3));

```

Info about version:
![image](https://user-images.githubusercontent.com/13964651/37804842-8202d81e-2e8a-11e8-96bf-a1d55b1ee2aa.png)

**Comment by rickbergfalk** [comment]
Hi @Chumbaloo - Unfortunately displaying multiple query results was a bug of sorts. SQLPad is designed to handle a single query at a time. Multiple result sets are unsupported at this time.
