### ISSUE TITLE
unable to handle static files with nginx proxy over directory

### ISSUE THREAD

**Issue by lkjangir** [rickbergfalk/sqlpad#323]
I am unable to setup proxy over directory with nginx. I am configuring **example.com/sqlpad** proxy to sqlpad, but /javascript, /vendor and /static directories are pointing to root url rather than /sqlpad. I have tried location directive to handle static files but it doesn't help. Can you please help me here and provide nginxx proxy configuration for /sqlpad directory?

**Comment by nagaraju02** [comment]
I am also facing the same issue. I am able to setup reverse proxy to root **/**  but unable to setup this at any directory ie.  example.com/sqlpad

It fails at loading static files from /javascripts  directory.

**Comment by rickbergfalk** [comment]
Sorry for the delay in getting to this!

I think setting the --base-url flag will help get this working. Could you try setting env var `SQLPAD_BASE_URL` or cli flag `--base-url` to `/sqlpad`?

Before doing that though, **be sure to update to the latest version of sqlpad, 2.5.2**. There was a bug that was preventing sqlpad from functioning properly when running it under a different root path. 

Let me know if this solves the issue, or if there is something else going on.

**Comment by lkjangir** [comment]
Thank you Rick,
It worked for me after setting up the suggested changes. Thanks once again.

**Comment by rickbergfalk** [comment]
You're welcome! glad to hear things are working again
