### ISSUE TITLE
unable to download csv

### ISSUE THREAD

**Issue by rgupta2** [rickbergfalk/sqlpad#325]
I am running sqlpad on my local mac and configured a connection to a local PostgreSQL database.
A `select *` query on a short table shows up all the 19 rows but when I click download, it takes me to a `http://localhost:3000/download-results/00aa1e00-334c-11e8-aae5-27937b010554.csv` page with "Not Found" message.

There are other issues too that I experienced but in terms of stability like once something goes wrong, sqlpad interface doesn't seem to recover even after refresh but those details I will share later.

**Comment by rickbergfalk** [comment]
Hi @rgupta2 - May I ask how you are running sqlpad? Are you running it from a clone of this repo with `npm start`?

I've noticed the same issue when running it that way - requests from the browser are being forwarded through a proxy and the file download is not making it through.

If you are running it via `npm start`, try first running `npm run build`. Then once the ui is built, run `npm start` again, but instead go to http://localhost:3010, which will server the compiled front-end from the sqlpad server directly.

If you're running sqlpad installed via docker or npm and still seeing this please let me know

**Comment by rickbergfalk** [comment]
I'm going to go ahead and close this issue - let me know if you're still having problems getting things set up and we can reopen
