### ISSUE TITLE
Password Reset Link Not properly working with `--base-url` option

### ISSUE THREAD

**Issue by snilaxan** [rickbergfalk/sqlpad#328]
Hi All,

Started sqlpad app using following command with --base-url :
sqlpad --dir sqlpad/data --port 3000 --ip 0.0.0.0 --base-url '/sqlpad' --save

And configured reverse proxy on apache2 service. It's working correctly but when I click on Password Reset Link, It's redirecting to `http://localhost:3000/password-reset/95fb3ca2-3a96-4177-83c6-29574730d5a7` 

But It should be redirected to: `http://localhost:3000/sqlpad/password-reset/95fb3ca2-3a96-4177-83c6-29574730d5a7`

Picture-1: Password Reset Page
![image](https://user-images.githubusercontent.com/3293837/38140093-eaea3fc8-344f-11e8-8e7f-94152e387c5d.png)

Picture-2: Redirect URL
![image](https://user-images.githubusercontent.com/3293837/38137582-169a1c36-3443-11e8-9d60-2725072dc9be.png)

Please try to fix this issue, To use the --base-url option properly in SQLPad.

**Comment by rickbergfalk** [comment]
Hi @snilaxan - I just published a fix for this in version 2.5.4. Let me know if you still run into the issue.
