### ISSUE TITLE
0 should not be converted to a string

### ISSUE THREAD

**Issue by razumau** [rickbergfalk/sqlpad#338]
Because of the #163 fix, numbers with a leading zero change datatype for the column to “string” (https://github.com/rickbergfalk/sqlpad/blob/8e59c391f6ea09f86d0d0b5433ac4ca12d371c3b/server/models/QueryResult.js#L106). However, when this number is zero it leads (no pun intended) to unexpectedly broken charts.

By the way, thanks for all your work and props for using taucharts!

**Comment by rickbergfalk** [comment]
Thanks for reporting @razumau - I'll take a look at this.

Out of curiosity, is the column this is happening to a BIGINT column or the result of a COUNT(*) or SUM() or some other aggregate?

**Comment by razumau** [comment]
It was the result of `COUNT(role)` where role could be null, so the row was `NULL; 0`. It was in fact an error in query (so it’s not a really important issue), but it was hard to catch since at first it simply looked like the graph was wrong.

**Comment by rickbergfalk** [comment]
This is now addressed in 2.5.5 available on docker and npm
