### ISSUE TITLE
Unhandled Rejection (TypeError): Cannot read property 'baseUrl' of undefined

### ISSUE THREAD

**Issue by thesobercoder** [rickbergfalk/sqlpad#340]
I just cloned the repo and ran `npm start`. I saw the web page load up at `http://localhost:3000` and then this error

     Unhandled Rejection (TypeError): Cannot read property 'baseUrl' of undefined

I'm running it on the following config

    OS: Windows 10
    node: v8.9.2
    npm: v5.5.1

![Error](https://i.imgur.com/sQOjFRs.png)

**Comment by rickbergfalk** [comment]
I've just noticed that too - It's because I left the baseUrl in the
development config... for short term workaround navigate to
http://localhost:3000/sqlpad/ and it should work for you. I'll revert the
baseUrl change for dev purposes

**Comment by thesobercoder** [comment]
Unfortunately browsing to `http://localhost:3000/sqlpad/` still gives the same issue.

**Comment by rickbergfalk** [comment]
hmm - I'm not sure what would be happening then offhand. I'll take a look
later this weekend. Actually should probably update that check to ensure
json.config exists too.

**Comment by rickbergfalk** [comment]
I haven't experienced this issue since the change - let me know if you're still running into issues after pulling in latest master and we can reopen
