### ISSUE TITLE
download in Excel

### ISSUE THREAD

**Issue by LeandroFavero** [rickbergfalk/sqlpad#35]
SQLPad is great!!!

One suggestion: SQLPad already have csv download option. Could have excel option too? This will eliminate one step, save in csv, import to Excel, send to user. There are this guy here:
https://github.com/mgcrea/node-xlsx

Very nice and simple.

**Comment by rickbergfalk** [comment]
Thanks @LeandroFavero! 

I'll have to check it out - I think it'd be a good addition.

**Comment by rickbergfalk** [comment]
This has been added to the latest version of sqlpad, now available on npm :)
