### ISSUE TITLE
iframe support in version 2.5.4

### ISSUE THREAD

**Issue by creichn** [rickbergfalk/sqlpad#351]
Hello,
Lately I updated SQLpad in version 2.5.4
The issue occurred is that some graphs I had added as iframes currently do not work due to the fact that iframe support was blocked.

Can you please assist on this?

**Comment by rickbergfalk** [comment]
Sorry about that @creichn - This probably happened when the security settings were tightened in 2.5.0. Do you happen to know what version you installed by chance? 

If you used npm to install, you should be able to downgrade back to 2.4.2 with `npm install -g sqlpad@2.4.2`

I'll take a look into disabling the iframe security restriction since that was a common use of the single chart display modes.

**Comment by creichn** [comment]
Thank you very much @rickbergfalk . 
Indeed I used npm to install version 2.5.4.
Before downgrading to version 2.4.2 , would it be possible to let me know approximately when you think you will be able to disable the iframe security restriction ?
I am asking since I need the feature of "Require Login for Table/Chart Links" (so if I downgrade I will lose the feature)

**Comment by rickbergfalk** [comment]
I will see if I can get a new release published in the next day or two. I think I have it fixed in master, but haven't built a setup to test it

**Comment by rickbergfalk** [comment]
Thanks I appreciated it! 

I've published 2.5.5 to npm and docker. Hopefully should resolve your issue. I didn't set up a test environment to confirm, but I'm fairly certain the frameguard protection is what did it, and that is being rolled back in 2.5.5. Let me know how it goes - for now I'll close this issue

**Comment by creichn** [comment]
Hello @rickbergfalk . I installed the latest release 2.5.5. Indeed the iframe worked. The only problem appeared is that some graphs I have prepared in the past do not work after the update.
So despite the fact that queries return results, it seems as if that the graphs cannot identify the column names. The result is that I get a message "not in query result"

![image](https://user-images.githubusercontent.com/4805115/39230572-9efa28f6-486f-11e8-92bc-74e2458c35e5.png)

So even though my result returns data (image below)

![image](https://user-images.githubusercontent.com/4805115/39230623-cd578cd4-486f-11e8-82d1-205884540bde.png)

I get a message "not in query result" when trying to see the chart.

This graph was working properly before the update.

**Comment by rickbergfalk** [comment]
Sorry about that! This was from me fixing a different chart related issue I came across, and didn't think about the case you're experiencing. Going to revert that commit and publish a new patch version - will attempt fixing the charting in a separate release

**Comment by rickbergfalk** [comment]
@creichn 2.5.6 is now available via usual channels.
