### ISSUE TITLE
Generic backend support

### ISSUE THREAD

**Issue by clach04** [rickbergfalk/sqlpad#356]
Any thoughts or plans for supporting more/arbitrary backends? Using something generic that isn't tied to a particular backend. E.g.

1. ODBC (https://www.npmjs.com/package/odbc seems so be a live one) 
2. JDBC (there seems to be two viable options https://www.npmjs.com/package/jdbc and https://www.npmjs.com/package/node-any-jdbc)
3. Some sort of proxy/bridge using something like https://sourceforge.net/projects/sqlrelay/

From reading https://github.com/rickbergfalk/sqlpad/issues/22#issuecomment-87591891 I suspect if support was added it would need to be optional due to native dependencies?

**Comment by rickbergfalk** [comment]
I would love support for a more standardized database driver connection method! What held it back in the past as been lack of maturity of the solutions, and the native dependencies being difficult to set up for people (must have build tools installed, specific python version, etc)

The odbc/jdbc solutions linked look like they are in better shape than when I first checked. 

If you wanted to undertake adding support for one of them and documenting how to set it up I'd be all for it.

All the driver stuff has been consolidated, so if the usage is modeled after an existing connection it should just work https://github.com/rickbergfalk/sqlpad/tree/master/server/drivers.

The only tricky part would be making it optional... but I'm pretty sure npm has an optional dependencies support, and the require() could be wrapped in a try/catch to validate whether it installed successfully maybe?

**Comment by clach04** [comment]
@rickbergfalk I've posted https://github.com/clach04/sqlpad/tree/unixodbc_squashed which I would like some feedback on. It is enough to get sqlpad up and running against some Actian's databases (which I have a vested interest in working :)); ActianX, Vector, and Ingres. It also runs against sqlite3. I've not tested any other DBMS backends.

It does require odbc support, which in turn requires a C compiler and node-gyp, however if `npm install odbc` works, its ready to go!

Schema lookup has been implemented with a simple query against INFORMATION_SCHEMA.columns, not all backends support this so this can be overridden in connection settings with the `schema_sql` setting. I've provided examples for sqlite (NOTE limited schema information in sqlite, specifically no column information without either parsing DDL or a query against the object) and Ingres.

To get the sqlite demo going unixodbc and the driver is required, under Ubuntu this can be installed via:

    sudo apt-get install libsqliteodbc

The test/demo should work without any additional config changes to the .ini files used for UnixODBC and no need for a DSN (but one could be created if preferred).

I thought I'd ping you before opening a PR, there is some tidy up to do but I'd rather share current progress early.

**Comment by rickbergfalk** [comment]
Thanks @clach04 looks really good so far! 

Any thoughts on how this could be made testable on other setups? Docker has been a nice way to provide a database across a variety of platforms, but understandably not all databases have that as an option.

I only ask because I'd want a low-friction way to run the tests myself if an issue came up or I end up refactoring the way the db integrations are done. I suppose the odbc test doesn't need to be an Actian test specifically - just something to test the integration with the odbc lib.

On the other hand... if this is left as a separate step by the end user and not something supported out of the box via an `npm install sqlpad -g`, then I'd be fine bringing this in and not having flexible tests for it right away, adding documentation disclosing there will be some extra work to get this up and running :)

Just some minor nit-picks on style... I've been trying to use `const` and `let` over `var` for variable declarations, and moving away from single-line conditionals (is that even what they are called?) and favoring something like 

```js
if (config.user) {
  cn = cn + ';Uid=' + config.user;
}
```

Not a big deal though -  I haven't been able to go through and clean everything up yet and I have yet to set up the eslint rules for stuff like this.

**Comment by clach04** [comment]
@rickbergfalk on testing on other setups; originally I was thinking sqlite3 would be a good idea. The datatypes are limited and the meta data interface is also limited but its a relatively easy setup (no passwords or user management), I'd be interested to hear what your thoughts are on that. My thought was include the sqlite test shell script (only) in the PR.

I do not personally have experience with Docker, if you already have a setup with Docker that you rely on for testing, then MySQL, Microsoft SQL Server, etc. may be a good option as you already have it with the extra odbc driver depedency. Thoughts? The existing SQL Server test script could be used with very few changes if you'd prefer that route.

Let me have a quick scan on style items you identified.

I personally would be OK manually installing the extra dependencies, adding odbc would suddenly mean a C compiler is needed but a try on the require would probably resolve that.

**Comment by clach04** [comment]
@rickbergfalk just committed dd372047f39c9df4d2614807876da85a856894ef, hopefully takes care of style comments.

**Comment by rickbergfalk** [comment]
sqlite3 would be a good test case. I haven't made a docker image for testing yet, but that'd be a good route to go. So far testing has consisted of running the node scripts locally, but there's no reason that couldn't also be inside a container. I'm fine with that being something I tackle as an additional step after this is merged. 

Wrapping the require in a try catch should work. Actually npm has some updated docs on using optionalDependencies which is quite nice: https://docs.npmjs.com/files/package.json#optionaldependencies

Once you open the PR, I can help test and ensure things are working well without the additional dependencies installed

**Comment by clach04** [comment]
@rickbergfalk posted PR issue #366 - it is going to need some polishing and attention from you. Hopefully not too much :-)

**Comment by clach04** [comment]
Sorry for delay @rickbergfalk , I can see the report and the error it generates. I've pushed a change that I believe will address the problem.

**Comment by rickbergfalk** [comment]
Thanks @clach04 - I'll plan on merging once #369 is fixed and a patch is published. 

Regarding your comment about column metadata not being available for sqlite3, does the default query finish successfully with nulls in columns it does not support or does it error out?

**Comment by rickbergfalk** [comment]
This is now published to npm declaring odbc as an optional dependency. Realized that odbc support could be built-in to the docker image if someone wanted to support it...

Thanks again @clach04

**Comment by clach04** [comment]
Thanks, linking to https://github.com/rickbergfalk/sqlpad/wiki/ODBC for completeness.

**Comment by gk-patel** [comment]
It would be good if ODBC could be made available in Docker. I dont know how much work it is for you, but would appreciate if it could be added to the backlog. Thanks for consideration and the nice tool.

**Comment by clach04** [comment]
My 2 cents, ODBC support in the Docker image is extra space overhead that would be unused without an ODBC driver.

So maybe a example Dockerfile would be useful, but that's a different topic. @gk-patel you could open a new ticket and copy/paste your proposal or submit a PR, this issue was closed 3 years ago.
