### ISSUE TITLE
systemd service not working

### ISSUE THREAD

**Issue by nicolamarangoni** [rickbergfalk/sqlpad#357]
I created a systemd service:
```[Unit]
Description=Service to run SQLPad Daemon
Documentation=
[Service]
User=sqlpad
Group=sqlpad
Type=forking
WorkingDirectory=/opt/sqlpad
ExecStart=/usr/local/bin/sqlpad --port 3000 --dir /opt/sqlpad/db
[Install]
WantedBy=multi-user.target
```
When I start it with `systemctl start sqlpad`, it doesn't return to the prompt, but I cann access the tool at http://hostname:3000
However, after some minutes, the `systemctl start sqlpad` returns to the prompt with a timeout error and sqlpad stop working.
Are there generic issues with nodejs applications running as a systemd service?

**Comment by rickbergfalk** [comment]
Hi @nicolamarangoni 

I'm assuming you installed sqlpad via npm?

Unfortunately I don't know too much about systemd setups. I did use upstart years ago though, and remember when I did I had some permissions issues to work out when I had installed SQLPad via npm.

I'm not sure how to go about debugging this, but if you wanted to try running sqlpad from the git repo that might provide more insight as to what is going on.

To build and run sqlpad from the repo you can do

```sh
git clone sqlpad into desired directory
cd sqlpad-directory
npm install
npm run build
node server/server.js --dir ./path/to/db/file --port 3010 --debug
```

Wish I could be of more help! Let me know what you find out or if I can help answer any questions

**Comment by nicolamarangoni** [comment]
Hi @rickbergfalk I didn't notice that I left "forking" through copy/pasting from another service.
"simple" is the right option!

**Comment by jmutai** [comment]
My systemd works fine, check:

https://computingforgeeks.com/sqlpad-web-based-sql-editor-for-mysql-postgresql-sql-server/
