### ISSUE TITLE
sh: 1: concurrently: not found

### ISSUE THREAD

**Issue by clach04** [rickbergfalk/sqlpad#359]
Following "Development" instructions results in:

    > sqlpad@2.5.6 start /home/ingres/sqlpad
    > concurrently "npm run start-server-dev" "npm run start-client-dev"

    sh: 1: concurrently: not found
    npm ERR! file sh
    npm ERR! code ELIFECYCLE
    npm ERR! errno ENOENT
    npm ERR! syscall spawn
    npm ERR! sqlpad@2.5.6 start: `concurrently "npm run start-server-dev" "npm run start-client-dev"`
    npm ERR! spawn ENOENT
    npm ERR!
    npm ERR! Failed at the sqlpad@2.5.6 start script.
    npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
    npm WARN Local package.json exists, but node_modules missing, did you mean to install?

    npm ERR! A complete log of this run can be found in:

when issuing `npm start`

Resolved by issuing:

    npm install concurrently

I'm using nvm on this machine to manage node.js, I don't think its relevant, documenting in case its significant.

**Comment by rickbergfalk** [comment]
Sorry about that! My instructions were missing a step. Before running `npm start` you need to run `npm install`. 

I've updated the documentation - let me know if you have any other questions :)
