### ISSUE TITLE
Enhancement: Right Click Table Name Copy

### ISSUE THREAD

**Issue by deepvoice** [rickbergfalk/sqlpad#36]
Having completx table names (especially in vertica), it would help to be able to right click the table or column name and be able to paste the fully qualified path.

**Comment by dcelasun** [comment]
I'm not sure I understand. In the context of Vertica, what do you mean by complex table names and fully qualified paths?

**Comment by deepvoice** [comment]
Vertica queries require "fully qualified" paths.

So you might have a fully qualified path that looks like: "PlutoServerDatabase1"."cronologicalDataWebproxy132"."postitionalCorrectionIndex"
Having to type that every time you want to run a manual query can be maddening. A simple right click to save fully qualified path would be awesome. There is a NPM module for it somewhere I believe.

**Comment by dcelasun** [comment]
Oh, now I get what you mean. Yes, the schema name is necessary, but the database name is not. In your example:

    cronologicalDataWebproxy132.postitionalCorrectionIndex

would work just fine. Anyway, let me see if we can do something about this.

**Comment by deepvoice** [comment]
Vertica would be: database->collection->table->column so you are correct in saying database name is not required but it may still have 3 positions

**Comment by dcelasun** [comment]
Indeed. I think we can make something generic enough that will work with all drivers.

**Comment by deepvoice** [comment]
https://www.npmjs.com/package/rightclick

**Comment by rickbergfalk** [comment]
In the SELECT clause of the query, do you need to supply the schema and table as well? Or can it be inferred or aliased? 

Another option that could be explored is using autocomplete in the Ace editor component. I wouldn't have the skills to do anything fancy - it'd just be a list of fully qualified schemas, tables, and maybe column to choose from. Could get annoying for people where the fully qualified names aren't necessary though.

**Comment by rickbergfalk** [comment]
I took a look at the rightclick module - looks like its for filesystem manipulation, not copy operations in the browser. I'll do some research to see whats available

**Comment by dcelasun** [comment]
> In the SELECT clause of the query, do you need to supply the schema and table as well? Or can it be inferred or aliased?

For Vertica, yes, you need to specify the schema and table at all times.

**Comment by rickbergfalk** [comment]
that would be a bummer to have to write out every time...

I wasn't aware that clipboard operations aren't consistently supported across browsers, and that its usually solved via flash. https://hacks.mozilla.org/2015/09/flash-free-clipboard-for-the-web/

Looks like we would use something like ZeroClipboard? http://zeroclipboard.org/

**Comment by dcelasun** [comment]
Yeah, zero clipboard seems like a good fit.

**Comment by rickbergfalk** [comment]
reading about zero clipboard. I don't think we can support copy on right-click. Instead I think it'll have to be a regular left click, which already expands the schemas and tables. 

What if a little copy icon was added to the right of every item in the tree? It would be visually muted so it isn't too distracting. Or maybe the copy icon appears to the right on hover of the item? 

Now that I think about it the latter might be the most efficient way to implement it. We wouldn't want thousands of copy buttons (which are little flash movies apparently) being created.

**Comment by dcelasun** [comment]
> Or maybe the copy icon appears to the right on hover of the item?

Yep, this one sounds best to me.

**Comment by rickbergfalk** [comment]
I've got this worked out and added to the master. It'll go out next release of SqlPad. I decided to make it opt-in, since it could be distracting to some. I could be persuaded to have it turned on by default though.

And sorry @dcelasun I just noticed you said you'd look into it - didn't mean to steal your initiative :) I've been working a bunch in SqlPad so I just figured I'd jump on it.

**Comment by dcelasun** [comment]
@rickbergfalk No worries, my attempt would probably had to wait until the weekend :)

**Comment by rickbergfalk** [comment]
Got excited about all the changes and published things to npm. This can be enabled in version 1.9.0
