### ISSUE TITLE
whitelist problem

### ISSUE THREAD

**Issue by clach04** [rickbergfalk/sqlpad#360]
I setup sqlpad and did *not* enter a whitelist for the domain.

I did invite a user and they got a "not white listed" error message when they attempted to sign up. I'd entered their name in mixed case, they entered their name in lower case. Once they attempted a 2nd time with the exact case I used for their email they could signup.

**Comment by rickbergfalk** [comment]
Thanks for reporting this! I will look into changing it to being case insensitive
