### ISSUE TITLE
Can it support for Hbase Hlive clickhouse  database ?

### ISSUE THREAD

**Issue by zhaodagang** [rickbergfalk/sqlpad#367]
Can it support for Hbase Hlive clickhouse  database ?

**Comment by rickbergfalk** [comment]
Unfortunately those are not supported databases at this time. Pull requests would be gladly accepted if someone would like to work on them :)

**Comment by rickbergfalk** [comment]
ClickHouse is added in `master`/ `latest` on Docker Hub, and Hbase and Hive are supported via the ODBC integration.

Open to accepting PRs if anyone wants to work on adding Hbase/Hive specific drivers, but going to close this issue for now.

**Comment by dengc367** [comment]
@zhaodagang you can use presto connection instead. presto can support hive connector  and [hbase connector](https://github.com/analysys/presto-hbase-connector)
