### ISSUE TITLE
How it signin?

### ISSUE THREAD

**Issue by zhaodagang** [rickbergfalk/sqlpad#368]
After run npm install.  it let me sign in .  ?
usename and password ?
![11](https://user-images.githubusercontent.com/33817963/40596736-6bc3a8da-626f-11e8-8b71-cadf7d54766e.jpg)

**Comment by rickbergfalk** [comment]
@zhaodagang You'll need to sign up first, which will create an admin account. Once that is created, you can sign in with that, and sign up will be allowed for only people that have been whitelisted in the application.

Let me know how it goes
