### ISSUE TITLE
Enhancement: Queries from the URL

### ISSUE THREAD

**Issue by deepvoice** [rickbergfalk/sqlpad#37]
Not sure if there is a way to do this already.

On some of my scripts, it would be great to send the user a link based on programmatic variables (sending them to a saved query won't work because the script result is dynamic) and have the option to force a CSV download.

example: http://localhost:3000/querie/database_name?"select * from table_name",csv=true

**Comment by rickbergfalk** [comment]
There isn't a way to do this in SqlPad currently. I'd want to get input from others on this though. I'm not sure if this would create a security concern or if its no more dangerous than what SqlPad already allows. 

Are the scripted queries similar in a way, just with different parameters? 

Something I've been thinking about is having some way of defining custom variables or text replacement parameters, and then being able to run a query on that. 

For example, say you have a complicated query called "Sales for Department". You wouldn't want a copy of the query for each department, and you don't want to have to keep editing the query to change the department. 

In the query, maybe you could put ```WHERE department = '{departmentparameter}' ```. When the query is  run, it'd prompt for the value to use for {departmentparameter}. Or maybe a form is created in a sidebar or something to the right. 

This could be integrated in the url too, something like http://localhost/query-result/<queryid>?departmentparameter=thedepartmentname. Optionally too a the format could be specified. 

We end up back to the url executing SQL, but at least its predefined? 

I don't know if this gets towards what you're trying to solve or if a generic url to run SQL would be easier. Something to consider - I think the url parameters might need to be encoded correctly, and that could be a hassle to do for a whole SQL statement...

**Comment by deepvoice** [comment]
How about premade query with variables in order

Http://localhost:3000/q=<query name>?1=v1&2=v2&3=v3&refresh=10&type=(vis or
data)
(Refresh: see other enhance request )

**Comment by dcelasun** [comment]
I'm -1 on this idea. First of all, it seems out of scope as it's more suited for a command line client, like `mysql` or `vsql`.

But even more than that, this would introduce the need to parse queries in sqlpad which can easily become a security concern. There is a reason why most databases have server-side parameter binding and string manipulation on the client side is heavily discouraged.

I also have additional concerns around non-ASCII character handling / escaping, but the paragraph above is more important.

**Comment by deepvoice** [comment]
Yes. I see what you mean. No worries close request
