### ISSUE TITLE
Error in title of https://rickbergfalk.github.io/sqlpad/installation-and-administration/

### ISSUE THREAD

**Issue by Naereen** [rickbergfalk/sqlpad#372]
Hi,
The `<title>` tag in https://rickbergfalk.github.io/sqlpad/installation-and-administration/ is wrong, and this can be easily fixed by moving the comment here
https://github.com/rickbergfalk/sqlpad/blob/73009c25d06c92aba7958e7b20b44d4b2979e13f/docs-source/layouts/_default/single.html#L3
just one line above (I'll let you do it).

**Comment by rickbergfalk** [comment]
I've removed the comment and corrected the header :)
