### ISSUE TITLE
Release version not including Content-Type in html headers

### ISSUE THREAD

**Issue by taranda** [rickbergfalk/sqlpad#373]
OS: MacOs 10.13.5
Node: 8.11.1
NPM: 6.1.0
sqlpad:  2.6.0 (installed with npm)
Browser: Chrome 67.0.3396.79

When running the published version of sqlpad, I get the following:

```
$ sqlpad
Port 80 already occupied. Using port 60939 instead.

Welcome to SQLPad!. Visit http://localhost:60939 to get started
```

Upon inspecting the network traffic from `http://localhost:60939`, none of the responses include a `Content-Type` in the header.

The is causing issues with my reverse proxy which replaces non-existent Content-Types which a default which then causes the app not to crash.

My problems aside, web apps should include `Content-Type` in the header.

Also, this only affects some requests.  `signin` has no `Content-Type` but `api/app` does.  Likewise, `static/bundle.js` and `tauCharts.min.css` are missing `Content-Type`.

Any help would be appreciated.

**Comment by rickbergfalk** [comment]
I poked around a bit and noticed that I get Content-Type on first load of static assets (with a 200 response code), and on subsequent pages a 304 response code.

This seems to be known/intended behavior: https://stackoverflow.com/questions/31099113/why-response-304-doesnt-have-content-type-header

Is there a way to handle this gracefully in your reverse proxy?

**Comment by taranda** [comment]
It has been surprisingly hard to figure out how to configure the proxy server to handle this correctly.  However, since sqlpad is working normally, it sounds like it is my problem to solve.  Thanks for your consideration.
