### ISSUE TITLE
strict MIME type checking prevent chrome from opening sqltab

### ISSUE THREAD

**Issue by victornoel** [rickbergfalk/sqlpad#375]
I tried to run sqlpad (installed 2.6.1 just now and ran with `sqlpad`) and when I connect to it with Chromium, I get the following error in the console and nothing is shown:
```
Refused to execute script from 'http://localhost:9000/static/js/main.266789c5.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
```

**Comment by rickbergfalk** [comment]
@victornoel I'm not able to reproduce this - is anything sitting in front of sqlpad that might be altering the response?

Could I get the version of node, chromium, and os you are using?

**Comment by victornoel** [comment]
@rickbergfalk there is something strange yes, I can't reproduce it on another computer I have and the docker version works well… maybe it is because of a common dependency with another package I globally installed and an old version is used? I don't know how files are served by sqlpad…

I installed with yarn global, it happens both with chromium and firefox.

node 8.11.2, latest linux (but it works on another computer) and chromium 67.0.3396.87.

**Comment by damienmarshall** [comment]
Hello!

I was deploying sqlpad in kubernetes behind a standard nginx ingress and I received this error. I was able to resolve the error by removing the basepath config option (which I'd set to "sqlpad"). However, with this option enabled, it returned the content type as "text/html" for javascript. I tried a few things with nginx to resolve, but couldn't as I'm not well versed in nginx!

Let me know if you need any further info!

Damien
