### ISSUE TITLE
how do specify username/password for cassandra connection

### ISSUE THREAD

**Issue by fish0185** [rickbergfalk/sqlpad#379]
hi, Thank you for the great tool! I am able to access local cassandra when it without credential. so how do i specify the credential values when I need.

**Comment by rickbergfalk** [comment]
Thanks @fish0185! 

Unfortunately SQLPad does not support connecting with credentials at this time. I'm not too familiar with cassandra myself, but it doesn't look like username/password options are provided in the cassandra Node.js driver https://github.com/datastax/nodejs-driver.

If they are and I missed it and someone would like to implement I'd be happy to take a pull request.

**Comment by fish0185** [comment]
@rickbergfalk  thank you for the information.

**Comment by gonace** [comment]
Hi @cx2c @fish0185
I've created a PR to add support for authentication (`username` and `password`) but have not yet figured out how to configure authentication in a `docker-compose.yml` file.

So if you can test this it would be appreciated, or if you have knowledge of how to set up authentication in a `docker-compose.yml` file that would be awesome.

Regards
