### ISSUE TITLE
Enhancement: Selectable Auto-refresh

### ISSUE THREAD

**Issue by deepvoice** [rickbergfalk/sqlpad#38]
I deal with real-time data. 
Being able to auto-refresh the query based on a selectable or inputted value would be helpful in visualizing the charts and/or data returned.

**Comment by rickbergfalk** [comment]
Would a solution like the one proposed in #37 work for this?

**Comment by deepvoice** [comment]
I was thinking auto page refresh and rerunning the query each time

**Comment by rickbergfalk** [comment]
Oh that makes sense. Would something like a textbox to run query every x seconds work? If on the SQL page, the result grid would refresh. Otherwise if on the chart tab the chart would be updated with the new query results.

**Comment by deepvoice** [comment]
Exactly! perfect

**Comment by rickbergfalk** [comment]
Finally published this. Sorry it took so long. I'm starting to think a proper consumption mode is needed (like a report view or dashboard view or something)
