### ISSUE TITLE
json result

### ISSUE THREAD

**Issue by WalterBDias** [rickbergfalk/sqlpad#381]
Hi, Is it possible to have a url with input parameters and returning a raw json?

![temp](https://user-images.githubusercontent.com/40076274/44727785-34688b00-aab1-11e8-861f-c3c55d9afbd7.png)

**Comment by rickbergfalk** [comment]
Hi @WalterBDias! Are you thinking this would trigger a file download action like the other two?

If so that's definitely possible and wouldn't be too difficult to add. It might be a while though as I haven't had much time for sqlpad lately

**Comment by gonace** [comment]
I've just opened a `Pull Request` to add support for a JSON-file #484 as this is something I'd like to have as well. 

I'm not sure if that was what you were aiming for @WalterBDias?
