### ISSUE TITLE
Can the debug log add a username or user id?

### ISSUE THREAD

**Issue by xrff** [rickbergfalk/sqlpad#384]
i just know little English,Please bear with me:)

The debug log is now like this:
{"connectionName":"test_db","startTime":"2018-09-19T03:42:12.129Z","stopTime":"2018-09-19T03:42:12.146Z","queryRunTime":17,"rowCount":51,"query":"select * from tag"}

Can  you add a user name or user id in this log? i need to record user actions, thanks a lot.

**Comment by xrff** [comment]
i love this web app so much,thank you for your creation!

**Comment by rickbergfalk** [comment]
Hi @xrff -- I'm assuming you mean the SQLPad user and not the db connection user right? 

I don't see an issue adding that

**Comment by rickbergfalk** [comment]
This has been added to 2.8.0

**Comment by xrff** [comment]
> Hi @xrff -- I'm assuming you mean the SQLPad user and not the db connection user right?
> 
> I don't see an issue adding that

yes! SQLPad user!
