### ISSUE TITLE
Result interface improvements

### ISSUE THREAD

**Issue by scottsimpson** [rickbergfalk/sqlpad#399]
I enjoy using this software to demonstrate database concepts. It might be worth considering improving some of the result display characteristics, though. 

I would recommend (1) turning off the bar chart lines in a numeric key fields (where a bar chart doesn't really make sense), and (2) removing the time component from the display of DATE fields (it shows 00:00:00 which, while I believe it's technically correct, is a little distracting in comparison with DATETIME or other types that do have an explicit time component).

Otherwise, I'm a big fan! Thanks for this!

**Comment by rickbergfalk** [comment]
Closing as these improvements were added to v3 :)
