### ISSUE TITLE
Ability to reset user password

### ISSUE THREAD

**Issue by rickbergfalk** [rickbergfalk/sqlpad#4]
Currently in SqlPad, if you forget your password you are out of luck. Eventually an admin/cli interface should be able to reset a user's password, allowing them to create a new one.

**Comment by dcelasun** [comment]
I'd like to tackle this one, but I'm not really sure how to go about it. Ideally, the app would send a password reset email, but that sounds somewhat out of scope for SqlPad.

So maybe an admin could set a temporary password, which would not only disable the current password, but also toggle a flag that forces the user to set their own password on first login. As SqlPad is for private networks, the admin could simply tell the temporary password to the user.

Alternatively, if you'd like to go with the email option, we could add a minimal SMTP module that can be configured via the new configuration interface. This would allow SqlPad to send emails and it wouldn't touch any other part of the codebase.

Personally I'm fine with either option. What do you think?

**Comment by rickbergfalk** [comment]
Initially I was thinking something like the temporary password you are proposing, or a secret url that gets generated for an admin to manually email to the user so they can set a new password. I think it'd be nice if teams could run SqlPad without needing access to an SMTP server.

That said, I think the ability to add SMTP support would be awesome and very professional. I've never done any email stuff with node yet so I don't know what's involved. 

If its something you want to tackle by all means go for it :)

**Comment by dcelasun** [comment]
All right then, I'll tackle the SMTP thing when I can :)

**Comment by deepvoice** [comment]
node-mailer?

**Comment by rickbergfalk** [comment]
in v2!
