### ISSUE TITLE
Add SSL for MySQL

### ISSUE THREAD

**Issue by sebastiendan** [rickbergfalk/sqlpad#404]
Hi,

Would it be possible to add `ssl` option for MySQL?

Thanks!

**Comment by sebastiendan** [comment]
I get the following error when trying to connect to my MySQL DB on Azure
> Error: UNKNOWN_CODE_PLEASE_REPORT: SSL connection is required. Please specify SSL options and retry.

**Comment by ltning** [comment]
This is pretty critical as it completely prevents use of this in anything but the most basic of dev envs..

**Comment by gonace** [comment]
@sebastiendan @ltning Hi, I've added support for SSL under MySQL/MariaDB and there is a pending pull request (#489) for this feature.

However, we'd like your support testing this feature out, if you have time to test this please do so. 

Best Regards
