### ISSUE TITLE
Automatic logout after some period

### ISSUE THREAD

**Issue by aroup** [rickbergfalk/sqlpad#408]
We have deployed a sqlpad v2.8.0 image docker version in k8s. But the problem is whenever some time passes, say one hour, the session expires and users are logged out whenever they try to do any action like running query and saving. Is there any configuration that increases the session time?

**Comment by rickbergfalk** [comment]
Today this is set to 1 hour, but should be extended when interacting with the API. 

I see no problem making it configurable. I can make this change with the upcoming 3 release sometime next couple months

**Comment by rickbergfalk** [comment]
I've added a configuration variable for session time, available in latest or 3.0.0-beta.2 docker image. 

Something I thought of - the session should be getting extended each API request, but I'm wondering if that is not happening? Also potentially relevant -- the session store today is using the file system since there isn't an external db in use. Not sure if that is also causing issues here?

**Comment by CrashLaker** [comment]
Often times I'm losing my query due to losing the session. Is it possible to increase or set it to a very long time?

**Comment by rickbergfalk** [comment]
Yes with the 3.0.0 release you can set to as long as you'd like. V3 will also keep unsaved edits in saved in the browser local storage and will prompt to restore next visit to that query

**Comment by CrashLaker** [comment]
I can't seem to find the setting to chance that though I'm using version 3.0.0-beta.1.
Is it the "Require Login for Table/Chart Links" option?

**Comment by rickbergfalk** [comment]
Oh sorry - it was introduced with 3.0.0-beta.2 to be specific. I've also added a configuration doc of sorts detailing all the config keys that can be set https://github.com/rickbergfalk/sqlpad/blob/master/CONFIGURATION.md

The env var is `SQLPAD_SESSION_MINUTES` and the ini/json config key is `sessionMinutes`

**Comment by CrashLaker** [comment]
Can I just add:
`ENV SQLPAD_SESSION_MINUTES 999999`
inside the Dockerfile?

Can't seem to find `$HOME/.sqlpadrc`.
I'm my case `$HOME = /root` inside the container.

**Comment by rickbergfalk** [comment]
Yes setting the environment variable `SQLPLAD_SESSION_MINUTES` should hopefully accomplish what you need. 

I just realized my release notes have conflicting information about `$HOME/.sqlpadrc` being the default. I kept changing my mind on that and ultimately decided that there is no default location.

In 3 beta.2 you can create your own file, name it anything, put it anywhere, use JSON or INI, and then tell SQLPad where it is at using cli flag `--config=path/to/file` or env var `SQLPAD_CONFIG=path/to/file`

If you are using docker, I'd recommend going the environment variable route personally
