### ISSUE TITLE
"Failed to fetch user profile" when using Google Sign-In API for Oauth2

### ISSUE THREAD

**Issue by akatch** [rickbergfalk/sqlpad#409]
In preparation for the deprecation of the Google+ API, I tried swapping in a set of known working GOOGLE_CLIENT_* credentials we currently use elsewhere in our environment. Unfortunately, upon restarting SQLpad and attempting to sign in, I get `Internal server error` displayed in the browser and this output in the logs:

```
Mar  8 01:34:40 web03-util-uw2 sqlpad[10697]: InternalOAuthError: failed to fetch user profile
Mar  8 01:34:40 web03-util-uw2 sqlpad[10697]: at /usr/local/nodejs/v6.11.1/lib/node_modules/sqlpad/node_modules/passport-google-oauth2/lib/oauth2.js:92:28                                                         
Mar  8 01:34:40 web03-util-uw2 sqlpad[10697]: at passBackControl (/usr/local/nodejs/v6.11.1/lib/node_modules/sqlpad/node_modules/oauth/lib/oauth2.js:132:9)                                                        
Mar  8 01:34:40 web03-util-uw2 sqlpad[10697]: at IncomingMessage.<anonymous> (/usr/local/nodejs/v6.11.1/lib/node_modules/sqlpad/node_modules/oauth/lib/oauth2.js:157:7)                                            
Mar  8 01:34:40 web03-util-uw2 sqlpad[10697]: at emitNone (events.js:91:20)
Mar  8 01:34:40 web03-util-uw2 sqlpad[10697]: at IncomingMessage.emit (events.js:185:7)
Mar  8 01:34:40 web03-util-uw2 sqlpad[10697]: at endReadableNT (_stream_readable.js:974:12)
Mar  8 01:34:40 web03-util-uw2 sqlpad[10697]: at _combinedTickCallback (internal/process/next_tick.js:80:11)                                                                                                       
Mar  8 01:34:40 web03-util-uw2 sqlpad[10697]: at process._tickCallback (internal/process/next_tick.js:104:9)  
```

If I put the G+ credentials back, everything works as expected, but I would like to stop using these as soon as possible. Please let me know if I can provide further troubleshooting data.

SQLpad version is 2.8.0

**Comment by rickbergfalk** [comment]
I'm going to take a shot at reproducing this and see if I can get something published under 2.8.1. It looks like there is a way to provide an alternate authentication user info endpoint to use.

**Comment by akatch** [comment]
You rock, let me know if there's anything I can do to help test.

On March 8, 2019 3:33:15 AM UTC, Rick Bergfalk <notifications@github.com> wrote:
>I'm going to take a shot at reproducing this and see if I can get
>something published under 2.8.1. It looks like there is a way to
>provide an alternate authentication user info endpoint to use. 
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/rickbergfalk/sqlpad/issues/409#issuecomment-470792605

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by rickbergfalk** [comment]
@akatch I think I maybe got it fixed, but not entirely sure. I pointed the oauth to a new endpoint and updated the implementation to handle the different profile shape received back in #410 

2.8.1 has been published to npm and dockerhub. If you build from source you'll want to grab the v2 branch of this repo.

Let me know how it goes!

**Comment by akatch** [comment]
IT WORKS! Thank you so much for the quick fix!

**Comment by rickbergfalk** [comment]
Great to hear and you're welcome!
