### ISSUE TITLE
Cannot npm install

### ISSUE THREAD

**Issue by chrisabrams** [rickbergfalk/sqlpad#417]
Running `npm install sqlpad -g` results in the following error. I am running Node 11.10 on OS X.

```
In file included from ../src/odbc.cpp:25:
../src/odbc.h:30:10: fatal error: 'sql.h' file not found
#include <sql.h>
         ^~~~~~~
1 error generated.
make: *** [Release/obj.target/odbc_bindings/src/odbc.o] Error 1
```

**Comment by rickbergfalk** [comment]
Hi @chrisabrams. That should be an optional dependency...

Do you recall if there was a message at the end about it being installed successfully afterwards? Are you able to run sqlpad from the command line despite the error?

**Comment by zyp001a** [comment]
try yum install unixODBC-devel or apt-get install unixodbc-dev

**Comment by rickbergfalk** [comment]
going to close this out, can reopen if necessary but I'm pretty sure the sqlpad build should be functional just without the unixodbc support.

I wish there was a way to suppress this message as it seems to be tripping a lot of people up...
