### ISSUE TITLE
cassandra connection error

### ISSUE THREAD

**Issue by chaiyuan2046** [rickbergfalk/sqlpad#433]
sqlpad is great for sql on web.

Error log:" Server responded not ok".
while using cassandra connector,query disconnect after few minites(less then 5 minutes),any ideas to me ?

**Comment by chaiyuan2046** [comment]
![image](https://user-images.githubusercontent.com/16013012/58627517-0fd46480-830a-11e9-8a91-fb2589414dde.png)
![image](https://user-images.githubusercontent.com/16013012/58627549-22e73480-830a-11e9-9442-0cf8d9c2ae77.png)

**Comment by rickbergfalk** [comment]
Thanks @chaiyuan2046 - Can you check and see if the SQLPad server crashing? I haven't used the cassandra driver much... It may not be handling errors gracefully.

**Comment by rickbergfalk** [comment]
Going to close due to inactivity - let me know if this needs to be reopened
