### ISSUE TITLE
Node-gyp Error

### ISSUE THREAD

**Issue by sonuame** [rickbergfalk/sqlpad#441]
Upon building up the new source in Ubuntu 18.xx, its giving me the below error

gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@8.10.0 | linux | x64
gyp ERR! configure error
gyp ERR! stack Error: EACCES: permission denied, mkdir '/home/sonuame/sqlpad/server/node_modules/odbc/build'
gyp ERR! System Linux 4.18.0-1019-azure
gyp ERR! command "/usr/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build"
gyp ERR! cwd /home/sonuame/sqlpad/server/node_modules/odbc
gyp ERR! node -v v8.10.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
added 503 packages in 15.788s

I checked the permissions, tried running with sudo , Installed odbc driver separately but nothing is working for me

**Comment by rickbergfalk** [comment]
Hi @sonuame - I believe the build should still be valid. That error is for the native dependencies, which are flagged as optional. You should be able to run SQLPad but without the unix odbc support.

Let me know if this is not the case and you're still having trouble.
