### ISSUE TITLE
feature req - private connections between users

### ISSUE THREAD

**Issue by tooptoop4** [rickbergfalk/sqlpad#444]
docs have:
"SQLPad is meant to be run on an internal network for a single team. All connections added to the app can be used by all individuals with access to the SQLPad server."

any plans to allow private db connection details so they are not shared between users?

**Comment by rickbergfalk** [comment]
Hello @tooptoop4 

There are no plans to add a private or user-based connections unfortunately.

Today there are 2 roles available to users. Admins can see/edit/add connections, and editors can use them for querying, but not edit or modify them.
