### ISSUE TITLE
Google OAuth shows "Not Found" page

### ISSUE THREAD

**Issue by deemoowoor** [rickbergfalk/sqlpad#449]
I'm trying to set up Google OAuth in development. Following the instructions in this document, though: 

https://github.com/rickbergfalk/sqlpad/blob/master/docs/installation-and-administration/index.html 

gives me a "Not found" page on http://localhost:3000/sqlpad/auth/google after I click on "Log in with Google" button. I can see, that this is the default behavior for the React client, when you navigate to a URL not listed in the Routes.js. 

I'm expecting some redirect from the server (judging by the code in server/routes/oauth.js) -- to a Google's login page. 

Oddly enough, when I'm trying to access the same `/sqlpad/auth/google` page through Postman, it does return the page I expect (Google's login). 

I'm trying to implement SAML support for this SQLPad (to allow authentication with ADFS or similar Single Sign On-type authentication services) to allow using SQLPad for a kind of restricted SQL console. My first attempt at stabbing that (as I -- somewhat naively -- assumed Google auth works) game me the same result -- a Not Found page. 

I'm willing to share the SAML support code -- it's fairly simple and I think it would benefit the community a lot -- if I can make this thing work somehow. 

Note: running a version from 11 days ago, development environment set up according to README:

https://github.com/deemoowoor/sqlpad/commit/391cf49f4d8ec0ce3090af384fdeee283931c377

**Comment by deemoowoor** [comment]
OK, I managed to make Google OAuth work by using the 'production'-compiled frontend on http://localhost:3010. 

So React GUI works differently in development? Is there a reason for that?

**Comment by rickbergfalk** [comment]
Hi @deemoowoor 

The React dev mode is served with a separate web server and isn't integrated with the web server serving the production compiled front-end. 

The react dev server is webpack/create-react-app and will proxy any request it doesn't understand to the backend API. 

It has been a while since I've looked at the alternate OAuth logins, but I suspect it isn't working either because of an issue with proxying and/or port difference?

Would gladly accept the SAML auth if it is something you'd like to contribute back :)

**Comment by deemoowoor** [comment]
Thank you for clarifying!

**Comment by deemoowoor** [comment]
Regarding OAuth2, I can see, that http://localhost:3010/sqlpad/auth/google correctly redirects to the Google's Auth2 page which in turn redirects to the callback URL http://localhost:3010/sqlpad/auth/google/callback with seemingly correct parameters, which then redirects to /sqlpad/signin, which according to oauth.js signifies a failure. 

After logging in as an admin user and "whitelisting" my test user account, I could successfully log in using Google OAuth2, actually. So, apparently, SQLPad requires users to be essentially registered manually by an admin. I think it would be helpful, if users could be auto-registered, when using an approved authentication setup (this would, of course, be useful only on internal networks).

**Comment by deemoowoor** [comment]
I've created a pull request for the SAML integration. Regarding the bug, I believe it could be closed. Some of the details revealed here could be added to the documentation, though.

**Comment by rickbergfalk** [comment]
Updated the documentation a bit in readme/developer guide and restructured things a bit. Hopefully it is a bit more clear. Please let me know if you have any additional questions!
