### ISSUE TITLE
Issue: old and insecure pre-4.1 auth mechanism

### ISSUE THREAD

**Issue by deepvoice** [rickbergfalk/sqlpad#45]
Trying to connect to an older mysql database

Same issue as: (resolved)
https://github.com/sequelize/sequelize/issues/1847

**Comment by rickbergfalk** [comment]
Sorry for the delay in getting to this @deepvoice. I've added this to the next deployment of sqlpad... which will be published either late tonight or tomorrow.

**Comment by rickbergfalk** [comment]
Sorry @deepvoice. Just got around to publishing this. check out 1.10.0

**Comment by deepvoice** [comment]
Thanks Rick!
Is auto-refresh in 1.10.0 too? ;)

Damon

**Comment by rickbergfalk** [comment]
It isn't... but I think I have it working locally so it is close :)

Part of me is trying to figure out how to work it into the UI. As SqlPad gets more usage, it seems that the chart/table viewing experience is just as important as the editing/creating experience. 

I may just publish it and get feedback on what people think...

**Comment by deepvoice** [comment]
It is... and here is why...

The bosses don't care about the raw data. They want to see pretty pictures.
Who pays us? The bosses
... and as the world turns so do the days of our lives...
