### ISSUE TITLE
docker-validation mssql requires large memory size

### ISSUE THREAD

**Issue by CrashLaker** [rickbergfalk/sqlpad#456]
Would be good to have a 2GB warning as a pre-req to build this.

```
$ docker logs -f mssql_mssql_1
sqlservr: This program requires a machine with at least 2000 megabytes of memory.
```
We could instead:
`docker run -dit --name mysql_sqlpad -e MYSQL_ROOT_PASSWORD=password -p 3306:3306 mysql:5`
then
`docker exec -it mysql_sqlpad mysql -u root -ppassword -e "create database sqlpad_test;"`

or setup the compose as in: https://hub.docker.com/_/mysql?tab=description

**Comment by rickbergfalk** [comment]
The README in the docker-validation mentions checking the minimum requirements before you run. The sql server team has been bringing that requirement down quite a bit. At one point it needed 4 GB. 

I was going to eventually add more examples to that directory showing different databases and quick ways to get started. 

More than welcome to add a directory with a different example or add to readme with a PR if you'd like.

**Comment by CrashLaker** [comment]
Sorry I probably missed that in the README.

Ok I'll try to PR some examples as well as some dummy SQL table insert

thank you @rickbergfalk

**Comment by rickbergfalk** [comment]
No worries - I remember why I started with mssql specifically now. It requires a few extra steps to get going, and I was using the docker container for testing the mssql integration.

I'm all for more docker examples with different databases :)
