### ISSUE TITLE
Connections not saving 3.0.2

### ISSUE THREAD

**Issue by Shadow00Caster** [rickbergfalk/sqlpad#464]
Version 3.0.2 on Docker

Fresh container, basic config in INI format with whitelisted e-mail for admin, when attempting to create a new connection for sql server, it does not save.  The connections.db gets created but is 0KB.

**Comment by rickbergfalk** [comment]
I'm able to save connections using this docker compose file https://github.com/rickbergfalk/sqlpad/blob/master/docker-examples/postgres-docker-compose/docker-compose.yml.

Are you changing the dbPath in the INI by chance or is there a permissions issue?

**Comment by Shadow00Caster** [comment]
No I'm using default, I mapped a local "volume" to /var/lib/sqlpad, just using builtin, no external db.  I did it with Portainer, I might try blowing it out and testing again, will update when I try and provide more info.

**Comment by rickbergfalk** [comment]
Going to close this -- if you reproduce feel free to comment and this can be reopened.
