### ISSUE TITLE
CONFIGURATION.md link on Docker Hub is incorrect

### ISSUE THREAD

**Issue by Shadow00Caster** [rickbergfalk/sqlpad#465]
The link to the CONFIGURATION.md file on hub.docker.com is incorrect.

**Comment by rickbergfalk** [comment]
I realized that... unfortunately docker hub messes with URLs that would otherwise work on GitHub. I think I'll likely fold all markdown into one giant README.md?

**Comment by Shadow00Caster** [comment]
Ah gotcha, or just say config avail on github :p.

**Comment by rickbergfalk** [comment]
The configuration documentation is now inlined in README so it'll show on Docker Hub.
