### ISSUE TITLE
MSSQL Login Error (Windows auth error)

### ISSUE THREAD

**Issue by Shadow00Caster** [rickbergfalk/sqlpad#475]
Using latest (3.1.0) running on Docker, everything was working fine until suddenly I am getting `ConnectionError: Login failed. The login is from an untrusted domain and cannot be used with Windows authentication.` on all my MSSQL connections (this is also the error being logged in SQL Server logs).  This is not Azure, it's a local MSSQL instance, I have tried with IP and hostname, ticked/un-ticked the Encrypt option, tried specifying a domain, all results in the same message.

This confuses me as it's not doing Windows authentication, it's using sql server native auth (we do have mixed mode enabled for applications like sqlpad where we cannot do Windows/Kerberos auth).

**Comment by rickbergfalk** [comment]
Are you using the `latest` or the `3.1.0` tag? If `latest` can you try `3.1.0` and pulling?

`latest` is updated after every commit in the repo. Between `3.1.0` and `latest` the `mssql` driver was updated, which could play a role in what you are seeing.

**Comment by Shadow00Caster** [comment]
That did it, thanks @rickbergfalk

**Comment by rickbergfalk** [comment]
Sure no problem! Though I'm thinking this could be a valid bug?

I tried tweaking various settings in a local docker test setup and was not able to reproduce the error message. 

If you switch back to `latest` (or `3.2.0` when it is published) and the error still persists please let me know.

**Comment by rickbergfalk** [comment]
Published SQLPad `3.1.1` to docker hub that has all the dependency updates if you want to give it a shot again at some point.

**Comment by Shadow00Caster** [comment]
Tested this on latest tag just now using existing working configs/db, same issue.  Production is running tag 3.1.0 without issue.

**Comment by rickbergfalk** [comment]
I'm unable to reproduce this one... not sure what the config settings are or the setup of the SQL Server instance. 

If anyone out there is feeling adventurous in trying to figure this out the connection implementation along with tests are at https://github.com/rickbergfalk/sqlpad/tree/master/server/drivers/sqlserver.

`index.js` is the actual implementation.
`test.js` is the nodejs test code
`docker-compose.yml` defines the docker container
`test.sh` brings up docker container and runs the `test.js` file

**Comment by rickbergfalk** [comment]
Is it possibly related to https://github.com/tediousjs/tedious/issues/836?

**Comment by Shadow00Caster** [comment]
@rickbergfalk So I think I figured this out.  I was able to get this to work with latest by deleting the existing DB connection and re-creating (with same name) and I no longer get the error.  It may have had something to do with the way the connection was previously stored, this was moved from an existing installation under 2.x running on a Windows machine previously using the old pip package.

In any case, I don't think this is an issue FRESH but rather an issue through various iterations of migrating/upgrading.

**Comment by rickbergfalk** [comment]
I'm wondering if this had something to do with the encryption of database usernames and passwords? If SQLPad config or defaults changed it may have produced some invalid results. Looking at the decipher code the behavior is to capture the decipher error and instead return empty string.

Instead of logging the error and returning empty string I'm thinking it should throw to make the breakage more apparent.

**Comment by rickbergfalk** [comment]
I'm removing the empty string behavior in #501. This should make the underlying error more apparent if it occurs again.
