### ISSUE TITLE
Schema Sidebar in Google Chrome not visible

### ISSUE THREAD

**Issue by alphawolf1988** [rickbergfalk/sqlpad#478]
If i toggle the schema sidebar, the scrollable schema content has only a height of 14px in Google Chrome. So it's not really visible / usable. While using Opera, everything is displayed correctly.

**Comment by rickbergfalk** [comment]
Hi @alphawolf1988 -- I'm unable to reproduce this one. What OS and version of Chrome are you using?

**Comment by alphawolf1988** [comment]
Hi @rickbergfalk i'm using Ubuntu 18 and Chrome 70.0.3538.77 (Offizieller Build) (64-Bit)

**Comment by bruth** [comment]
I observe this in Safari (v13.0.3) as well. See the text of the first line is cut-off.
<img width="374" alt="Screen Shot 2019-12-30 at 2 53 05 PM" src="https://user-images.githubusercontent.com/515142/71598305-54c8af80-2b14-11ea-9c98-1b0827758bcf.png">

Disabling the `height: 100%;` on `#root > div > div:nth-child(2) > div > div.Pane.vertical.Pane1 > div > div:nth-child(3) > div` made the list reappear..

**Comment by rickbergfalk** [comment]
Thanks @bruth for additional info. I'm able to reproduce and confirm in Safari.

**Comment by bruth** [comment]
Thank you!
