### ISSUE TITLE
Enhancement: allow to mount under any directory

### ISSUE THREAD

**Issue by vadz** [rickbergfalk/sqlpad#48]
Sorry if this is already possible, but I couldn't find any way to use SqlPad behind Apache `ProxyPass`: the problem is that all the URIs in the returned contents uses absolute paths, so if you proxy `https://www.example.com/sqlpad` to SqlPad, the very first redirect would go to the (non existent) `https://www.example.com/signup` and not the expected `https://www.example.com/sqlpad/signup`.

AFAICS Express.js does support this, but I had never used it before, so I'm not sure how exactly to do this.

**Comment by rickbergfalk** [comment]
Hi @vadz. I don't think this is possible with express.js, but I'm not too familiar with this sort of stuff. Are you able to host sqlpad behind a subdomain at all? It was pretty easy to put behind a subdomain with nginx, I'm not sure if there's something similar for apache? 

I'll leave this issue open for a bit in case anyone has any additional info on this...

**Comment by vadz** [comment]
Well, I've seen mentions of the [mount path](http://expressjs.com/api.html#app.mountpath) in the documentation, so this is why I thought it was supported, but I could be wrong, of course, as I said I know absolutely nothing about Express.js.

Using subdomain would work, of course, but has some drawbacks and is also inconsistent with all the other web apps already installed on this server, so I'd prefer to not do it like this if possible.

**Comment by rickbergfalk** [comment]
It looks like the mount path is for mounting an express app inside another express app, but it might be able to help in this case though... I'll have to do more research. Maybe we could leverage the mount path inside express, and then make sure the mount path is considered everywhere else? Places like html templates, ajax calls, javascript redirects, etc.

**Comment by willwest** [comment]
@rickbergfalk @vadz I'm currently working on adding this functionality using the solution noted here: http://stackoverflow.com/a/5994334/1304437

Right now I'm planning on adding a baseUrl config value. This will be used by the views and routes to properly redirect requests and configure absolute paths with the correct base path.

I'm very new to express.js, so please let me know if there is a better approach!

**Comment by rickbergfalk** [comment]
Thanks for the assistance @willwest! I think that looks like a great way to go.

Let me know if you run into any issues or have any questions and I'll try to assist where I can :)

**Comment by rickbergfalk** [comment]
Sorry @vadz and @willwest! Meant to publish earlier but just now getting around to it.  This is in version 1.16.0 published to npm.
