### ISSUE TITLE
In README.md, link to CONFIGURATION.md is broken

### ISSUE THREAD

**Issue by toolness** [rickbergfalk/sqlpad#482]
Hello!  I just started using sqlpad and noticed that the "Docker Image" section near the beginning of the README has a link to `CONFIGURATION.md` that doesn't seem to exist anymore:

> For configuration exposed via environment variables reference [CONFIGURATION.md](https://github.com/rickbergfalk/sqlpad/blob/master/CONFIGURATION.md).

As far as I can tell, this file seems to have been integrated into the README itself, in its [Config variables](https://github.com/rickbergfalk/sqlpad/blob/master/README.md#config-variables) section?

**Comment by rickbergfalk** [comment]
Yep the documentation was merged into README. I've updated docs. Thanks for catching this
