### ISSUE TITLE
Timeout Setting Not Working

### ISSUE THREAD

**Issue by Shadow00Caster** [rickbergfalk/sqlpad#483]
I am running latest via docker (3.4.0 at time of writing) and have added
`; HTTP server timeout as number of seconds. Extend as necessary for long running queries timeoutSeconds=480`
into my sqlpad.ini which is pointed to via env var `SQLPAD_CONFIG /var/lib/sqlpad/sqlpad.ini`, however I still experience MSSQL queries that take longer than 2 minutes to timeout exactly at the 2 minute mark. I tested this with a query that completes on average in just over 2 minutes but never more than 3 minutes.

**Comment by rickbergfalk** [comment]
Testing locally I was able to confirm that the node.js server will wait longer than 2 minutes if set to that. We may need to add some additional logging to confirm what is actually timing out.

**Comment by rickbergfalk** [comment]
@Shadow00Caster could you confirm this is still an issue with latest version?

Additional logging has been added with app and web log levels if that is helpful...

**Comment by rickbergfalk** [comment]
Thanks for confirming. I think I'll see if I can set up a SQL Server instance and set the timing to 600 as well and see what happens...

**Comment by kpioneer123** [comment]
docker  -e SQLPAD_TIMEOUT_SECONDS=1000 Setting Not Working

**Comment by rickbergfalk** [comment]
@kpioneer123 can I get the database as well as SQLPad version you are using? 

I've confirmed that the timeout seconds _are_ working at the node.js HTTP server level, but that doesn't necessarily handle any timeouts that might be in play at the driver side of things, or if you have your SQLPad instance behind an HTTP proxy/load balancer. 

The `latest` tag in docker uses a new API that should hopefully remove the need for setting timeout seconds, as it no longer relies on long running HTTP connections.

**Comment by rickbergfalk** [comment]
I think this should be addressed in `5.0.0` now tagged as stable. The POST request used to run a query does not wait for the query to finish before the response is sent back to the client. 

If this is still an issue in v5, let me know and we can reopen again :)
