### ISSUE TITLE
Install instructions not working

### ISSUE THREAD

**Issue by ltning** [rickbergfalk/sqlpad#485]
Hi,

I've built sqlpad as instructed in README.md, but the global install step fails:
```
[root@foo.bar] /home/sqlpad/GH/sqlpad/server (master)# node install -g
internal/modules/cjs/loader.js:895
    throw err;
    ^

Error: Cannot find module '/usr/home/sqlpad/GH/sqlpad/server/install'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:892:15)
    at Function.Module._load (internal/modules/cjs/loader.js:785:27)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1143:12)
    at internal/main/run_main_module.js:16:11 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

OS: FreeBSD 12.1
Node: 13.1.0

**Comment by rickbergfalk** [comment]
I'm seeing some strange issues too, though I get a different error. 

Did you have SQLPad previously installed globally via npm by chance?

Could you try running the following:
```sh
npm uninstall -g sqlpad
cd /home/sqlpad/GH/sqlpad/server
npm install -g
```

**Comment by ltning** [comment]
I got i tworking, using npm install instead of node install (and in the right directory); the instructions in README.md are wrong though :)

See my other ticket (#486), no idea what I'm doing wrong if anything..

**Comment by rickbergfalk** [comment]
Sorry - didn't even realize the docs or your paste of the error. will get that updated
