### ISSUE TITLE
Make build script more portable

### ISSUE THREAD

**Issue by corneliusludmann** [rickbergfalk/sqlpad#495]
To fix the issue with the missing `await` when using the admin password config, I used the [Gitpod Cloud IDE](https://gitpod.io/). I noticed that the build script does not run in Gitpod.

This is because `sh` is given as interpreter in the shebang line und double square brackets `[[ ... ]]` are used. In a POSIX `sh` double square brackets are not available. Most modern Linux desktop distribution does not provide a real `sh` but point to `bash` instead. Therefore using this script on a desktop works even though. Gitpod uses a docker container that has `sh` installed. Therefore, the script does not work correctly.

I would suggest to use `bash` as interpreter to make the build script more portable.

**By the way:** If you would like to provide other developers with an easier entry you could find a configuration for the Gitpod Cloud IDE with a running SQLPad in my [SQLPad Gitpod branch](https://github.com/corneliusludmann/sqlpad/tree/gitpod). Gitpod is free for up to 100 hours per month for open source projects. You can add it to your repository, if you like. _[Full disclosure: I work for TypeFox who makes Gitpod.]_

**Comment by gonace** [comment]
Hi @corneliusludmann feel free to create a PR for the sh, bash change :)
