### ISSUE TITLE
dbpath not provided in config

### ISSUE THREAD

**Issue by Ergovite** [rickbergfalk/sqlpad#497]
Hi, I installed SQLPAD and when i try to run it, i get the error "dbpath not provided in config"

![image](https://user-images.githubusercontent.com/57803438/71027145-a9156d80-20d8-11ea-923b-0b7782fa4c25.png)

Can someone help in resolving this issue.

Thanks in advance!

**Comment by rickbergfalk** [comment]
Hi @Ergovite -- the path to configuration is no longer included by default. You could try 

```sh
sqlpad --dbPath "C:\Users\ergovite\sqlpad\db"
```

Alternatively you can create a config.json or config.ini file, and specify a path, port, etc and run 

```sh
sqlpad --config "/path/to/config.file"
```

**Comment by Ergovite** [comment]
Hi Rick, Thanks for your prompt response.

I tried the first option and i'm getting the "Welcome to SQLPad!", and i'm able to login to the local host. 

Few things i'm seeing at the command prompt are highlighted, if they are critical please let me your suggestions. Thanks again

![image](https://user-images.githubusercontent.com/57803438/71053105-780a5c80-211b-11ea-86d0-c1de58dc7ee8.png)

**Comment by rickbergfalk** [comment]
For `optional driver ../drivers/unixodbc` message, that can be ignored. SQLPad will function without it. If unix odbc support is needed you'll need to follow the setup instructions to compile native dependencies for node projects using node-gyp.

For the EPERM issue, SQLPad uses local filesystem for its database and session storage. It seems that the account running SQLPad does not have permissions to write to the directory used for storage.

**Comment by rickbergfalk** [comment]
@Ergovite going to close this issue - let me know if you have any further questions
