### ISSUE TITLE
Firefox add user form performs a GET

### ISSUE THREAD

**Issue by bruth** [rickbergfalk/sqlpad#503]
I can add users in Safari (have not tested Chrome), but in Firefox I am noticing a couple things:

- Validation on the fields is not enforced (e.g. required role)
- Clicking the "add user" button results in a GET with the values as parameters

<img width="771" alt="Screen Shot 2019-12-30 at 3 03 19 PM" src="https://user-images.githubusercontent.com/515142/71598613-87bf7300-2b15-11ea-947b-1605524aa74a.png">

**Comment by rickbergfalk** [comment]
Thanks @bruth I'll take a look at this

**Comment by bruth** [comment]
Thank you!
