### ISSUE TITLE
Readme addition: How to run live server from a git checkout

### ISSUE THREAD

**Issue by nbrustein** [rickbergfalk/sqlpad#52]
I'm working on a feature in sqlpad that I want to submit as a PR.  I think I have it working on my local machine, but I want to run my branch in place of my company's live sqlpad instance so I can test it against real data.

I can't figure out how to get this working, though.  I've tried checking out my branch on our servers and running

   npm start --dir /path/to/pre_existing/data/dir --port 80 --passphrase MYPASSPHRASE

but I get

    Error: ENOENT, open ' /path/to/pre_existing/data/dir/package.json'

Could you please add to the README a description of how to get this working?

Thanks a lot for this project.

**Comment by rickbergfalk** [comment]
Hi @nbrustein! You're welcome! Always nice to hear SqlPad is getting some use at other companies.

I think you'll need to run the server.js file directly in this case, with either node or nodemon (depending if you want to to auto-restart on changes). It looks like npm must do something with the --dir flag?

So you'd do

```
node server.js --dir /path/to/pre_existing/data/dir --port 80 -- passphrase MYPASSPHRASE
```

I'll be on the lookout for that pull request :)
