### ISSUE TITLE
testConnection doesn't indicate failures

### ISSUE THREAD

**Issue by murphyke** [rickbergfalk/sqlpad#526]
E.g. if you tweak the port to be invalid and click the Test button, the result from the user's perspective is exactly the same as if the test succeeded. The connection test *is* made behind the scenes, but the error gets swallowed.

**Comment by rickbergfalk** [comment]
Thanks for the report @murphyke. Can I get the driver you're seeing this behavior with (postgres, mysql, etc)?

**Comment by murphyke** [comment]
@rickbergfalk I saw it with postgres, using 7c6c28e (current `master` some time yesterday). (Sorry, should have specified).

I initially saw it with the BigQuery driver I am finishing up (using an abandoned fork from hongkongkiwi).

BTW, the BigQuery driver looks to be about ready to go. I can include instructions for testing it.

**Comment by rickbergfalk** [comment]
No worries -- I was testing but wasn't able to reproduce. I was putting fake data into postgres host and trying it out. I'll have to do more digging.

Great to hear about BigQuery! will keep an eye out for PR

**Comment by rickbergfalk** [comment]
@murphyke are you still seeing this at all? I looked into this a bit more and have been unable to reproduce with postgres

**Comment by murphyke** [comment]
@rickbergfalk I will check this afternoon.

**Comment by murphyke** [comment]
@rickbergfalk  This is a really minor issue, but I am still seeing it in the new `master` branch.  I'm running Postgres.app on Mac (PG 11), and when I configure the driver for port 5432 (the correct, default one), everything is fine.

Clicking the Test button in the connection management view correctly goes to the Connections view.

I can go to the SQL editor and make queries, as expected.

FWIW, the SQLPad log (for the good test) shows:

```
{"level":30,"time":"2020-04-06T20:49:42.809Z","pid":93746,"hostname":"c85b76a52f72.chop.edu","name":"sqlpad-web","req":{"id":62,"method":"PUT","url":"/api/connections/wC6qmHplSZusv38g"},"res":{"statusCode":200},"responseTime":7,"msg":"request completed","v":1}
{"level":30,"time":"2020-04-06T20:49:42.811Z","pid":93746,"hostname":"c85b76a52f72.chop.edu","name":"sqlpad-web","req":{"id":61,"method":"POST","url":"/api/test-connection"},"res":{"statusCode":200},"responseTime":15,"msg":"request completed","v":1}
```

Now I edit the connection, change the port to 54321 and click Test. Again the "Edit connection" view is closed and I'm returned to the "Connections" view.

There is no visual sign of an error - this is unexpected.

When I go to the SQL editor and try a query (or reload the schema), I get the giant magenta "ECONNREFUSED" error (as expected, since the port is bad).

I see the following in the SQLPad log for the bad test:

```
{"level":50,"time":"2020-04-06T20:41:06.761Z","pid":93746,"hostname":"c85b76a52f72.chop.edu","name":"sqlpad-app","errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":54321,"msg":"connect ECONNREFUSED 127.0.0.1:54321","stack":"Error: connect ECONNREFUSED 127.0.0.1:54321\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1137:16)","type":"Error","v":1}
{"level":30,"time":"2020-04-06T20:41:06.765Z","pid":93746,"hostname":"c85b76a52f72.chop.edu","name":"sqlpad-web","req":{"id":57,"method":"POST","url":"/api/test-connection"},"res":{"statusCode":200},"responseTime":9,"msg":"request completed","v":1}
{"level":30,"time":"2020-04-06T20:41:06.770Z","pid":93746,"hostname":"c85b76a52f72.chop.edu","name":"sqlpad-web","req":{"id":58,"method":"PUT","url":"/api/connections/wC6qmHplSZusv38g"},"res":{"statusCode":200},"responseTime":8,"msg":"request completed","v":1}
```

Does all that make sense?

**Comment by rickbergfalk** [comment]
Thanks for the repro! That should give me enough to work off of. I was testing by changing host and was seeing errors so I didn't go much further than that.

**Comment by rickbergfalk** [comment]
Ah good point! I believe it does.
