### ISSUE TITLE
include materialized views in table list

### ISSUE THREAD

**Issue by nbrustein** [rickbergfalk/sqlpad#53]
I'm using postgres with materialized views.  It would be nice if they showed up in the list of tables on the left of the query pages

**Comment by dcelasun** [comment]
That's quite possible, we just need a postgres-specific alternative to [this](https://github.com/rickbergfalk/sqlpad/blob/d52fc6dadbe59361d387af8b31e8fb679c47f442/routes/schema-info.js#L50-L55) query. I don't have access to a postgres instance nowadays, so feel free to send a PR. If not, maybe someone else can pick it up.

**Comment by rickbergfalk** [comment]
this will be addressed in next sqlpad version

**Comment by rickbergfalk** [comment]
version 1.17.0 has been published to npm
