### ISSUE TITLE
Swap nedb out for sequelize & sqlite

### ISSUE THREAD

**Issue by rickbergfalk** [rickbergfalk/sqlpad#533]
The embedded database used by SQLPad today is nedb, and operates by holding all data in memory and appending JSON records to a line-delimited json file. 

This works well so far, but nedb itself has not been supported for some time. I've also avoided storing larger amounts of data in it, since it is an in-memory data store. Using nedb also limits SQLPad to being a single instance (2 SQLPad processes cannot share the same database).

I'd like to consider moving SQLPad to use sqlite, using sequelize as an ORM to standardize the interaction with the database. 

Using sqlite keeps SQLPad simple to start with. Sqlite technically also enables sharing the database file across SQLPad instances, though it'd require shared access to the underlying file system.

Sequelize is a fairly mature ORM in the Node.js ecosystem. While it can be problematic if abused, it also opens up the potential to easily migrate SQLPad to a more robust database if desired in the future (Postgres, MySQL, or MS SQL Server, but these would be a long way off). 

Using this combo will also enable cleaning up other legacy quirks of SQLPad. Sequelize can be leveraged to store sessions in whatever backing database it is connected to, instead of using the file system store (https://www.npmjs.com/package/connect-session-sequelize). The habit of storing JSON files on the file system can also be avoided, instead storing the data in whatever sequelize is connected to. While sqlite is still technically storing data on the file system, it at least provides some structure to the data, and allows for a unified format.

**Comment by rickbergfalk** [comment]
This is something that was started with #554 and seeing the benefits of being able to use sqlite, I'm convinced. I'll keep this issue open until things are converted 100%.

**Comment by rickbergfalk** [comment]
This was slated for v5 release, but might take a while and I'd prefer to make some breaking changes fixes in the mean time (like fixing API). Instead aiming to make this a v6 breaking change

**Comment by bruth** [comment]
I just ran into this multi-process, one database limitation today. I wasn't aware the underlying database was in-memory, I assumed SQLite was already being used. Obviously no fault to you or the project! But I am definitely interested in this change moving forward. If there is anything my team can help with, please let us know.

**Comment by rickbergfalk** [comment]
Thanks @bruth! I'll let you know if there's anything I could use some help with. I'll see if I can move this up in priority. 

I was going to focus v5 on some REST API improvements and realized the nedb data model quirks are getting in the way, so I might decrease the scope of the API changes and get this in instead...

What is your thoughts on session storage? Instead of using sequelize/sqlite for session storage, I'm considering expanding the options to in-memory and redis (which is most common I'd say) and eventually deprecate the file-session-storage in use today.

**Comment by bruth** [comment]
Redis may be an obvious choice for sessions, although depending on the scale you are looking at, SQLite could like handle that just fine up to a handful of users. Adding additional dependencies is obviously a trade-off in getting started with the application. It is quite nice that you can run a single container and get started. Scaling out to support many concurrent users would hit the limitations of SQLite fairly quickly due to the single-writer lock. So Redis or even a server-based database (if Postgres, MySQL, etc. would be alternative options to SQLite) would likely be sufficient for the expected scale.
