### ISSUE TITLE
SQL Server Trusted Authentication

### ISSUE THREAD

**Issue by forkandspoon** [rickbergfalk/sqlpad#56]
Hello,

This is not an issue, but I am having problems connecting to our network SQL Server (ELOGIN error). I believe this is because we are using Windows Authentication/Trusted Connection. Does SQLpad support this connection setting?

Thanks,
JD

**Comment by rickbergfalk** [comment]
Hi JD - I don't believe SqlPad supports windows auth at the moment, but I can see about adding support for it. There is an encrypt option for SQL Server connections though, which might help with the trusted part? I'll have to do some investigating...

**Comment by forkandspoon** [comment]
Hi Rick,

I did some searching and it appears the current driver (Tedious) does not support Windows Auth, however I believe msnodesql provides this (Windows only driver).

https://www.npmjs.com/package/mssql

via `options.trustedConnection=TRUE`

I have msnodesql installed on my machine, so I could possibly hard code the connection parameters into sqlpad for testing. Which is the best place for me to write this in? i.e. where are the connection parameters saved?

Thanks you.

**Comment by forkandspoon** [comment]
I've managed to shoehorn msnodesql into Sqlpad. The database connection parameters are hardcoded, but have allowed me to showcase this as a demo for my team.

To replicate:
1) Install Sqlpad as per normal
2) Install msnodesql. Navigate to mssql node_modules directory
3) To install a precompiled version (https://github.com/jorgeazevedo/node-sqlserver-unofficial), ``npm install node-sqlserver-unofficial``, rename the folder from ``node-sqlserver-unofficial`` to ``msnodesql``
4) Open Sqlpad ``run-server.js`` and under ``sqlconfig`` add
```
driver: 'msnodesql',
connectionString: ''Driver={SQL Server Native Client 11.0};Server=[server name];Database=[database name];Trusted_Connection={Yes};'
```

Currently server and database are hardcoded values, I expect this should be easy to expand for the connection form - will give it a go this weekend and send a pull request.

**Comment by rickbergfalk** [comment]
Glad you were able to get it working JD.

I'm not sure if it's the same as trusted auth, but it looks like the tedious driver supports a domain log in. Is that related or something separate?

I'm all for expanding the database support for sqlpad, but I'd like to keep the dependencies in package.json to pure javascript packages to prevent people from needing to compile packages, and I could see some people being a bit cautious installing an unofficial pre-compiled driver.

I'm completely open to adding msnodesql support in the SqlPad code though. 

If at all possible, could we leave installing the native driver as a manual step, similar to what you went through? 

In the sqlpad code, the require('msnodesql') could be wrapped in a try catch, just in case someone has not installed it. We could make a note in the documentation as well that the official driver could be installed, or the unofficial pre-compiled one. 

As for how to manage the connection ui - I'd be fine with however you'd like to accomplish it. Either this could be extra form elements in the existing "SQL Server" driver form, or it could be a separate driver all together (maybe we have a "SQL Server" option and a "SQL Server Native" option?)

This process is similar to how Oracle support was envisioned - just haven't gotten around to it (nor do I have an oracle instance to test against)

Let me know if you have any questions. 

Good luck with the development :)

**Comment by Seddryck** [comment]
@rickbergfalk You're correct "Trusted Authentication" or "Domain Log In" are the same. Basically you don't need to provide a Database Username and a Password because SQL Server will use your own domain account to authenticate. 

Basically, the connection string is a little bit different, you don't provide the tokens UserID and Password but in place you need to specify the token "Integrated Security = SSPI".

Would be great to have the support for this kind of connection strings.

**Comment by rickbergfalk** [comment]
I'm going to close this issue for now, but I'm going to be watching the official microsoft node-sqlserver driver. According to the readme, they are going to be releasing a new version of the driver in the coming months. 

Hopefully it will support Trusted Authentication and maybe offer precompiled binaries for the popular platforms...

**Comment by MarkGStacey** [comment]
New issue logged as MS has released a new version:
https://github.com/rickbergfalk/sqlpad/issues/220
