### ISSUE TITLE
Support cli or API to administrator connection, access, account...

### ISSUE THREAD

**Issue by btsken** [rickbergfalk/sqlpad#577]
Hi

Thanks for the very good project!

I have some needs, is sqlpad support CLI or API to let me can administrator connections, access control and account setting?

I think it will be useful.

**Comment by rickbergfalk** [comment]
Thanks @btsken! Unfortunately there is no CLI or API at this time. 

It is possible to use HTTP basic auth for an existing user and use the API that way, but it is not documented and may go away in the future. If your curious, the server test cases use this mechanism to do the API integration tests, so they could be used as an example.

I think a formal API implementation would be a nice addition though.

**Comment by rickbergfalk** [comment]
Sorry @btsken meant to follow up with you on this. JWT service tokens were added in 4.2.0 that can be used to manage things via API. 

Not all APIs are documented however. I would recommend either using browser dev tools and inspecting requests made, and/or referencing the server API test directory, as most APIs are covered https://github.com/rickbergfalk/sqlpad/tree/master/server/test/api
