### ISSUE TITLE
providing a json file for connection

### ISSUE THREAD

**Issue by agates4** [rickbergfalk/sqlpad#582]
https://rickbergfalk.github.io/sqlpad/#/connections?id=defining-connections-via-configuration

in documentation, it says I can provide a json file to list all my connections. I've tried this using the "SQLPAD_CONNECTIONS" environment variable and passing through a path to the json file.

this did not work

there is no documentation to using a json file for connections. can you tell me how?

**Comment by agates4** [comment]
I am using docker-compose and right now have sloppy solution here

  sqlpad:
    image: "sqlpad/sqlpad"
    ports:
      - 127.0.0.1:5026:3000
    environment:
      SQLPAD_ADMIN_PASSWORD: helloWorld1
      SQLPAD_ADMIN: admin
      SQLPAD_CONNECTIONS__my_db__name: db
      SQLPAD_CONNECTIONS__my_db__driver: sqlserver
      SQLPAD_CONNECTIONS__my_db__host: mssql
      SQLPAD_CONNECTIONS__my_db__port: 1433
      SQLPAD_CONNECTIONS__my_db__database: master
      SQLPAD_CONNECTIONS__my_db__username: sa
      SQLPAD_CONNECTIONS__my_db__password: helloWorld1

**Comment by rickbergfalk** [comment]
Hi @agates4 - I can see where the documentation is not clear. The connections would be defined in the config file if you have one already, and would then point to it with `--config` or `SQLPAD_CONFIG=/path/to/file_with_config_and_connections.json`

I'll try to expand on the documentation and provide some concrete examples

**Comment by agates4** [comment]
thanks rick that makes sense. will there be support for passing through a path to json from env variable in docker compose?

**Comment by rickbergfalk** [comment]
Setting the path with `SQLPAD_CONFIG` env variable should work, but you'll have to ensure the file is mapped and placed inside the container.

**Comment by rickbergfalk** [comment]
I've expanded on the documentation a bit for configuring connections via JSON file. Hopefully this adds some clarity. If not please continue to ask questions and I'll expand on it as I can :)

https://rickbergfalk.github.io/sqlpad/#/connections?id=via-json-config-file
