### ISSUE TITLE
[bigquery] Multi-dataset schema support

### ISSUE THREAD

**Issue by bruth** [rickbergfalk/sqlpad#587]
In BigQuery, the top-level unit is a project which can have one or more datasets each of which has one or more tables. This akin to a Postgres database -> schema -> table hierarchy.

@murphyke Is there support for rendering multiple datasets in the side-bar schema and not requiring specifying a dataset in the connection?

**Comment by murphyke** [comment]
@bruth That's up to the driver, which could be modified to do whatever makes sense. I assume the BigQuery API will allow obtaining the datasets available to a project. Right now the driver is just querying for tables using the configured dataset, as you can see.

@hessam61 could look into this. Hopefully SQLPad allows another layer to the hierarchy, but maybe there would be a decent way of changing this if not.

**Comment by bruth** [comment]
Ok thanks. For our use case at least that will be required since we will be hosting at least two datasets for users.

**Comment by murphyke** [comment]
@bruth @hessam61 The BigQuery Node.js client library docs are [here](https://googleapis.dev/nodejs/bigquery/latest/index.html).

SQLPad calls [the driver's getSchema function](https://googleapis.dev/nodejs/bigquery/latest/index.html) to obtain the data to populate the side-bar schema pane.

You can see that the driver gets the data into partial shape and then call's SQLPad's [formatSchemaQueryResults function](https://github.com/rickbergfalk/sqlpad/blob/master/server/drivers/utils.js) to transform it further. From the data model output by `formatSchemaQueryResults`, it looks like SQLPad should multiple schemas just fine (which is probably obvious from the UI, but I'm not looking at it).

**Comment by rickbergfalk** [comment]
I think this should be possible if you're just looking to populate data sets. Most driver implementations use a SQL query to get the schema but you're not necessarily limited to that at all.

I'm open to expanding on or changing the format used for hierarchy if necessary BTW. Today it is restricted to 3 levels, and requires 3 levels (schema -> table -> column w/type & w/description). It might make more sense to have this tree not require schema, or allow another layer above that (like project or database)

**Comment by bruth** [comment]
Thanks @rickbergfalk. I will correct my first comment, this is requesting the three levels. In BigQuery a `schema` is just called a `dataset`. We don't need to project or database in the hierarchy. So if three levels are supported then it would be a matter of the BigQuery driver doing the right request to pull all datasets available within the project (akin to a database in Postgres).
