### ISSUE TITLE
Restrict Query History to Admins

### ISSUE THREAD

**Issue by rickbergfalk** [rickbergfalk/sqlpad#611]
With the addition of query ACL (and connection access I suppose) its is possible query history can expose some queries not meant for others to see.

@koszti any issue if I move this to be an admin privilege along with users, connections, connection accesses, and service tokens?

**Comment by eladeyal-intel** [comment]
It's OK for a non admin to see his own history but not others'. It's OK for the admin to see everybody's. But probably the admin also wants to see his own history too.

Non admin seeing other's history is not acceptable I think.

**Comment by rickbergfalk** [comment]
Good point - this route could be updated to additionally restrict the results to the user of the session and left alone. 

I just merged some work on changing the way how queries are run, and it kind of overlaps with the query-history somewhat. 

Eventually I'd like to move things towards the user being able to see the history of the query they are currently viewing (along with the results if they have not been purged)

**Comment by rickbergfalk** [comment]
@eladeyal-intel query history has been restricted for non-admins in `latest`/master
