### ISSUE TITLE
Cannot run sqlpad, unhandled error

### ISSUE THREAD

**Issue by tjerkw** [rickbergfalk/sqlpad#62]
Disabling Google authentication streategy, since there's no GOOGLE_CLIENT_ID or no GOOGLE_CLIENT_SECRET in ENV.
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: listen EACCES 0.0.0.0:80
    at Object.exports._errnoException (util.js:837:11)
    at exports._exceptionWithHostPort (util.js:860:20)
    at Server._listen2 (net.js:1218:19)
    at listen (net.js:1267:10)
    at Server.listen (net.js:1363:5)
    at Object.<anonymous> (/usr/local/Cellar/nvm/0.26.1/versions/node/v4.1.0/lib/node_modules/sqlpad/server.js:149:24)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)

**Comment by paultela** [comment]
You need to be root to bind to port 80, try using `sqlpad --port 3000` and it should work.

**Comment by rickbergfalk** [comment]
Thanks @paultela! @tjerkw does running as root solve your issue? 

I think you could potentially get this or a similar error if the port is already in use as well...

**Comment by bnmnetp** [comment]
I got the same error as @tjerkw initially. Tunning it with --port 8000 just gives me a signin heading, with no signin form.  trying to access /signup results in an error message in the browser window, ``Cannot load signup``

However, running with sudo works fine.  It would be nice to get this working without the need for sudo.

**Comment by ryantuck** [comment]
if the primary use case is to run locally, you may want to run on port 3000 by default, and possibly add some flag if you're running on some cloud server to bind to 80/443 as needed. 

i say this after initially downloading, super excited to try it out, and getting an error before even playing around with the app. it's super slick, btw - great job.

**Comment by rickbergfalk** [comment]
Thanks @ryantuck! glad you like it. 

I'd be alright making port 3000 the default, but might save that for a bigger release/breaking change.

What if in the interim a patch is added to check to see if port 80 is available, and if not, switch over to 3000?

**Comment by ryantuck** [comment]
@rickbergfalk that sounds like a pretty reasonable patch that doesn't seem like it would affect anything too negatively!

**Comment by rickbergfalk** [comment]
This has been implemented in the v2 branch. beta release will be published in npm in a few weeks.
