### ISSUE TITLE
Two columns with the same name

### ISSUE THREAD

**Issue by bruth** [rickbergfalk/sqlpad#629]
In the "Why not SQLPad" section:

> It can't handle a query with 2 columns returned of the same name.

What is the underlying reason for this?

**Comment by rickbergfalk** [comment]
Just poor query result format decision in the past on my part 😅 

Query results are returned from drivers and throughout sqlpad as an array of objects `[{ col_a: 'value' }]` instead of an array of arrays.

It is also partially because this is the default response format for most db drivers, though some (maybe all?) might support returning results in an array format.

**Comment by bruth** [comment]
Understood. The constraint does cause issues when doing seemingly basic queries like `select *` with a join.. in which case the two join columns prevent the query from rendering if they are named the same thing.

I would be happy to work on this if you can point me to the general locations of where these "array of objects" constructions exist. If the array of objects permeate rendering and what not, then a strategy I have used in the past is to scan the column names and append a integer suffix when a duplicate name is found. Then they can all co-exist in an object.

**Comment by rickbergfalk** [comment]
The unfortunate (or maybe fortunate?) part of all this is something that would require special handling for each driver. For bigquery for example, I'm pretty sure the array of objects is first referenced here: https://github.com/rickbergfalk/sqlpad/blob/master/server/drivers/bigquery/index.js#L79. 

From there the rows data is passed on to things that create the file downloads in advance, then pass the results to the browser.

The upside to all this is you could take a shot and implement the column numbering approach for bigquery, and others can be done gradually as needed. 

Another option I've thought about is having 2 different kind of query result formats, and indicating that as appropriate the the queryResults object that is passed around.

**Comment by bruth** [comment]
Thanks. I will take a pass at the BQ driver for starters.

**Comment by bruth** [comment]
Well this is interesting. So it turns out that BigQuery does not support duplicate column names. I didn't realize the error was coming from BigQuery and not SQLPad since I was aware of that limitation already so I incorrectly assumed.

There are a couple workarounds that I found which seem reasonable. Doing {{select foo.* except (col1, col2, ...)}} selects all columns and then exclude specific ones. So if the message pops up specifying which columns ares duplicates, those would be listed in one or more of offending tables.

Another syntax that is supported is selecting the _table_, e.g. {{select foo}} rather than {{select foo.*}} which returns the rows as records. Multiple tables can be listed and this effectively namespaces the columns with the table names. However one issue in that records are rendered as JSON-encoded objects in the result table. But this behavior would be pretty easy to change in the driver. It would Inspect the top-level objects and flatten the first-level of objects. This I will likely open a PR to support for the BigQuery driver.

**Comment by bruth** [comment]
Closing since there is unfortunately no general way to support this. If the assumption is to unpack any column value that is represented as an object, then native BigQuery columns with the struct type would fall into that category.

For our use case, we internally discussed and are pushing towards explicit column names or using the `except ( ... )` syntax. This has the added benefit that columns won't appear or disappear without the using be aware of it.
