### ISSUE TITLE
Result table column headers misaligned

### ISSUE THREAD

**Issue by daveloyall** [rickbergfalk/sqlpad#63]
Hi. I'm using Firefox 45.0a1 (2015-12-11) (64 bit, Nightly) on Windows 7.

The results table looks like this:

![capture](https://cloud.githubusercontent.com/assets/1524866/11789271/07e2be90-a25b-11e5-8ce8-8ecb049c2df1.PNG)

I hope this helps.

**Comment by daveloyall** [comment]
I'm using 1.12.0 installed via NPM.

**Comment by rickbergfalk** [comment]
Thanks @daveloyall 

From some initial testing it looks like the grid library in use (slickgrid) isn't being displayed correctly in Firefox. Display is aligned for me in the latest Chrome and IE 11. 

Unfortunately slickgrid's maintainer has taken a break from the project... we'll need to find and updated fork or a suitable alternative.

**Comment by daveloyall** [comment]
Hm, it is tough to find a suitable fork because Github's 'Network Graph' is automatically disabled for SlickGrid.

So, I connected to Github's API and got a list of pull requests...  And produced the following list...  It shows how many pull requests came from each fork.  I hope this helps, good luck!

    hobbes@metalbaby:~$ sort ~/scratch/Document2.txt |uniq -c|sort -nr
          8         "full_name": "PerformanceHorizonGroup/SlickGrid",
          4         "full_name": "yakirmanor/SlickGrid",
          4         "full_name": "TNKSoftware/SlickGrid",
          3         "full_name": "icoxfog417/SlickGrid",
          2         "full_name": "tradingtechnologies/SlickGrid",
          2         "full_name": "STRML/SlickGrid",
          2         "full_name": "royling/SlickGrid",
          2         "full_name": "RandScullard/SlickGrid",
          2         "full_name": "kzhdev/SlickGrid",
          2         "full_name": "Koloto/SlickGrid",
          2         "full_name": "JLynch7/SlickGrid",
          2         "full_name": "jamesongamble/SlickGrid",
          2         "full_name": "ChadPrice/SlickGrid",
          1         "full_name": "zamabraga/SlickGrid",
          1         "full_name": "YupengFu/SlickGrid",
          1         "full_name": "yokkaichi/SlickGrid",
          1         "full_name": "yanavery/SlickGrid",
          1         "full_name": "xrmx/SlickGrid",
          1         "full_name": "wtvamp/SlickGrid",
          1         "full_name": "truk/SlickGrid",
          1         "full_name": "TrainingPeaks/SlickGrid",
          1         "full_name": "tjormola/SlickGrid",
          1         "full_name": "techit-ung/SlickGrid",
          1         "full_name": "taskputty/SlickGrid",
          1         "full_name": "stanislavgeorgiev/SlickGrid",
          1         "full_name": "SpeCT/SlickGrid",
          1         "full_name": "sp-csmithhill/SlickGrid",
          1         "full_name": "sortex/amdjs-SlickGrid",
          1         "full_name": "smithkl42/SlickGrid",
          1         "full_name": "SimplGy/SlickGrid",
          1         "full_name": "SimonBrangwin/SlickGrid",
          1         "full_name": "seriesoftubes/SlickGrid",
          1         "full_name": "saulocastelo/SlickGrid",
          1         "full_name": "rostg/SlickGrid",
          1         "full_name": "reebalazs/SlickGrid-touch",
          1         "full_name": "pythonanywhere/SlickGrid",
          1         "full_name": "ptraca/SlickGrid",
          1         "full_name": "prystupa/SlickGrid",
          1         "full_name": "pigiax/SlickGrid",
          1         "full_name": "paulsfds/SlickGrid",
          1         "full_name": "Odaeus/SlickGrid",
          1         "full_name": "oadam/SlickGrid",
          1         "full_name": "MSeal/SlickGrid",
          1         "full_name": "mr-stateradio/SlickGrid",
          1         "full_name": "momaci/SlickGrid",
          1         "full_name": "mltroutt/SlickGrid",
          1         "full_name": "mikemsq/SlickGrid",
          1         "full_name": "michalcarson/SlickGrid",
          1         "full_name": "meyogi/SlickGrid",
          1         "full_name": "marioandujar/SlickGrid",
          1         "full_name": "jstormes/SlickGrid",
          1         "full_name": "jsm222/SlickGrid",
          1         "full_name": "jrschumacher/SlickGrid",
          1         "full_name": "joaoFelix/SlickGrid",
          1         "full_name": "jeroenpeeters/SlickGrid",
          1         "full_name": "jcready/SlickGrid",
          1         "full_name": "jbthoma/SlickGrid",
          1         "full_name": "icambron/SlickGrid",
          1         "full_name": "ibrahimkarahan/SlickGrid",
          1         "full_name": "hnakamur/SlickGrid",
          1         "full_name": "henriks/SlickGrid",
          1         "full_name": "henkli/SlickGrid",
          1         "full_name": "gsanta/SlickGrid",
          1         "full_name": "graemian/SlickGrid",
          1         "full_name": "geriamir/SlickGrid",
          1         "full_name": "frankguixianhua/SlickGrid",
          1         "full_name": "fbuchinger/SlickGrid",
          1         "full_name": "fatihsoydan/SlickGrid",
          1         "full_name": "emertechie/SlickGrid",
          1         "full_name": "ejlo/SlickGrid",
          1         "full_name": "drawyan/SlickGrid",
          1         "full_name": "dergraf/SlickGrid",
          1         "full_name": "DemarsM/SlickGrid",
          1         "full_name": "ddomingues/X-SlickGrid",
          1         "full_name": "DataSplice/SlickGrid",
          1         "full_name": "DarthVictor/SlickGrid",
          1         "full_name": "dandv/SlickGrid",
          1         "full_name": "CrocInc/SlickGrid",
          1         "full_name": "codiemullins/SlickGrid",
          1         "full_name": "cmatheson/SlickGrid",
          1         "full_name": "ckosmowski/SlickGrid",
          1         "full_name": "cho7herve/SlickGrid",
          1         "full_name": "cdeng/SlickGrid",
          1         "full_name": "Catroque/SlickGrid",
          1         "full_name": "bseib/SlickGrid",
          1         "full_name": "bryandragon/SlickGrid",
          1         "full_name": "brondavies/SlickGrid",
          1         "full_name": "brokenseal/SlickGrid",
          1         "full_name": "borota/SlickGrid",
          1         "full_name": "BlazeCell/SlickGrid",
          1         "full_name": "blaremc/SlickGrid",
          1         "full_name": "bighuggies/SlickGrid",
          1         "full_name": "berislavlopac/SlickGrid",
          1         "full_name": "benjaminsonday/SlickGrid",
          1         "full_name": "bdwidhalm/SlickGrid",
          1         "full_name": "bbuchalter/SlickGrid",
          1         "full_name": "bbankowski/SlickGrid",
          1         "full_name": "B1nke/SlickGrid",
          1         "full_name": "a-poptsov/SlickGrid",
          1         "full_name": "andrewagga/SlickGrid",
          1         "full_name": "aleksj/SlickGrid",
          1         "full_name": "albaxe/SlickGrid",
          1         "full_name": "aemonge/SlickGrid",

**Comment by daveloyall** [comment]
(Of course my little list doesn't include anybody who might have made a bunch of changes but never sent in a PR...)

**Comment by rickbergfalk** [comment]
Since SlickGrid hasn't been updated in quite some time, and there does not appear to be a primary fork that is getting all the attention, I'm thinking about abandoning it all together. 

So far I'm leaning towards http://nexts.github.io/Clusterize.js/ 

It uses a similar technique to handle many records in the browser. Its smaller, actively maintained, and allows for flexibility in what is displayed (we can render whatever html we'd like easily in the table). The only downside I can think of is that the columns can't be expanded by the user, but I don't know how critical that will be since the table won't be hiding any information and might better automatically size column width and row height appropriately. 

Thoughts?

**Comment by daveloyall** [comment]
No thoughts beyond that I'm glad you're looking into it.  I won't bikeshed. :)

**Comment by rickbergfalk** [comment]
This has been addressed in the upcoming v2 release. I've switched the result grid to utilize the FixedDataTable component (http://facebook.github.io/fixed-data-table/) instead of slickgrid.

This is currently implemented in the v2 branch. It'll be published to npm under a beta version September.
