### ISSUE TITLE
Detect & Inject LIMIT / FETCH FIRST n ROWS ONLY

### ISSUE THREAD

**Issue by rickbergfalk** [rickbergfalk/sqlpad#631]
I have a request to detect and enforce/inject the LIMIT clause or similar into SELECT queries, in order to protect SQLPad against `SELECT * FROM really_big_table` queries, and drivers that do not support a streaming the result set.

Supplying the LIMIT in the query likely generates a better query plan, so this is likely beneficial for the target database too.

The downside to this is... it can be tricky to do across the board for different SQL engines. This also modifies user queries, which could lead to unknown errors or errors with line/char positions that do not line up if a database support that.

As a solution, I've decided to take a shot at creating a flexible lib that allows specifying different "strategies" for limiting queries. https://rickbergfalk.github.io/sql-limiter/

Still need to test it out, but I'm more positive about this approach. 

I'm still thinking about how to implement this. I can't decide on whether this should be opt-in per connection, or enabled automatically for each driver. 

Any thoughts on this @bruth @murphyke @gonace @koszti

**Comment by bruth** [comment]
I think adding this explicitly as a connection option would be reasonable. To inform the user that the query is being capped, a little help message could be rendered in the UI indicating this. If there is a desire to know if there are more records than the cap, then the limit would need to be executed as a limit + 1, but that may not be necessary.

In terms of injection, that library demo looks pretty good. Another strategy is to simply wrap the users query `select * from ( ... ) limit N` (I presume most query planners will optimize that properly) which may reduce any edge cases you encounter with modifying the query directly. You are right that error messages from the server that call out specific line/char position could be an issue unless that is parsed and adjusted.

**Comment by murphyke** [comment]
@rickbergfalk I thought that this is what the `queryResultMaxRows` config option is for. That is passed into drivers via a connection object in a `maxRows` key.

**Comment by rickbergfalk** [comment]
That is correct @murphyke -- the `maxRows` is passed into the drivers, but it is up to each driver to handle differently. Postgres and SQL Server stream query results, so they can cut the query off once that maxRows is hit. 

Other drivers, such as node odbc, doesn't support any kind of streaming unfortunately, and buffer all rows into memory, then takes the first n rows per the `maxRows`. This works for smaller queries, but results in out-of-memory errors for something like `SELECT * FROM millions_of_rows_table`.

This detecting and injecting would just be an alternate implementation option for drivers that don't support a streaming method, and is perhaps more friendly for the target db too.

@bruth I thought about wrapping the user query too but wasn't sure how that would play out with CTEs. I'm thinking I could add a `limit-wrap` strategy to the library though to give people options if one proved to be problematic.

**Comment by murphyke** [comment]
@rickbergfalk OK, I assumed that the individual drivers were already handling this as best they could. The limiter lib seems like an OK idea because of the error message complication. Even for APIs that stream results, it would be better to limit the query to get better performance in some cases and reduce the load on the backend. BigQuery's API directly supports row limits, so the BigQuery driver already has this issue covered.

**Comment by rickbergfalk** [comment]
I ended up taking a mixed approach with this. As of current state, all queries executed are being split into individual statements using `sql-limiter`, then run by whatever driver is used by the connection.

Whether the limiter is enforced using that lib is up to the driver implementation. For Postgres, redshift, mysql, mysql2, sqlite, the `sql-limiter` call and config is hardcoded into the driver implementation. For odbc, the limit strategy to use is configurable by the end user, since we don't know which strategies to use. 

Some drivers are being left alone due to either enforcing their own limits in various ways, being too obscure/not easily tested, and/or laziness on my part :)

I'm not supporting `mssql` in `sql-limiter` because of the way `TOP` works and the complexities around that. `mssql` has fairly good streaming support too, so I think it is okay. Other drivers like `crate` limit the results anyways if I recall correctly.

I'm going to say this is complete enough to close the issue :) Other driver implementations can evolve as needed.
