### ISSUE TITLE
Crash on incorrect SQL query (PostgresSQL)

### ISSUE THREAD

**Issue by eladeyal-intel** [rickbergfalk/sqlpad#637]
I'm just trying out sqlpad (via docker). It seems to me that if I write an incorrect SQL query (with PostgresSql), sqlpad crashes. See some logs here.

```
ERR events.js:288
ERR       throw er; // Unhandled 'error' event
ERR       ^
ERR error: syntax error at end of input
ERR     at Connection.parseE (/usr/app/node_modules/pg/lib/connection.js:614:13)
ERR     at Connection.parseMessage (/usr/app/node_modules/pg/lib/connection.js:413:19)
ERR     at TLSSocket.<anonymous> (/usr/app/node_modules/pg/lib/connection.js:129:22)
ERR     at TLSSocket.emit (events.js:311:20)
ERR     at addChunk (_stream_readable.js:294:12)
ERR     at readableAddChunk (_stream_readable.js:275:11)
ERR     at TLSSocket.Readable.push (_stream_readable.js:209:10)
ERR     at TLSWrap.onStreamRead (internal/stream_base_commons.js:186:23)
ERR Emitted 'error' event on Client instance at:
ERR     at connectedErrorHandler (/usr/app/node_modules/pg/lib/client.js:202:10)
ERR     at Connection.connectedErrorMessageHandler (/usr/app/node_modules/pg/lib/client.js:209:7)
ERR     at Connection.emit (events.js:311:20)
ERR     at TLSSocket.<anonymous> (/usr/app/node_modules/pg/lib/connection.js:134:12)
ERR     at TLSSocket.emit (events.js:311:20)
ERR     [... lines matching original stack trace ...]
ERR     at TLSWrap.onStreamRead (internal/stream_base_commons.js:186:23) {
ERR   name: 'error',
ERR   length: 84,
ERR   severity: 'ERROR',
ERR   code: '42601',
ERR   detail: undefined,
ERR   hint: undefined,
ERR   position: '19',
ERR   internalPosition: undefined,
ERR   internalQuery: undefined,
ERR   where: undefined,
ERR   schema: undefined,
ERR   table: undefined,
ERR   column: undefined,
ERR   dataType: undefined,
ERR   constraint: undefined,
ERR   file: 'scan.l',
ERR   line: '1074',
ERR   routine: 'scanner_yyerror'
ERR }
OUT Exit status 1
```

I'm using sqlpad v4.4.0 from dockerhub.

The server is PostgreSQL 9.5.0 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.1.2 20080704 (Red Hat 4.1.2-55), 64-bit

* I also don't see an error message returned from server. Just a  purple window with "Server responded not ok"

**Comment by seanno** [comment]
+1 just hit this too, every sql error kills the process.

**Comment by seanno** [comment]
FWIW editing back the pg module dependency to 7.18.2 and pg-cursor to 2.1.9 (that second one almost certainly not relevant to the issue) fixed the problem on my local build. Looks like this was updated about a month ago in PR #625.

**Comment by rickbergfalk** [comment]
Thanks for the info both. I noticed that there have been some updates to the pg modules, so I'll check if those updates fix things otherwise roll back.

**Comment by rickbergfalk** [comment]
I've updated the postgres driver libraries (pg and pg-cursor) to latest, and added a test case for getting a helpful error message back for a bad query.

All postgres tests are passing now.

Let me know how things go. Fix is available in `latest` docker image/running from `master`

**Comment by eladeyal-intel** [comment]
Things don't work for me now - I get "unable to verify the first certificate". My main use case is mysql which works for me so hopefully @seanno can verify this was fixed.

**Comment by eladeyal-intel** [comment]
Things seem to fail differently now.

For psql with the query `SELECT moo` - On the server I see
```
[2020-06-09T05:38:30.714Z] DEBUG (sqlpad-app/1046 on xxx): Executing (default): UPDATE `statements` SET `status`=?,`stop_time`=?,`duration_ms`=?,`row_count`=?,`columns`=?,`incomplete`=?,`updated_at`=? WHERE `id` = ?
error: column "moo" does not exist
    at Parser.parseErrorMessage (./server/node_modules/pg-protocol/dist/parser.js:241:15)
    at Parser.handlePacket (./server/node_modules/pg-protocol/dist/parser.js:89:29)
    at Parser.parse (./server/node_modules/pg-protocol/dist/parser.js:41:38)
    at TLSSocket.<anonymous> (./server/node_modules/pg-protocol/dist/index.js:8:42)
    at TLSSocket.emit (events.js:311:20)
    at addChunk (_stream_readable.js:294:12)
    at readableAddChunk (_stream_readable.js:275:11)
    at TLSSocket.Readable.push (_stream_readable.js:209:10)
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:186:23)
[ERROR] 05:38:30 error
[2020-06-09T05:38:30.726Z] INFO  (sqlpad-app/1046 on xxx): Received SIGTERM, shutting down server...
```
and on the client I see this
![image](https://user-images.githubusercontent.com/20379005/84110145-fb529e00-aa2c-11ea-937b-451169d8290a.png)

For the same query with mysql I get `Unknown column 'MOO' in 'field list'` nicely presented in the query results pane.

**Comment by rickbergfalk** [comment]
Is this still an issue? I tried just now on latest and get an expected result

![postgres-error](https://user-images.githubusercontent.com/303966/85358054-65148280-b4d8-11ea-80de-5962580895a2.jpg)

**Comment by eladeyal-intel** [comment]
I had to refresh the clinet (control-F5) and now works for me too
