### ISSUE TITLE
Unnamed columns have no width in the result table

### ISSUE THREAD

**Issue by daveloyall** [rickbergfalk/sqlpad#64]
As you can see in this screen shot, unnamed columns have no width.  So they don't get displayed.

![capture](https://cloud.githubusercontent.com/assets/1524866/11789443/0a29cada-a25c-11e5-841a-f435984e5219.PNG)

I hope this helps.

**Comment by daveloyall** [comment]
I'm using 1.12.0 installed via NPM.

**Comment by rickbergfalk** [comment]
I'll have to take a look at this. Some of the assumptions made in SqlPad is that all columns will have names, thinking that the columns would later be mapped to a chart attribute. We might be able to accommodate unnamed columns in the grid view, but it's very likely it would require a lot of reworking how query results are passed around in SqlPad.

**Comment by daveloyall** [comment]
FYI any kind of math `column_A+column_B` or use of functions `datepart(ddd,shipping_date)` will result in an unnamed column unless the query author explicitly provides a column name.

I don't know how your database driver works, but in JDBC you can address columns either by numeric index or name.  There is something called ResultSetMetadata which contains (among other things) a map of type int --> string which provides the known column names, with nulls (or missing keys?) for the unnamed columns.  Applications can provide some default ("unnamed column") or even unique default ("unnamed column 1", "unnamed column 2") when the map lookup fails or returns null.

Cheers!

**Comment by dcelasun** [comment]
The structure of the result sets are sadly driver specific in the Node world; every driver does things a little bit differently. Like you suggested, we can probably solve this after query results are converted to the [common format sqlpad uses](https://github.com/rickbergfalk/sqlpad/blob/f313fdc5861102a9c2f24b0f21c66c869273fe16/lib/run-query.js#L256-L259). I'll try to take a look at this soon.

**Comment by rickbergfalk** [comment]
I was able to work in a special handling for this case when querying SQL Server. Unnamed columns are numbered off and given the name "UNNAMED COLUMN x". 

This will be in the next major version of sqlpad. 

Officially, I'd like to say querying without column names in sqlpad is unsupported, and that SQL Server is just a special exception :) 

If other db users want to figure out how to add this sort of functionality to the database connection they are using I'm all for it and will accept pull requests, but I likely won't be putting too much effort into supporting this edge case.
