### ISSUE TITLE
non-admin password-less login

### ISSUE THREAD

**Issue by eladeyal-intel** [rickbergfalk/sqlpad#645]
My usecase for sqlpad is "minimal interaction" - click a URL and write sql.

When I set `DISABLE_AUTH=true`, everyone can login (which is good) but everyone get Admin access (which is not good). I would prefer an option to auto-login as Editor. (Connections are configured via env vars).

**Comment by eladeyal-intel** [comment]
I tried to implement that in #646.

I guess it would be slightly better if I could have a "secret URL" - i.e. a URL with a token which will let users connect as guests (and others still can connect as admin).

**Comment by rickbergfalk** [comment]
I've thought about this too and I think its reasonable to have the disable auth role configurable. 

Guest access is something I think would be good to add as well but I want to try and consider all the different use cases. Something I'd like to implement but haven't gotten to is the idea of a "public" or "guest" user that can have an even more restricted role than editor if desired. (maybe the guest can execute queries, but not modify them for example)
