### ISSUE TITLE
external tables

### ISSUE THREAD

**Issue by acivitillo** [rickbergfalk/sqlpad#647]
It seems that external tables are not supported. We are using Redshift Spectrum and its external tables can be queried in SqlPad but they don't show up in the tree left sidebar.

**Comment by rickbergfalk** [comment]
Does Redshift use the postgres driver to connect? 

Its likely that the schema query would need to be altered to get at external tables. I'm curious if external tables are also missing from the postgres connections as well.

If the query is not compatible, we can create a redshift specific driver option in SQLPad (that still uses the postgres driver behind the scenes) and runs a different query designed for redshift schema.

**Comment by acivitillo** [comment]
Correct, same driver, but this might be a Redshift specific query: https://docs.aws.amazon.com/redshift/latest/dg/r_SVV_EXTERNAL_TABLES.html

Your approach should be correct because the query will pass through the postgres driver but it is a different query, this is what we need to query to get the list of tables:

```sql
SELECT *
FROM SVV_EXTERNAL_TABLES
WHERE schemaname='spectrum'
```

**Comment by acivitillo** [comment]
I see, so we'd have to change this: https://github.com/rickbergfalk/sqlpad/blob/master/server/drivers/postgres/index.js

And the below query.

I can give you the query if it helps? I am not that good with javascript and wouldn't know how to replicate your coding environment on my local PC to add the changes and the tests. I can do it but it will take few weeks, let me know.

Meanwhile as for the query, I guess we'd need to do a UNION if we want to stick to 1 SCHEMA_SQL. We'd union external and normal tables.

Of course the best solution would be for the sidebar to become a tree view and show tables, external and views nodes. But for now just throwing all tables and external tables under a schema would be great. 

```
const SCHEMA_SQL = `
  select 
    ns.nspname as table_schema, 
    cls.relname as table_name, 
    attr.attname as column_name,
    trim(leading '_' from tp.typname) as data_type,
    pg_catalog.col_description(attr.attrelid, attr.attnum) as column_description
  from 
    pg_catalog.pg_attribute as attr
    join pg_catalog.pg_class as cls on cls.oid = attr.attrelid
    join pg_catalog.pg_namespace as ns on ns.oid = cls.relnamespace
    join pg_catalog.pg_type as tp on tp.typelem = attr.atttypid
  where 
    cls.relkind in ('r', 'v', 'm')
    and ns.nspname not in ('pg_catalog', 'pg_toast', 'information_schema')
    and not attr.attisdropped 
    and attr.attnum > 0
  order by 
    ns.nspname,
    cls.relname,
    attr.attnum
`;
```

**Comment by rickbergfalk** [comment]
@acivitillo If you could get the query for me that'd be great! I'd be more than happy to add a redshift specific driver that uses it. I just wouldn't be able to test the integration of it.

**Comment by acivitillo** [comment]
Here is the sql. I could not get the `column_description` for external table but it is not really needed I think.

```sql
select 
    schemaname as table_schema,
    tablename as table_name,
    columnname as column_name,
    external_type as data_type,
    'no description' as column_description
from SVV_EXTERNAL_COLUMNS
union all
select table_schema,
        table_name,
        column_name,
        data_type,
        column_description
    from
    (select 
        ns.nspname as table_schema,
        cls.relname as table_name,
        attr.attname as column_name,
        trim(leading '_' from tp.typname) as data_type,
        pg_catalog.col_description(attr.attrelid, attr.attnum) as column_description
    from 
        pg_catalog.pg_attribute as attr
        join pg_catalog.pg_class as cls on cls.oid = attr.attrelid
        join pg_catalog.pg_namespace as ns on ns.oid = cls.relnamespace
        join pg_catalog.pg_type as tp on tp.typelem = attr.atttypid
    where 
        cls.relkind in ('r', 'v', 'm')
        and ns.nspname not in ('pg_catalog', 'pg_toast', 'information_schema')
        and not attr.attisdropped 
        and attr.attnum > 0
    order by 
        ns.nspname,
        cls.relname,
        attr.attnum)
```

**Comment by rickbergfalk** [comment]
Thanks @acivitillo I'll try to get this implemented today and will let you know when it can be tested

**Comment by rickbergfalk** [comment]
Added a Redshift Spectrum driver and labeled it experimental. I tested the query running aspects against Postgres, but I'm not able to confirm the schema at all.

Removed some of the settings.... if there are any additional settings that should be removed let me know. Same for any that would be useful to add :)

**Comment by acivitillo** [comment]
It works! (I just noticed github issue editor does not support confetti emojis)

One thing I have noticed is that the `Test` button in `Connections` sometimes incorrectly reports bad test. This seems to be consistent with the redshift driver but I have seen it happening of couple of other times with Postgres too.

Also I would call the driver `Redshift` because this driver pulls schemas/tables for everything in Redshift, not only spectrum.

### Amazing External Tables

![image](https://user-images.githubusercontent.com/54931660/83937431-d102a580-a7cc-11ea-9f31-f577e8602edc.png)


### Test Button Issue

![image](https://user-images.githubusercontent.com/54931660/83937452-04453480-a7cd-11ea-9bdc-f8ed03312c63.png)

**Comment by rickbergfalk** [comment]
@acivitillo great to hear. 

Will this query work for someone that has Redshift and not Redshift Spectrum? Or would that never happen?

**Comment by acivitillo** [comment]
Yes it would work as spectrum is a “plugin” on top of Redshift.

Sent from my iPhone

On 8. Jun 2020, at 19:13, Rick Bergfalk <notifications@github.com> wrote:

﻿

The following message was sent from an external e-mail address. Be cautious when clicking on links, opening attachments or providing sensitive information.

________________________________

@acivitillo<https://github.com/acivitillo> great to hear.

Will this query work for someone that has Redshift and not Redshift Spectrum? Or would that never happen?

**Comment by rickbergfalk** [comment]
Just a heads up I've merged in the change to rename Redshift Spectrum to Redshift.

@acivitillo If you have a connection configured via config or seed data, you'll need to change the driver value from `redshiftSpectrum` to `redshift`. 

If the connection was set via UI, a migration will take care of it for you on startup.
