### ISSUE TITLE
query w/o connection missing feedback

### ISSUE THREAD

**Issue by eladeyal-intel** [rickbergfalk/sqlpad#648]
Open sqlpad. Make sure the connection chooser is on the default "... choose connection". write a query and "click run"

Expected behavior: Some kind of error indication

Observed behavior: "Query time" starts counting and the spinner is presented indefinitely.

![image](https://user-images.githubusercontent.com/20379005/83347442-cc9e3e80-a32d-11ea-93ce-dcb663f95011.png)

**Comment by rickbergfalk** [comment]
This is fixed in latest/master too :)
