### ISSUE TITLE
Log contains "Row limit hit", but none of these tables are that big

### ISSUE THREAD

**Issue by daveloyall** [rickbergfalk/sqlpad#65]
FYI, I am seeing this in my log:

    Row limit hit - Attempting to cancel query...
    Query cancelled successfully

I read somewhere that the default row count limit is 50,000.  Even if it were only 1000, the fact is that none of the tables I have queried today contain more than a few dozen rows.

I think the row limit is being hit by some internal query that SqlPad is doing automatically.  This might indicate a bug somewhere...

I'm using 1.12.0 installed via NPM.  My DB is MS SQL Server.  If you need other information or would like to recommend some settings I can change to get more detailed logs, just let me know.

**Comment by dcelasun** [comment]
The only thing I can think of is the schema info query. How many schemas / tables do you have? If you run [this](https://github.com/rickbergfalk/sqlpad/blob/f313fdc5861102a9c2f24b0f21c66c869273fe16/routes/schema-info.js#L66-L71) query outside sqlpad, how many rows does it return?

**Comment by daveloyall** [comment]
The number of resultant rows varies depending on which context I am in.  I mean, which database I am connected to.

When I invoke `use MASTER` before invoking that SQL, I only back 44 rows.

When I `use some_work_related_database`, I get over 22,000 rows.  (That DB is a beast!)

I hope this helps.

**Comment by rickbergfalk** [comment]
@dcelasun I was thinking it was the schema info query too, but that query overrides the max row setting.

@daveloyall are you executing multiple queries at a time returning multiple result sets? I think the row count would count all rows returned in the batch, which could maybe explain what we are seeing...

**Comment by daveloyall** [comment]
@rickbergfalk nope, I'm certain none of the queries I ran manually would return more than a few hundred rows, even if I ran them all at the same time.

What about enabling debugging logs?  Sorry, this is the first node app I've ever used, so I don't know how to do that.  I'm a Java developer, so I'm familiar with Log4j for example.

**Comment by rickbergfalk** [comment]
@daveloyall no worries - right now SqlPad isn't logging much. If you wanted to see what's happening out of curiosity, you can clone the repo and run server.js directly, and add some console.log() statements various places.
 
Otherwise I think it might be good to add a --debug flag to the application that logs a variety of activity.

I'll open a separate issue for that work.

**Comment by rickbergfalk** [comment]
@daveloyall SqlPad 1.13.0 includes a --debug flag that will log all queries run within SqlPad. It isn't anything fancy at this point, but should help figure out which query is causing this message.

**Comment by daveloyall** [comment]
Thanks, @rickbergfalk!

**Comment by rickbergfalk** [comment]
@daveloyall I'm going through and cleaning up some old issues. going to close this for now - let me know if you're still running into this issue
