### ISSUE TITLE
Will not save unworking connection

### ISSUE THREAD

**Issue by eladeyal-intel** [rickbergfalk/sqlpad#657]
1. Connections
2. Add Connections
3. Pick any driver. Fill any text in all the fields.
4. Click Save - save is successful.
5. Now it is impossible to edit this connection (possibly the only way would be to overwrite all fields until you get a working connection). It seems sqlpad will let you *create* a non-working connection, but not *update* it. Furthermore, when you click "Save" the window just disappears, without notification that things were not saved.

**Comment by rickbergfalk** [comment]
I'll look into this. I'm guessing this is related to a lot of the restructuring/data migrations done moving to SQLite
