### ISSUE TITLE
Anonymous users can see eachother's history

### ISSUE THREAD

**Issue by eladeyal-intel** [rickbergfalk/sqlpad#658]
related to #652 

set `disableAuth`=`true` and `disableAuthDefaultRole`=`editor`.
Person A logs in (as anonymous editor) and executes a query. 
Person B (from different browser) logs in (as anonymous editor) and clicks History.
Person B sees person A's history.

![image](https://user-images.githubusercontent.com/20379005/83445145-20f00e00-a455-11ea-996b-afd0e0e2cae5.png)

I guess somewhere there's a "IS NOT NULL" missing.

(I wouldn't mind if the History button is removed altogether in this scenario)

**Comment by rickbergfalk** [comment]
Will have to think about this further. 

Anonymous user doesn't get persisted to the db, but even if it did, I'd think it'd be the same value, and we'd have the same problem. 

I'm kind of leaning towards needing a distinction between the no-auth/disabled auth "user" and a guest that doesn't have an identity
