### ISSUE TITLE
Doesn't support multiple result sets

### ISSUE THREAD

**Issue by daveloyall** [rickbergfalk/sqlpad#66]
SqlPad doesn't support multiple result sets.

![capture](https://cloud.githubusercontent.com/assets/1524866/11796257/00cdd6fa-a281-11e5-8ee4-19fd478b9756.PNG)

Here's the same query in SSMS:

![capture](https://cloud.githubusercontent.com/assets/1524866/11796304/460cdfc2-a281-11e5-9525-4a23f22b2508.PNG)

**Comment by daveloyall** [comment]
Here is a related issue... Try this query:

    select 'foo' [column A], 'bar' [column B]
    GO
    This is not SQL.

SQL server does return a result for the first query.  The "Incorrect syntax" error message comes back separately.  But, SqlPad doesn't display the result, only the error...

**Comment by rickbergfalk** [comment]
Thanks for the feedback @daveloyall. Unfortunately this falls beyond the scope of SqlPad. The main use case will always be focused on consuming a single result set. Another somewhat related limitation is that a new connection is created and then closed each time a query is run, so there's no ability to utilize SQL Server temp tables across query runs

An undocumented tip you  may find handy - if you  highlight SQL text and click run only that text will be executed. Not sure it helps with what you're looking to do but you could at least store separate SQL statements in one SqlPad query and run separately as desired.
