### ISSUE TITLE
free anonymous users from connection selection

### ISSUE THREAD

**Issue by eladeyal-intel** [rickbergfalk/sqlpad#660]
When logging anonymously (`disableAuth`), editor user is directed to `queries/new`. In my setup there is only one configured connection, but the is still presented with "..choose connection" where she must select the active connection in order to run.

There are two things which can be improved I think:

1. If there is only one connection available, do not show "...choose connection" (or even hide the connection dropbox at all) and auto select the connection.

2. allow the URL to connect the connection id - maybe `queries/new?connection=connectionname` and have this pre-configure the connection

**Comment by rickbergfalk** [comment]
I'm open to both of these options. For specifying the connection in the url, I'd prefer either `connectionId` or `connectionName` fields be specified.

**Comment by eladeyal-intel** [comment]
So the first option was merged :-) thank rick

I would love if someone helps implementing the second option, specifying connection name via URL
