### ISSUE TITLE
dbInMemory

### ISSUE THREAD

**Issue by eladeyal-intel** [rickbergfalk/sqlpad#665]
It appears that setting `dbInMemory` means user creation does not survive app restart (container restart). Is this correct? Is this intentional? if so I propose to add it to documentation clearly.

**Comment by rickbergfalk** [comment]
Yeah its more for testing, though I could see it being used for cases ephemeral use cases as well. 

For example, I found this instance of SQLPad that has no auth and isn't persisting any user data. In memory only would be fine for this I'd think. https://covid.bit.io/queries/new
