### ISSUE TITLE
SequelizeTimeoutError on startup

### ISSUE THREAD

**Issue by eladeyal-intel** [rickbergfalk/sqlpad#667]
I'm deploying with Docker, and finally trying to set a persistent volume under `/var/lib/docker` (so that container restart does not cause users data to be lost) .  The volume may be a bit slow - but the application certainly has read & write access.

sqlpad fails to start because of this, when trying to perform 

        CREATE TABLE IF NOT EXISTS `schema_version` (`name` VARCHAR(255) NOT NULL UNIQUE PRIMARY KEY);

I get
```
SequelizeTimeoutError: SQLITE_BUSY: database is locked
   at Query.formatError (/usr/app/node_modules/sequelize/lib/dialects/sqlite/query.js:419:16)
   at Query._handleQueryResponse (/usr/app/node_modules/sequelize/lib/dialects/sqlite/query.js:73:18)
   at Statement.afterExecute (/usr/app/node_modules/sequelize/lib/dialects/sqlite/query.js:250:31)
   at Statement.replacement (/usr/app/node_modules/sqlite3/lib/trace.js:19:31)
   at Statement.replacement (/usr/app/node_modules/sqlite3/lib/trace.js:19:31)","type":"Error","msg":"Error starting SQLPad"}
```

Any ideas? I thought there maybe there's a concurrency issue

The volume is CIFS / SMB.

**Comment by eladeyal-intel** [comment]
I've read [here](https://www.sqlite.org/wal.html) that "WAL mode does not work over network. I thought that might be it but https://github.com/sequelize/sequelize/issues/5245 suggests the default is "DELETE" (and not WAL).

**Comment by rickbergfalk** [comment]
Is Sequelize using WAL? I wasn't thinking it was. Is there anything else that might have a lock on the database? 

I'll have to take a look at the startup order of operations. Maybe there's something that is running asynchronously on startup that really should be sync.

**Comment by rickbergfalk** [comment]
@eladeyal-intel weirdly enough I'm seeing this now in the migration test case. Investigating...

**Comment by rickbergfalk** [comment]
Wait my mistake - I'm not seeing the BUSY error, but instead SQLITE_CANTOPEN: unable to open database file. Further investigation this CANTOPEN error seems to be a known issue https://github.com/sequelize/sequelize/issues/9691.

Going switch to using the old dialect/storage parameters for SQLite, otherwise use the URI if provided. 

Fixes my issue, not sure if it will help with this one.

**Comment by eladeyal-intel** [comment]
I think it's OK to close this issue since there is a workaround (`SQLPAD_BACKEND_DB_URI`)
