### ISSUE TITLE
SqlPad connections are tied to a single database even when the user can access more

### ISSUE THREAD

**Issue by daveloyall** [rickbergfalk/sqlpad#67]
At work, I have three Microsoft SQL Server instances and each has multiple databases inside.

Some of my existing queries touch multiple databases.  This works fine in SqlPad, but the schema view on the left is tied to a single database.

So, if I want to review the columns in some table, I have to create another connection which is tied to the database that table resides in.

Meanwhile, in SQL Server Management Studio, all the databases I have access to appear in the schema view on the left.

So, the feature I am requesting is an additional level of abstraction above 'database' in the schema view.

**Comment by dcelasun** [comment]
This would not only require a major overhaul to pretty much everything, but it would also break existing saved queries (since a database is no longer automatically selected).

@rickbergfalk can correct me here, but I think this would break too many things for very little benefit, for a handful of users. SqlPad is a small, simple query editor / visualizer for internal networks. It's not meant to replace SQL Server Management Studio or any other large SQL software.

**Comment by rickbergfalk** [comment]
We could potentially keep everything the same on this, and just support the expanded schema in the schema-info sidebar. It could even be implemented as a SQL Server specific feature, and the schema tree would accommodate things at the database level if it is available. The connection itself would still be tied to the specified database. to reach other databases you'd have to use the full object name [database].[schema].[table].

A potential challenge with this though could be schema info tree performance in the browser. While some optimizations were made a while back, SqlPad still loads the whole thing up front. For some large databases I work with this can still take a while to render. I can't imagine what would happen if you had many reasonably sized databases. Some sort of ajax tree traversal could occur, but it'd add complication.

I wouldn't be opposed to someone adding this in, but for me it would be pretty low priority. I agree with @dcelasun in that SqlPad is a small and simple tool, and I wouldn't be sad if a single-database-at-a-time mindset was officially adopted :)

**Comment by daveloyall** [comment]
Yep, no worries!

**Comment by motion-x86** [comment]
Any updates on this topic? This will be a great feature to add.

**Comment by rickbergfalk** [comment]
@motion-x86 there hasn't been any more consideration given to it at all given the complexity it would add. 

Out of curiosity are you using SQL Server?

**Comment by motion-x86** [comment]
Sad news, but thanks for the update.
Yes my team is running multiple SQL server instances in docker each of which could contain any number of databases, which can be dynamically created on each server. We were hoping to use `sqlpad` as the tool of choice to explore those servers and the databases contained within them. However the lack of the above mentioned feature renders the tool useless for our use case.
