### ISSUE TITLE
search result has extra data 

### ISSUE THREAD

**Issue by kpioneer123** [rickbergfalk/sqlpad#689]
SELECT
	b.bookId AS '书ID',
	b.bookName AS '书名',
	u.nickname AS '作者名',  
         .....

normal result  ： 书ID⋮书名⋮作者名
but now has  extra data
fieldCount ⋮ affectedRows⋮ insertId ⋮ serverStatus ⋮ warningCount ⋮ message⋮protocol41⋮changedRows⋮书ID⋮书名⋮作者名

**Comment by rickbergfalk** [comment]
Hi @kpioneer123 -- Could I get the database driver and sqlpad version you are using?

**Comment by rickbergfalk** [comment]
@kpioneer123 closing for now -- we can reopen with more info
