### ISSUE TITLE
Deprecate INI/JSON config and add .env file support.

### ISSUE THREAD

**Issue by rickbergfalk** [rickbergfalk/sqlpad#690]
I just ran into [this ini bug](https://github.com/npm/ini/issues/81) when setting an ODBC connection string via INI file.

Unfortunately looks like the `ini` lib is not actively maintained anymore, and I'm not interested in forking and publishing a fixed version myself. 

Is JSON enough or should a more human friendly alternative be added in its place? (TOML perhaps? https://github.com/toml-lang/toml)

**Comment by eladeyal-intel** [comment]
Are .env files supported ? I tried to look for it online and am under the impression that something needs to be included in code for support. If so it would be good to mention it. I like .env files better than JSON because they are copy-and-paste to deployment env variables. They are pretty much the same as ini files except they use the env variable name instead of the json name, and the connection configrations can't have their own [section]. They are thus a good enough replacement to ini files in my opinion.

**Comment by rickbergfalk** [comment]
.env files are not supported but they could be. For variables that need a section I've seen other applications use double underscores as a separator (which is how connections are currently defined via environment variables). 

I like that .env has comment support too.

If .env file support was adopted... what do you think about removing JSON support? 

I like the options, but if JSON were removed it'd allow for documentation to be simplified a lot. This week I've helped troubleshoot 2 malformed JSON files too... something that wouldn't happen if .env was used...

**Comment by rickbergfalk** [comment]
I should add not only could documentation be simplified, but code to manage the config as well.

**Comment by eladeyal-intel** [comment]
I don't think I have a strong opinion.

**Comment by rickbergfalk** [comment]
This is one the hardest parts as maintainer.... If it were just me I'd drop JSON and standardize on environment vars/.env file in an instant. Less to maintain and document. 

However as an end user it could be inconvenient... Maybe I'm using JSON and it is fine and if it is removed I need to change. But maybe it is beneficial in the long run if things are easier to read about in documentation?

I guess ideally I'd like someone to chime in and say "I use JSON but I wouldn't mind being 
restricted to environment variables"... but that probably won't happen 🙃.

Anyone out there want to tell me its okay to drop JSON file support 😂 (Or make a case to leave it in?)

**Comment by rickbergfalk** [comment]
.env is added in 5.1.0 and JSON/INI deprecated
