### ISSUE TITLE
unsupported non-english column name in SELECT clause

### ISSUE THREAD

**Issue by wolfee9633** [rickbergfalk/sqlpad#694]
running SQL like "select `姓名` from test;" will return "invalid syntax at line 1 col 9: select `姓名` from test; ^" error, while other clients like Navicat Or PHPMyAdmin return correct result for the same SQL.
I thought it's a encoding issue and have tried to add following statement in the Pre-query Statements, but actually it doesn't work..
SET character_set_client = utf8 ;
SET character_set_connection = utf8 ;
SET character_set_database = utf8 ;
SET character_set_results = utf8 ;
SET character_set_server = utf8 ;

I plan to view the source code to dig more deep, but it really helps a lot if someone can get me some clues.
please help. thanks..

**Comment by eladeyal-intel** [comment]
You did not specify which driver you are using and which database.

**Comment by wolfee9633** [comment]
Sorry. I use Mysql Driver and Mysql 5.7 Community Server.

**Comment by eladeyal-intel** [comment]
interestingly this works for me: `select "姓名";`

I wonder if it is needed to do like this
```js
var connection = mysql.createConnection({ ... , charset : 'utf8'});
```

(or maybe  `utf8mb4` ? I'm not su

**Comment by wolfee9633** [comment]
No. Not directly select "姓名". I mean there is a column named "姓名". I know it's not a good practice to use non-English name for a column. But in some cases, you know...
please refer the following statements to reproduce.
1、create a table named "test" and insert test rows.
```
SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for test
-- ----------------------------
DROP TABLE IF EXISTS `test`;
CREATE TABLE `test`  (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `姓名` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 3 CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of test
-- ----------------------------
INSERT INTO `test` VALUES (1, 'ttt');
INSERT INTO `test` VALUES (2, 'ddd');

SET FOREIGN_KEY_CHECKS = 1;
```

2、run SQL
`select 姓名 from test;
select `姓名` from test;`

both of the 2 SELECT query statements above will return error: invalid syntax at line 1 col 9: select `姓名` from test; ^

**Comment by eladeyal-intel** [comment]
I tried adding `charset: 'utf8',` in mysql2.js but did not seem to help. 

I think @wolfee9633  commands for building the table don't work as well (I get invalid syntax at line 10 col 4: `姓名`)

I imagine this shorter SELECT shows the same problem.

```sql
select   1 as 名;
```

**Comment by wolfee9633** [comment]
Adding ' around alias is a workaround for non-English alias case.
```
select   1 as '名';
```
 works well.
But if the Non-English character is column name, I got no way for now.

**Comment by eladeyal-intel** [comment]
@wolfee9633  try this 
```
select `姓名` as '姓名' from test;
```

**Comment by wolfee9633** [comment]
> @wolfee9633 try this
> 
> ```
> select `姓名` as '姓名' from test;
> ```
> 
> ```
> select 姓名 as '姓名' from test;
> ```

ummm...doesn't work as well.

**Comment by eladeyal-intel** [comment]
```sql

select `姓名` as A from test;
```

?

**Comment by wolfee9633** [comment]
well, this doesn't work, either.
And I found out just now it's not a must to create a TEST table for reproduce this issue.
In any connection created in sqlpad
```
select `姓名` from test;
select `姓名` from test;
```
will return syntax error for me, even there is no table named TEST in the database.

I think this means the statement doesn't even pass grammar OR SQL convention check phase in sqlpad, because normally this statement should return "Table doesn't exist" error.

**Comment by rickbergfalk** [comment]
Sorry I haven't looked into this yet.

@wolfee9633 I think you're on the right track troubleshooting though. Based on the queries you and @eladeyal-intel are trying I think this might be related to the sql-limiter library parsing the SQL https://rickbergfalk.github.io/sql-limiter/ and not the nodejs mysql driver? 

I'll have to take a look into this further. `sql-limiter` is a wrapper around the `moo` library... which I hope supports non-english characters otherwise we'll have to rethink the sql limiter approach.

**Comment by rickbergfalk** [comment]
I just tried 

```
select `姓名` from test;
```

On sql-limiter page and got the syntax error :( Will need to look into that further

**Comment by rickbergfalk** [comment]
Sorry @wolfee9633 I think I know where the problem is looking at `sql-limiter` implementation. 

For identifiers it is using limited English characters to check for columns/tables https://github.com/rickbergfalk/sql-limiter/blob/master/src/get-statements.js#L46.

I think what I can do is alter the order of the rules, and make the assumption that anything that isn't caught by rules is treated as an identifier of some kind.

What things are classified as doesn't really matter. `sql-limiter` is being used as a way to split batch statements and inject a limits

**Comment by rickbergfalk** [comment]
Fix is in `latest` / `master`. 

Underlying issue was that `sql-limiter` didn't support backtick quotes and non-English characters. Both are resolved.

**Comment by wolfee9633** [comment]
thanks a lot. I've updated with master branch. Issue resolved!
