### ISSUE TITLE
sqlpad crashes with Error: read ECONNRESET  (MySQL driver)

### ISSUE THREAD

**Issue by mahaesin** [rickbergfalk/sqlpad#699]
Likely since #697 sqlpad may crash a few minutes after a query on a mysql database was completed.

```
events.js:288
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:205:27)
Emitted 'error' event on Connection instance at:
    at Connection._handleProtocolError (/usr/app/node_modules/mysql/lib/Connection.js:423:8)
    at Protocol.emit (events.js:311:20)
    at Protocol._delegateError (/usr/app/node_modules/mysql/lib/protocol/Protocol.js:398:10)
    at Protocol.handleNetworkError (/usr/app/node_modules/mysql/lib/protocol/Protocol.js:371:10)
    at Connection._handleNetworkError (/usr/app/node_modules/mysql/lib/Connection.js:418:18)
    at Socket.emit (events.js:311:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: 'ECONNRESET',
  code: 'ECONNRESET',
  syscall: 'read',
  fatal: true
}
```

Sqlpad is started via docker-compose using the latest image (compose file as in #695)

**Comment by rickbergfalk** [comment]
Let me see if I can reproduce. 

Out of curiosity does turning on multi-statement transactions for the connection help at all?

**Comment by rickbergfalk** [comment]
I'm unable to reproduce on my end. May I get the specific database and version you're using with the MySQL driver? (is this mariadb or mysql, 5 or 8?)

I did push a fix to `latest`/master to gracefully handle client errors. Hopefully that resolves the issue. What I don't quite know is if the client recovers from this ECONNRESET error.

**Comment by mahaesin** [comment]
Thank you for the quick fix! With this the client recovers, but the pad is empty afterwards (like the container was restarted).

My setup uses mariadb. Version string: `10.5.3-MariaDB-1:10.5.3+maria~focal`

Multi-statement transactions are turned on.

I can reproduce the error using a example database from [mariadb (nation.zip)](https://www.mariadbtutorial.com/getting-started/mariadb-sample-database/)

Running a query like `SELECT * FROM continents`
and waiting 5-10 minutes should trigger the error.

Zipped database, configuration and docker-compose file:
[sqlpad_debug.zip](https://github.com/rickbergfalk/sqlpad/files/4818512/sqlpad_debug.zip)

Log file:
[sqlpad_debug_econnreset.log](https://github.com/rickbergfalk/sqlpad/files/4818518/sqlpad_debug_econnreset.log)

**Comment by eladeyal-intel** [comment]
Did you remember to refresh client? Control f5 in Google Chrome

**Comment by mahaesin** [comment]
I tried some older versions of mariadb but the behaviour is the same.

But when i set `multiStatementTransactionEnabled` to false i see no such errors any more.

**Comment by mahaesin** [comment]
> Did you remember to refresh client? Control f5 in Google Chrome
Sorry, i'm not sure what you mean - when should i refresh?

(My observation of an empty pad after the error was caught by the mentioned fix is somewhat meaningless. I think i actually refreshed the browser then, so ... i emptied it myself.)

**Comment by eladeyal-intel** [comment]
@mahaesin , see https://refreshyourcache.com/en/cache/ "Force Refresh".

**Comment by mahaesin** [comment]
@eladeyal-intel You mean refreshing after updating sqlpad to a newer build? Yes, i think i did that.

As mentioned above i seem to have refreshed the client after ECONNRESET occured in the server logs (5 to 10 minutes after a query was run).
If i do not refresh the client doesn't recover: No new queries can be run. I get the message
`"Cannot enqueue Query after fatal error."`

**Comment by eladeyal-intel** [comment]
"force refresh" is different than "refresh". I simple refresh may load JS from cache and sometimes miss that a new version of the client code was deployed.

**Comment by rickbergfalk** [comment]
Thanks for the zipped files @mahaesin I'll see if I can get this reproduced on my end.

When googling about this I keep coming back to this stackoverflow answer and wondering if MySQL is just terminating the stale connection and the node.js driver is unhappy about it. https://stackoverflow.com/questions/22900931/mysql-giving-read-econnreset-error-after-idle-time-on-node-js-server

**Comment by rickbergfalk** [comment]
15 minutes in and I haven't hit the error yet. I'm wondering if there is something else at play here with docker and OS?

I'm on Windows 10 insider build and Docker edge 2.3.1.0

**Comment by mahaesin** [comment]
Very strange, but thanks for your attention! 

My first test setup is a Debian 10 system running
Docker version 18.09.1

I downloaded the zip file to a different Linux system (running opensuse with Docker version 19.03.11) an got the error after a `select * from continents;` and waiting for 10 minutes.
[sqlpad_debug_econnreset_2020_06_24.log](https://github.com/rickbergfalk/sqlpad/files/4825653/sqlpad_debug_econnreset_2020_06_24.log)

MariaDB returns `600` as response to
`show variables like 'wait_timeout';`
so above question on stackoverflow seems to be a good explanation. I will increase MariaDB's timeout value and check the effect.

**Comment by mahaesin** [comment]
If i change the value of MariaDB's `wait_timeout`, the error/crash occurs accordingly.

I could also trigger the error on a system running Windows 10 and docker 19.03 but only if i run my test query in sqlpad and switch to another browser tab, so sqlpad stays in background. If sqlpad is visible it seems to 'refresh' the connection sometimes (`docker logs <sqlpad_container> -f` shows some action) and ECONNRESET does not occur.

[log_windows.log](https://github.com/rickbergfalk/sqlpad/files/4852238/log_windows.log)

As a workaround I changed my setup to `multiStatementTransactionEnabled = false` which is fine for me.

**Comment by rickbergfalk** [comment]
mysql and mysql2 based connections now have the `INTERACTIVE` flag set as of `5.4.0`, which should increase the wait_timeout setting automatically and prevent this from occurring. 

If we still see this we can explore other options to work around this.
