### ISSUE TITLE
SAP Hana support

### ISSUE THREAD

**Issue by torax242** [rickbergfalk/sqlpad#7]
Just to flex my fingers I added support for the SAP Hana database. Anyone interested in this addition?

**Comment by dcelasun** [comment]
Sure, send a PR and we'll take a look. Thanks!

**Comment by rickbergfalk** [comment]
That'd be great! And it looks like its a purely javascript-based driver right? I'm fine with adding support for any other database so long as it doesn't require compiling a native driver :)

**Comment by rickbergfalk** [comment]
@torax242 did you ever get around to adding SAP Hana support? I'd definitely love to support it.

I wouldn't mind implementing it myself, I'd just need something to test against. Are there any free SAP Hana hosting options out there? or a dev version that can be installed for free?

**Comment by rickbergfalk** [comment]
I signed up for a trial Hana account but it doesn't appear to be a practical target to develop against. From what I gathered, if you aren't building your application in the Hana cloud, you need to run some sort of tunnel to connect? 

If someone wants to add in support for SAP Hana I'd gladly take a pull request, but for the time being I'm going to close this issue.
