### ISSUE TITLE
how to reload config file without killing the daemon?

### ISSUE THREAD

**Issue by FlorinAndrei** [rickbergfalk/sqlpad#700]
Let's say sqlpad-config.json has changed - I've added a couple more connections. Is there a way to tell sqlpad to reload the config file without killing sqlpad?

I tried `kill -HUP $pid` but the sqlpad process dies. I want to avoid that.

**Comment by rickbergfalk** [comment]
Ah... currently this is not supported. I'd be open for adding support to this, but I think it might have to be limited to a subset of config values. 

For example, changing the database path might have to remain be something that requires a full restart.

Out of curiosity is it just connections you're changing or would there be other settings you'd hope would update as well?

**Comment by FlorinAndrei** [comment]
In this particular case it's just connections. This is part of a fairly dynamic DB cluster, and I want to reconfigure SQLPad automatically as DB nodes are added/removed to/from the cluster.

Yeah, I realize some settings must be buried pretty deeply into the app, so those might be hard to change dynamically. But things like the dbPath seem unlikely to ever need to be adjusted dynamically (famous last words).

Okay, I will restart the daemon after reconfig for now. Thanks!
