### ISSUE TITLE
legit-looking JSON config crashes the server

### ISSUE THREAD

**Issue by FlorinAndrei** [rickbergfalk/sqlpad#701]
v4.4.0

admin user/pass are provided via env vars.

This works:

```
{
  "dbPath": "/root/server/db",
  "httpsPort": 443,
  "ip": "0.0.0.0",
  "port": 80,
  "systemdSocket": false
}
```

This doesn't work:

```
{
  "dbPath": "/root/server/db",
  "httpsPort": 443,
  "ip": "0.0.0.0",
  "port": 80,
  "systemdSocket": false,
  "connections:" {
    "local": {
      "name": "local",
      "driver": "mysql",
      "host": "localhost",
      "database": "test",
      "username": "test",
      "password": "test",
      "mysqlInsecureAuth": true
    }
  }
}
```

Error is:

```
{"level":30,"time":"2020-06-22T19:49:06.417Z","pid":541,"hostname":"vnode-98-184","name":"sqlpad-app","msg":"Loading users","v":1}
{"level":30,"time":"2020-06-22T19:49:06.419Z","pid":541,"hostname":"vnode-98-184","name":"sqlpad-app","msg":"Loading connections","v":1}
{"level":30,"time":"2020-06-22T19:49:06.419Z","pid":541,"hostname":"vnode-98-184","name":"sqlpad-app","msg":"Loading connectionAccesses","v":1}
{"level":30,"time":"2020-06-22T19:49:06.420Z","pid":541,"hostname":"vnode-98-184","name":"sqlpad-app","msg":"Loading queries","v":1}
{"level":30,"time":"2020-06-22T19:49:06.420Z","pid":541,"hostname":"vnode-98-184","name":"sqlpad-app","msg":"Loading queryHistory","v":1}
{"level":30,"time":"2020-06-22T19:49:06.420Z","pid":541,"hostname":"vnode-98-184","name":"sqlpad-app","msg":"Loading cache","v":1}
{"level":40,"time":"2020-06-22T19:49:06.421Z","pid":541,"hostname":"vnode-98-184","name":"sqlpad-app","msg":"CONFIG NOT RECOGNIZED: Key { in file /app/scripts/sqlpad-config.json.","v":1}
...
{"level":50,"time":"2020-06-22T19:49:06.422Z","pid":541,"hostname":"vnode-98-184","name":"sqlpad-app","msg":"\n  \"dbPath\" not provided in config. \n  This was previously defaulted to /root/sqlpad/db.\n  This must now be explicitly set.","v":1}
```

Nothing else is different. I just add that section, restart the daemon, and it refuses to work.

The syntax looks fine to me. What could possibly cause this?

**Comment by rickbergfalk** [comment]
Hi @FlorinAndrei -- It looks like there's a syntax issue with `"connections:" {` in that it should be `"connections": {`

In 4.4.0 SQLPad falls back to trying to parse JSON as an INI file, which is going to be made more strict in v5 to hopefully help catch these issues.

**Comment by FlorinAndrei** [comment]
OMG - sorry, that was totally my bad. I've fixed it and now it works. Thank you.

**Comment by rickbergfalk** [comment]
No worries @FlorinAndrei. Its strange lately I've helped troubleshoot a few JSON configs. It is easy to do.

Are you partial to the format? I'm contemplating dropping it and replacing it with a friendlier file that supports comments. 

Hoped INI to be this, but I've discovered some quirks with INI as well.

**Comment by FlorinAndrei** [comment]
I think if the parser could point at the specific place where it fails, a lot of these issues would become self-evident.

As for JSON vs something else - that's the eternal struggle. 😄  I use JSON for this project because the files are machine-generated, so I don't care for comments, and JSON is trivial to make. But in other contexts, yeah, that might be an issue. Horses for courses, I guess.

Thank you for your help.
