### ISSUE TITLE
what is the version  of the screenshot on README.md 

### ISSUE THREAD

**Issue by sonymoon** [rickbergfalk/sqlpad#704]
[https://camo.githubusercontent.com/d5fdaac9f32d901233068fcf1fa930cea3d50ace/68747470733a2f2f7269636b6265726766616c6b2e6769746875622e696f2f73716c7061642f696d616765732f73637265656e73686f74732f76332d626574612e706e67](https://camo.githubusercontent.com/d5fdaac9f32d901233068fcf1fa930cea3d50ace/68747470733a2f2f7269636b6265726766616c6b2e6769746875622e696f2f73716c7061642f696d616765732f73637265656e73686f74732f76332d626574612e706e67)

**Comment by rickbergfalk** [comment]
Its quite old. The initial v3 I think? I've been meaning to update it along with rest of project screenshots

**Comment by eladeyal-intel** [comment]
I think the graphs presented in the screenshots are not something you can create with current software?

Here's a macabre substitute

![image](https://user-images.githubusercontent.com/20379005/86045099-c34ee180-ba53-11ea-981b-e62d9623774a.png)

**Comment by rickbergfalk** [comment]
I forgot that used the old mock driver. Something that looks like the chart should be possible, but not with that query.

The covid db case is a nice showcase of things but it has a customized header, so it isn't accurate in that sense.

**Comment by rickbergfalk** [comment]
Updated the screenshot with a recent 5.1.0 image of a basic bar chart, reporting on the sqlpad database itself :)
