### ISSUE TITLE
Update to Sequelize v 5.22 (at least)

### ISSUE THREAD

**Issue by yorek** [rickbergfalk/sqlpad#705]
The latest version improved support for passing options in the URL.

https://github.com/sequelize/sequelize/releases/tag/v5.22.0

This will enable storing metadata into an Azure SQL database. It would be great if you can make a new release targeting this new version, thanks!

**Comment by eladeyal-intel** [comment]
@yorek are you / will you be using #668?

**Comment by yorek** [comment]
Yes. So that one can do, for example:

```
mssql://user:password@server.database.windows.net/database?options={"encrypt":true}&anotherOption=1
```

**Comment by eladeyal-intel** [comment]
Yay I'm so proud  💪
