### ISSUE TITLE
Add webhooks

### ISSUE THREAD

**Issue by rickbergfalk** [rickbergfalk/sqlpad#716]
I'd like to add a variety of webhooks and eventually deprecate things that could be built with them such as sending user email invites, or posting slack messages.

Webhooks would be easily testable, and allow for ultimate flexibility for people integrating SQLPad into other services. 

The variety of hooks could open up SQLPad to a whole other use case too depending on what people want to do with it.

Some of the webhooks that could be supported:
* user invited
* user logged in
* query run started
* query run finished (the results could be sent somewhere!)
* query error
* query saved
* api key created
* ???

As for the implementation, I'm thinking webhooks are just an HTTP post to a URL. A hook secret would be configured and sent as a header for each POST, so that the receiver can validate the hook is from a trusted setup. (similar to how GitHub hooks work)

**Comment by eladeyal-intel** [comment]
Access granted (to a user for a resource) can  be used to send email or notification in other service.

**Comment by rickbergfalk** [comment]
Webhooks are added in 5.2.0.

I implemented a variety of events and a pattern for testing them. If anyone doesn't see an event they'd like to see, PRs welcome for expanding on events supported.

**Comment by n0rm4l-real** [comment]
Any plans to add `access_created` webhook? It would be very useful.
