### ISSUE TITLE
Cannot push into my fork

### ISSUE THREAD

**Issue by yorek** [rickbergfalk/sqlpad#719]
I cannot push changes into my fork anymore (master branch) as I get the following error:
```
To https://github.com/yorek/sqlpad.git
 ! [remote rejected] master -> master (refusing to allow an OAuth App to create or update workflow `.github/workflows/lint.yml` without `workflow` scope)
error: failed to push some refs to 'https://github.com/yorek/sqlpad.git'
```
Any clue on why this started to happen today? (yesterday everything was good)

**Comment by eladeyal-intel** [comment]
Try creating a new github PAT with more scopes I.e. Workflow.

**Comment by yorek** [comment]
That worked, thanks!

**Comment by yorek** [comment]
Btw if anyone as the same problem solution is here: https://github.com/gitextensions/gitextensions/issues/4916
