### ISSUE TITLE
don't forget to unfix "Updates user"

### ISSUE THREAD

**Issue by eladeyal-intel** [rickbergfalk/sqlpad#722]
I modified 
`    assert(new Date(body.updatedAt) > new Date(user.updatedAt)); `
to 
`    assert(new Date(body.updatedAt) >= new Date(user.updatedAt)); `

in `server/test/api/users.js` -> `it('Updates user'...)`

I don't know what this test was trying to do; so I'm opening this issue to make sure @rickbergfalk looks into it an resolves or reverts.

**Comment by rickbergfalk** [comment]
For this one it was just to validate that updatedAt is auto updated. It is kind of a random test that isn't providing much value other than a sanity check on sequelize config. 

With MySQL though milliseconds aren't factored in so some of the updated times can be similar. I think the change is fine.
