### ISSUE TITLE
Allow users to be enabled/disabled

### ISSUE THREAD

**Issue by rickbergfalk** [rickbergfalk/sqlpad#746]
In prep for #745, there are cases where we need to have user accounts for reference, but they should not permit a user to log in.

Some examples: 
* A user could be deleted after creating queries, leaving a reference to a user that does not exist
* A seed query could be added for an email address that does not exist

To address this I'm going to add an `disabled` flag or similar to the `users` table, and allow it to be toggled via admin. Email addresses referenced in seed queries will eventually convert to user accounts that are disabled on creation.

Admins can then go enable the user in the user management section of the application.

Another benefit of all this allowing users to be disabled, but open authentication to remain open for auto-creating users.

This is probably not needed for this application, but if user auto-creation was turned on (depending on auth mechanism), and a user was deleted to prevent them from accessing the application, they could log in again by re-authenticating, which would recreate the user record that was deleted. With a disabled flag set to true, that user record persists, and the user is no longer allowed to log in on future attempts. This is probably beyond the scope of what people are using SQLPad for but potentially nice to have?

**Comment by eladeyal-intel** [comment]
Note that the GPDR requires (to my understanding) that any web-app has a way to delete e-mail addresses upon request (or users). So if you have this capability don't kill it.

**Comment by rickbergfalk** [comment]
I was thinking about that... 

I plan on keeping delete around, but what that should do yet I'm not sure. 

One thought I had was to leave the user record, but scrub email, make the name something like "Deleted editor" or "Deleted admin" or something like that.

This allows all existing queries created/updated by that user to go unchanged too
