### ISSUE TITLE
Add --migration command

### ISSUE THREAD

**Issue by rickbergfalk** [rickbergfalk/sqlpad#749]
Add a command line flag to run migrations then exit the process, returning proper error code. 

Today migrations are run on startup, which may not be preferred if launching multiple SQLPad instances with a new version, which could create a race condition.

Instead, one SQLPad instance should be launched, with others starting once complete.

**Comment by eladeyal-intel** [comment]
You also want a configuration option to disable auto migration ( Like https://www.metabase.com/docs/latest/operations-guide/running-migrations-manually.html ) in order to avoid this race.
