### ISSUE TITLE
Time for v5?

### ISSUE THREAD

**Issue by eladeyal-intel** [rickbergfalk/sqlpad#753]
Docker users would benefit from a fixed release with current feature set.

**Comment by rickbergfalk** [comment]
Yeah... I've been trying to follow a semantic versioning of sorts and bundling in a bunch of "breaking" changes for a v5.

Breaking in the sense that REST API changes and data models changes will be happening from 4 to 5, and rolling back to a previous version won't be possible unless you restore an old db. 

The `userId` stuff in #750 was the last big change I wanted to make. 

I think 5.0.0 can be tagged later this week?

**Comment by rickbergfalk** [comment]
I've decided to commit - 5.0.0 will be this Friday or sooner

**Comment by eladeyal-intel** [comment]
🦾

**Comment by rickbergfalk** [comment]
v5 has been tagged and builds are building in docker hub. 

Will plan on adding to documentation early next week.
