### ISSUE TITLE
Adding support for read-only database/Synapse SQL

### ISSUE THREAD

**Issue by JocaPC** [rickbergfalk/sqlpad#754]
I have tried to setup SqlPad to access read-only SqlServer database; however, it failed because at some point because it tried to execute `CREATE TABLE`. I have used SqlPad deployed in container in Azure as described in this post: https://devblogs.microsoft.com/azure-sql/querying-and-visualizing-data-using-sqlpad

I cannot provide writable connection to database, and I don't need some metadata to be saved. I'm fine with providing public access to my sample database via sqlpad but I don't want to provide connection string.

Is there a way to configure SqlPad to work with read-only database or this should be feature request? I tried SqlServer option readOnlyIntent:true but it didn't helped.

> Note: I'm trying to setup SqlPad as UI for Synapse SQL serverless that is by design read-only query-able service where we cannot insert data.

**Comment by eladeyal-intel** [comment]
You shout configure your read only database under "connections" (in json or I I or env vars) and not under backendDatabaseUri. I've used sqlpad with read only databases (not SQL server though)

**Comment by rickbergfalk** [comment]
To expand on this a bit...

SQLPad needs a database of some kind where it can write data to (saved queries, queries that have been executed, etc). The backend database URI is used for targeting something like MySQL, MariaDB, Postgres, or SQL Server. 

Alternatively you can use SQLite and the local file system by only setting `dbPath`/`SQLPAD_DB_PATH`.

If you are limiting yourself to 1 SQLPad process and don't need any data kept around, you can give `dbInMemory`/`SQLPAD_DB_IN_MEMORY` a try. Just keep in mind you will lose any history/saved queries on process restart.  http://rickbergfalk.github.io/sqlpad/#/configuration?id=dbinmemory

**Comment by rickbergfalk** [comment]
@JocaPC going to close for now - let me know if you have any other questions.
