### ISSUE TITLE
Environment variable consistency

### ISSUE THREAD

**Issue by rickbergfalk** [rickbergfalk/sqlpad#759]
Some environment variables start with `SQLPAD` while others don't. I've also noticed some are quite long, and `SQLPAD_` may not be necessary.

I'd like to make these consistent, and I'm leaning towards prefixing them all with `SQLPAD_` or perhaps shortening the prefix to `SP_` similar to how Metabase uses `MB_`. 

Whatever the decision, I think the existing can be supported for a version, and a deprecation warning logged.  This can also coincide with deprecating JSON/INI formats. 

The biggest advantage for all this is simplifying documentation. No more needing to reference `keyName` and `KEY_NAME` or `SQLPAD_KEY_NAME`.

**Comment by rickbergfalk** [comment]
Actually maybe `SQLPAD_` isn't so bad `SP_` only saves 4 characters 🤔

**Comment by eladeyal-intel** [comment]
SQLPAD_ is cool

I think max env var name should  be 32 characters

**Comment by eladeyal-intel** [comment]
Some variables are not sqlpad specific so they don't need SQLPAD_ Prefix.for example smtp configuration.

**Comment by rickbergfalk** [comment]
But isn't the SMTP variable _for_ SQLPad's config? 

I guess what I'm confused by is when variables should be namespaced and when they shouldn't be. For example, all ldap could start with LDAP_, all saml with SAML_, etc. But if you run multiple services in same space (probably unlikely/not best practice) could those conflict with any existing vars? 

The project today has `SAML_CERT`, `SAML_ISSUER`, `SAML_CALLBACK_URL` but also has `SQLPAD_SAML_AUTO_SIGN_UP`. I suppose one could reason that the latter is something SQLPad specific, while other SAML vars are generic for SAML?

Personally, making a rule that all env vars should be prefixed with SQLPad makes it easy to remember to be consistent and also minimizes conflict (if that is an issue I'm not actually sure).

**Comment by eladeyal-intel** [comment]
I agree that all saml stuff should be prefixed  with sqlpad. This configuration is sqlpad specific. Some stamp config can be seen IMO as client agnostic and in this case can be used without sqlpad prefix. (Maybe).

**Comment by eladeyal-intel** [comment]
OK, I went over the current env vars list. It makes sense *not* to rename all of SQLPAD_SMTP_* vars to SMTP_*.

1. LDAP_* --> SQLPAD_LDAP_* 
2. ENABLDE_LDAP_AUTH --> SQLPAD_LDAP_AUTH_ENABLED
3. DISABLE_AUTH --> SQLPAD_AUTH_DISABLED
4. DISABLE_USERPASS_AUTH --> SQLPAD_USERPASS_AUTH_DISABLED
5. GOOGLE_* --> SQLPAD_GOOGLE_*
6. CERT_PASSPHRASE, CERT_PATH, KEY_PATH  -  deprecated - don't change
7. SAML_* --> SQLPAD_SAML_*  #764 
8. PUBLIC_URL - can keep PUBLIC_URL, but I think it will remain the only env var w/o SQLPAD in its name so that would be funny. So SQLPAD_PUBLIC_URL

**Comment by rickbergfalk** [comment]
@eladeyal-intel I've renamed HTTPS cert/key variables since they are being left in. 

I'm going to update `SERVICE_TOKEN_SECRET` to `SQLPAD_SERVICE_TOKEN_SECRET` then tag 5.1.0

**Comment by rickbergfalk** [comment]
Thanks for all the help renaming these @eladeyal-intel!
