### ISSUE TITLE
HTTPS port config variable ignored?

### ISSUE THREAD

**Issue by aaronkorver** [rickbergfalk/sqlpad#770]
https://github.com/rickbergfalk/sqlpad/blob/master/server/server.js#L83
Looking at the code here, shouldn't this pull from the https port config?

**Comment by rickbergfalk** [comment]
Yeah it should. I suspect not many are using it. HTTPS support is going to drop next major version as that should be offloaded to nginx or similar.

**Comment by aaronkorver** [comment]
That's too bad, I was looking for something quick that could be run in a container platform on public cloud.  I can see the perspective to offload that to something else, but if it is there already and just using the npm capabilities, why remove?

**Comment by rickbergfalk** [comment]
Its been neglected and lacks testing, and putting something in front of node for HTTPS is recommended for perf reasons. SQLPad use cases probably aren't that high traffic though, so that last point probably doesn't matter.

Ultimately I figured people could just put nginx in front, but I can see wanting a standalone option...

**Comment by rickbergfalk** [comment]
Looking into the HTTPS port config, I think I meant to remove it but never removed the config/documentation. 

With the current implementation, running on both HTTP and HTTPS is not supported. Only one HTTP(S) server is started up for a given process.

I'll be removing the HTTPS port variable in favor of SQPLAD_PORT. I don't think 2 port configs make sense.

**Comment by rickbergfalk** [comment]
Also I think I'm going to un-deprecate HTTPS. Instead of removing it outright, perhaps it might be worth making note in documentation about why one might not want to serve HTTPS from SQLPad directly

**Comment by eladeyal-intel** [comment]
If it https is being removed..

Hopefully Dockerfile is updated to still deliver https

**Comment by rickbergfalk** [comment]
Do people put nginx in front of node.js in single docker image or are they usually put in 2 separate containers?

Instead of having node.js handle https I suppose nginx could be used? That could maybe complicate some of the HTTP config though too.

**Comment by eladeyal-intel** [comment]
All I know is that my docker instance of `sqlpad/sqlpad` (on CloudFoundry) works with https and I don't want it to break.

**Comment by rickbergfalk** [comment]
ah ok - yeah we can leave it as is.
