### ISSUE TITLE
Overwrite Docker port?

### ISSUE THREAD

**Issue by aaronkorver** [rickbergfalk/sqlpad#771]
https://github.com/rickbergfalk/sqlpad/blob/master/docker-entrypoint#L2
Looking at this entry point, it is using the CLI variable to set the port to 3000

Then diving into the config code https://github.com/rickbergfalk/sqlpad/blob/master/server/lib/config/index.js#L24 it looks like the CLI variable wins if there are conflicts between ENV, File, and CLI.  

Am I reading this correctly?  If so, then without changing the startup script there is no way to change the startup port.  

In normal Docker, I could map 3000 within the Docker network.  However, I'm looking to run this in a public cloud provider and they don't support the port mapping.  Thoughts?

**Comment by rickbergfalk** [comment]
Yeah you're reading it correctly. The config is in the middle of getting cleaned up and aimed to just use environment variables. 

Ideally I'd like docker-entrypoint to have no cli flags passed and just use environment variables. 

Can the entrypoint default env vars if not set? I'm not sure what the preferred pattern is for providing default env vars if not supplied.

**Comment by rickbergfalk** [comment]
This should be fixed in `latest` image on docker hub.
