### ISSUE TITLE
API questions

### ISSUE THREAD

**Issue by eladeyal-intel** [rickbergfalk/sqlpad#783]
1. I think the "service token" (whatever it is) is not documented.

2. I thought I could use an sqlpad instance as a way to implement DB updates from a webhook-style thing. So I could have an external website with a link/button which, when clicked, will send a POST request to `/api/batches` with `batchText`=`UPDATE tbl1  SET n=(n+1);` and setting `connectionId`; and this will update the table `tbl1`, right?

3. But I think for this to happen without the external website users needing to authenticate to sqlpad, I need to use a "service token" and I can append it to the POST request?

4. If all this makes sense; why not allow this as a GET request as well?

**Comment by rickbergfalk** [comment]
Ah yeah this could maybe be expanded on in API docs. Right now its just the config variable and that alone doesn't make much sense.

The service token secret is used to encrypt the JWT service tokens created in the UI. The resulting token can be passed with all requests as a header, so it should work for GETs as well.

**Comment by eladeyal-intel** [comment]
So I will set the POST request to /api/batches with a **header** `Authorization` whose value is `Bearer ` + "JWT service token created in the UI" ?

and the POST **body** will be 
```
{
  connectionId: 'conn1',
  batchText: 'UPDATE tbl1 SET n=(n+1);'
}
```

do I get this right?

**Comment by rickbergfalk** [comment]
Yep https://github.com/rickbergfalk/sqlpad/blob/master/server/test/api/service-tokens.js#L108

**Comment by rickbergfalk** [comment]
I'll add to documentation in a bit under authentication and API sections.

Another undocumented option for API if you're using userpass auth is to send username and password as HTTP basic auth if preferred as well
