### ISSUE TITLE
Regular expression constraint escapes result in parsing error

### ISSUE THREAD

**Issue by davidd-at-change** [rickbergfalk/sqlpad#792]
Escape flags \m and \M from Postgresql lead to SQL parsing error in SQLPad.

Example: select 'abc def' ~ 'def\M' 
gives error.

Table 9.21 from the doc reference https://www.postgresql.org/docs/12/functions-matching.html explains expected matching mechanism.

**Comment by rickbergfalk** [comment]
Thanks will look into this. I believe this is likely an issue with the library in use https://sqlpad.github.io/sql-limiter/

**Comment by rickbergfalk** [comment]
This is fixed in 5.2.0 (just tagged now, soon available on Docker Hub)
