### ISSUE TITLE
Config system implementation

### ISSUE THREAD

**Issue by dcelasun** [rickbergfalk/sqlpad#8]
Hey Rick,

I'd like to propose a configuration system feature. This would allow administrators to change SqlPad's behaviour on runtime via key/value pairs defined in the configuration interface.

My initial implementation ([screenshot](http://i.imgur.com/ojP78j6.png)) is [here](https://github.com/rickbergfalk/sqlpad/commit/8bdbdce049cd4c7dc214c7da9fd217c9aa6a9a5c) on a separate branch. I've also implemented a [small feature](https://github.com/rickbergfalk/sqlpad/commit/555c0b7b373705b46e8e5dfb6a52c5be1097effd) using the config system.

Any thoughts on this? Do you think it's a worthy addition?

**Comment by rickbergfalk** [comment]
Sure definitely! 

I initially contemplated adding a config screen of some kind, but ultimately had no idea what settings would be beneficial. I like the approach of a key/value system too - keeps things flexible and simple.

**Comment by dcelasun** [comment]
Great! I'll merge the branch into master shortly.
