### ISSUE TITLE
old news override new news

### ISSUE THREAD

**Issue by eladeyal-intel** [rickbergfalk/sqlpad#801]
This seems persistent in v5.2. 

1. Define a connection A which timeouts verry slowly 
2. Define a connection B which  is fine
3. choose connection A from dropdown menu
4. execute a SELECT (which will take a lot of time)
5. Don't wait for it to fail (loose your patience)
6. Choose connection B  from dropdown menu
7. execute a SELECT
8. results pane show results from connection B
9. After some time, when the result from connection A arrive, they unexpectedly override the results with the error message.

**Comment by rickbergfalk** [comment]
Ah thanks for reporting. I know what is going on here and will fix shortly
