### ISSUE TITLE
mysql2 transactions don't work

### ISSUE THREAD

**Issue by eladeyal-intel** [rickbergfalk/sqlpad#802]
With mysql driver, I can send "start transaction" and "rollback" and things seem to work.

with mysql2 I get "This command is not supported in the prepared statement protocol yet" (with same MariaDB server)

despite #703

**Comment by rickbergfalk** [comment]
Looks like `.execute` method in use automatically uses prepared statements, while `.query` doesn't? will add a quick test and see if that is the case
