### ISSUE TITLE
[FEATURE] sqlpad need have ticket ability or integrate the other Ticket system for collaboration

### ISSUE THREAD

**Issue by dengc367** [rickbergfalk/sqlpad#830]
I think sqlpad just need some ticket ability/functionality which can cooperate with other colleagues:

1. first, one user from  Business Unit can submit TT question/issue (which have title and description) on sqlpad,
2. then, The BI Developer understand the TT meaning, and provide the corresponding SQL according to that TT,
3. and then, the BU user can query the SQL to get result from TT.

**Comment by rickbergfalk** [comment]
I think this is an interesting idea. Want to give it some additional thought of how it might be worked into current application UI though. 

I'm not familiar with TT... is that a ticket of some kind?

**Comment by dengc367** [comment]
yeah, TT is short for TickeT, like [Request Tracker](https://bestpractical.com/request-tracker) of BestPractical and `issue` of github,  on which the users can submit the question/request, and other people can reply and resolve it.

**Comment by dengc367** [comment]
there is another ticket system [trudesk](https://github.com/polonel/trudesk) .

**Comment by dengc367** [comment]
I just close the issue. when needed, feel free to open this issue.
