### ISSUE TITLE
LDAP authentication security issue

### ISSUE THREAD

**Issue by skaravad** [rickbergfalk/sqlpad#835]
This is a followup for #831 , I tested the code locally and , here are the issues and few workarounds I think might help

1. As pre-loading users is not a trivial thing with LDAP auth, I enabled SQLPAD_ALLOWED_DOMAINS, so that users can auto sign-up , but this totally defeats the purpose for LDAP auth
2. At the sign-up page, users can enter any password , it does not really need to match the password set in the LDAP.
3. At the login page, users can sign-in with the LDAP creds which works perfectly, but at the same time, users can login with the email address that was used to signup (in step2) and the password which was used in  step 2.
4. I set SQLPAD_USERPASS_AUTH_DISABLED=true, which just disabled the entire UI (no form login)

Few thoughts on possible workarounds
1. Can the code honor  SQLPAD_USERPASS_AUTH_DISABLED=true as SQLPAD_LDAP_AUTH_ENABLED=true  and if the user is authenticated.
2. As of now the ldap is only performing the authentication, can this also perform authorization (fetch the group membership and map it back to editor or admin role based on a matching LDAP group membership), this way users need not sign up, as the role is pre-fetched from the LDAP.

3. There is pre-defined user SQLPAD_ADMIN and SQLPAD_ADMIN_PASSWORD, probably this can be used for local auth for initial setup or future admin tasks (if 2 is not feasible)

4. What if the user who is signing up (when LDAP auth is enabled) is flagged as LDAP user in the SQLPAD internal db and not allow the user to login with the email that was used in the sign up process.

Again these are just thoughts, I think you guys have better ideas in how to deal with this situation, again thank you for #831

**Comment by skaravad** [comment]
The security issue is, even if the user is disabled or deleted in the LDAP, user can still sign-in with the info that was set during the signup process.

**Comment by dengc367** [comment]
Yep, good ideas, there are several login / sign up security enhancements you described that need to be fixed. You can create the PR to commit some code for these scenarios when you have time. We can collaborate for this case.

**Comment by rickbergfalk** [comment]
Just so I'm understanding things: we need to have username and password inputs in the UI for LDAP, which means someone today can't use LDAP and disable local userpass auth, since doing so removes the UI... correct?

**Comment by skaravad** [comment]
@rickbergfalk , yes that is correct, the moment we set the env var SQLPAD_USERPASS_AUTH_DISABLED=true and restart the service, the UI goes bust, I guess it is a side affect of expecting auth headers from either SAML or other mechanisms.

Now coming back to the issue, full disclosure, I'm not a software developer, I'm devops , my coding skills are pretty limited, so I looked into the code and understood few bits and pieces, and I could come up with a work around.

Here is my thought process, introduced another env variable in lib/config/config-items.js
```
{
    key: 'allowLocalAdmin',
    envVar: 'SQLPAD_ALLOW_LOCAL_ADMIN',
    default: '',
  }
```
Modified routes/signin.js
```
  if (
    body.email &&
    body.password &&
    (config.get('ldapAuthEnabled') || config.get('enableLdapAuth')) &&
    body.email.indexOf('@') < 0
  ) {
    return passport.authenticate('ldapauth', handleAuth)(req, res, next);
  }
### Changes start here ###
### When SQLPAD_ALLOW_LOCAL_ADMIN to is set to true (assuming that people will note down their initial admin email/pass), match the local admin env var and allow login using local auth strategy 
  if (
    body.email &&
    body.password &&
    body.email === config.get('admin') &&
    config.get('allowLocalAdmin')
  ) {
    return passport.authenticate('local', handleAuth)(req, res, next);
  }
#### If LDAP AUTH , is set to false , then continue to use Local auth ###
  if (
    body.email &&
    body.password &&
   !config.get('userpassAuthDisabled') &&
   !config.get('disableUserpassAuth') &&
   !(config.get('ldapAuthEnabled') || config.get('enableLdapAuth'))
  ) {
    return passport.authenticate('local', handleAuth)(req, res, next);
  }
```
My initial test results look good, but the error handling part ( proper log statements) is something that did not do and don't know how to bubble up to the UI , in the debug log, the application returns 400 (which is expected) , may be some documentation will help users vs over doing it as this is a stopgap.
@dengc367 let me know your thoughts, if you are okay with these change, I can create a PR. Again my coding skills are limited :-)

**Comment by skaravad** [comment]
The ideal way would be to toggle local auth true/false, but I could not figure out why the UI goes mute when local auth is disabled, but thinking through a bit I feel my approach makes some sense , probably during initial deploy where in you can still l use local admin with ldap enabled , and as a bypass mechanism if external auth systems go crazy for any reason.

**Comment by eladeyal-intel** [comment]
I think what you want is to add `SQLPAD_LDAP_AUTO_SIGN_UP` similar to `SQLPAD_SAML_AUTO_SIGN_UP`; and then do not use `SQLPAD_ALLOWED_DOMAINS`. Only users with LDAP account would be able to log in.

**Comment by skaravad** [comment]
SQLPAD_LDAP_AUTO_SIGN_UP the option exists or its  an enhancement ? I looked through the config items and it does not exist.

**Comment by skaravad** [comment]
My bad, I think I can make these changes.  I'll do some local testing and get back, looks pretty easy. Thank you for the pointer.

**Comment by eladeyal-intel** [comment]
@skaravad Here's how I added SQLPAD_SAML_AUTO_SIGN_UP - doing the same for LDAP could be similar 

https://github.com/rickbergfalk/sqlpad/pull/679/commits/ebf4de3ec8d8aad547d323b70cafad9cacd819b6

**Comment by skaravad** [comment]
@eladeyal-intel I got it working locally, made few additional changes for RBAC (not super great, but it works), I forked the repo , will send the PR sometime today ( I think RBAC can be enhanced further)

**Comment by skaravad** [comment]
@eladeyal-intel @rickbergfalk I created a PR, given my very limited JS skills, I'm not quite sure why the lint is failing 
https://github.com/rickbergfalk/sqlpad/pull/837

I'll be more than happy to fix them if you could provide me any pointers :) 
Here is the fork, given this is my first contribution towards OSS, my apologies for any mistakes.
https://github.com/skaravad/sqlpad

**Comment by skaravad** [comment]
Fixed lint issues.
