### ISSUE TITLE
Docker Hub sqlpad/sqlpad:latest can't be pull

### ISSUE THREAD

**Issue by tremblaysimon** [rickbergfalk/sqlpad#848]
Only to mention that `latest` version can't be pull from Docker Hub actually.
(digest version 848c2a4d9b33180d65775141ffe27fd2e43e0bb07bc78a4d65ee5c1210cbdb86)

Here is the error we get:

```
$ docker pull sqlpad/sqlpad
Using default tag: latest
latest: Pulling from sqlpad/sqlpad
cbdbe7a5bc2a: Already exists
6282c10629b6: Pulling fs layer
24f383844fee: Pulling fs layer
22e94daf4797: Pulling fs layer
0c0920263dd9: Waiting
6641c41ef3bf: Waiting
ac112a059e32: Waiting
b9249d4acf7c: Waiting
fdee66565571: Waiting
error pulling image configuration: unknown blob
```

**Comment by rickbergfalk** [comment]
Thanks for the heads up! I'll see if I can get this fixed

**Comment by rickbergfalk** [comment]
Looks like base image was wrong with last version bump. latest is now available. thanks again for making the report!
