### ISSUE TITLE
Created by filter behaviour for user having zero queries

### ISSUE THREAD

**Issue by iprikhach** [rickbergfalk/sqlpad#87]
If a user not having any queries clicks on "Queries" menu link (/queries?createdBy=xxx%40yyy.com), she gets an empty list of queries. Created by filter shows that "Everyone" is selected in this case, which is misleading, because if the user either removes url parameter or clicks on any other user and then clicks back on "Everyone", she'll see all queries in the system (by all users).

**Comment by rickbergfalk** [comment]
Hi @iprikhach - I think I have this sorted out in the upcoming beta release. For better or worse I've gotten rid of the url createdBy parameter. Now when a user clicks on the "queries" link, they'll see their own queries listed, unless they do not have any. If the user does not have any queries, the dropdown will switch over to everyone and all queries will be listed.
