### ISSUE TITLE
Enhancement - Save Chart Images

### ISSUE THREAD

**Issue by deepvoice** [rickbergfalk/sqlpad#9]
Could we add something like this to save the chart image too?

    function SaveChart()
    { TheCanvas=$("#canvas")[0];
    if(TheCanvas.toBlob) {
    TheCanvas.toBlob( function (blob) {
    saveAs(blob, "chart.png");
    }, 'image/png' ); }

    if(!TheCanvas.toBlob){
    var dataURL =TheCanvas.toDataURL('image/png') var w=window.open('about:blank','image from canvas');
    w.document.write("Save As Image"); }

    }

**Comment by rickbergfalk** [comment]
I would love to have something like this. I think the charting library in use (dimple) uses svg so we wouldn't be able to use this approach exactly, but there has to be something similar out there...

**Comment by deepvoice** [comment]
This looks promising: https://github.com/exupero/saveSvgAsPng

**Comment by rickbergfalk** [comment]
Just wanted to provide an update on this - i've been able to get saveSvgAsPng to work but it'll involve updates to the chart render process. I'm going to try and get around to this within the next week or so.

**Comment by rickbergfalk** [comment]
Just published this functionality in 1.4.0! Let me know what you think. Pretty basic functionality right now. I have an issue open to add a toggle for adding chart legend in #15
