### ISSUE TITLE
Dockerize

### ISSUE THREAD

**Issue by tclass** [rickbergfalk/sqlpad#90]
Hi, 
would be nice to have a Dockerfile direct in this repo and maybe and image on hub.docker.com

**Comment by tclass** [comment]
wow thx, looks great!

**Comment by rickbergfalk** [comment]
As I commented in #91 I think this is a great idea, I'm just not familiar with docker. 

I've created a SqlPad organization on hub.docker.com and will work towards getting an image published hopefully later tonight. (https://hub.docker.com/u/sqlpad/)

Any assistance welcomed :)

**Comment by marcmillien** [comment]
Sure :).
My docker username is as github `marcmillien` ;).

**Comment by rickbergfalk** [comment]
@marcmillien I've added you to the contributors team on the sqlpad org at hub.docker.com. I wasn't sure how I should manage the team structure... any ideas/suggestions let me know. 

I'm enjoying learning about docker, but honestly I wouldn't mind handing off docker image management too if that's something you'd be interested in owning :)

**Comment by marcmillien** [comment]
While I can, I'm ready to help in this :).

You have to create some repository, I visibly can't do that :).
https://hub.docker.com/u/sqlpad/dashboard/

Maybe we should follow you versioning for the docker tags.
I mean we would have:
```
sqlpad/sqlpad:latest
sqlpad/sqlpad:1.15.0
...
```
I'm going to create a `Makefile` to help us pushing this to the docker hub.

**Comment by rickbergfalk** [comment]
Thanks again @marcmillien! This is great. I'm in agreement with the versioning strategy too. 

I created a repository and added you as an admin. Hopefully you should be able to push the image now?

Otherwise I'll probably get around to this later this weekend. Thanks for all the assistance on this.

**Comment by marcmillien** [comment]
Done :)
https://hub.docker.com/r/sqlpad/sqlpad/tags/

I think we have to change the `docker-compose.yml` for a developper perspective.
I'll work on it when I have time to.

**Comment by tclass** [comment]
guess I close the issue than :D thx everyone
