### ISSUE TITLE
Exporting chart does not copy the legend

### ISSUE THREAD

**Issue by ybroze** [rickbergfalk/sqlpad#93]
Hi Rick, great tool. We're looking at using it at TodayTix, and will possibly be contributing PRs in the future, if we can get some traction. In any case, I wanted to help keep track of these feature requests in your Issues page.

Right now, exporting a chart does not export the legend, which makes it somewhat impractical. Would be a helpful feature.

**Comment by rickbergfalk** [comment]
Hi @ybroze thanks and great to hear! Definitely send in issues as you'd like! 

Regarding the chart legend, the tauCharts folk have already figured out how to work all that in and even wrote a blog post about it. I just haven't gotten around to changing my solution to utilize it. https://blog.taucharts.com/svg-to-png/ 

I hope to be clearing some time in my schedule to work on the SqlPad backlog and clean up some of the code. I've even contemplating taking some time off over the summer and dedicating it to SqlPad...
