### ISSUE TITLE
Use foreign keys to cross-link between tabels.

### ISSUE THREAD

**Issue by ioggstream** [rickbergfalk/sqlpad#96]
Provided two tables are related by a FK:

  - when clicking on the referencing cell
  - the lines of the referenced tables are shown.

**Comment by rickbergfalk** [comment]
Hi @ioggstream I'm not sure I fully understand the request. Would this be something done in the schema hierarchy sidebar?

**Comment by rickbergfalk** [comment]
going to close this issue for now - we can reopen with further detail in the future
