### ISSUE TITLE
Run multiple statement

### ISSUE THREAD

**Issue by preet20** [rickbergfalk/sqlpad#98]
Is there a option to run multiple statements and save those statements to be used in future.

For example
1. create table emp(name varchar(20)
2. insert into emp.....
3. select count(*) from emp

I would like to save all the above statements together and run it all together one after other

**Comment by rickbergfalk** [comment]
Hi @preet20 

Which database are you using with SqlPad? Have you tried this already? It looks like it works for MS SQL Server.

Something to consider though... SqlPad runs on the assumption that you'll only ever be returning 1 result set. If you run 2 select queries you may end up with unexpected results.

**Comment by rickbergfalk** [comment]
Hi @preet20 - going to close this issue for now. let me know if you have any more questions about this.
