### ISSUE TITLE
Run Queries Anonymously?

### ISSUE THREAD

**Issue by philjensen** [rickbergfalk/sqlpad#99]
Is there any way to configure this to run anonymously?  I'm using this as an internal web app to run queries to replace the old owc10.exe that only ran in IE.  I want users to be able to run a saved query URL without having to log in.

**Comment by rickbergfalk** [comment]
Hi @philjensen - currently a login is required. An email address domain can be whitelisted to make the process of creating user accounts a bit easier. 

If there was an option to disable user auth, would you expect the users to be able to modify the queries before they are executed, or would they just be able to run pre-defined queries?

I could see this functionality being useful though, especially a way to share queries in some way.

**Comment by philjensen** [comment]
For my needs, they just want to be able to hit a URL and run the queries in a read-only fashion. This is great for queries that relate to their daily tasks, daily sales data, daily metrics, etc.  So you could lock down the program like you have it now unless you send a saved query URL w/ some kind of read-only parameter, possibly showing a view that is just the results and ability to export to a file type without all the left/top nav and the query itself.

**Comment by rickbergfalk** [comment]
The display part is already in place... for each query there is a url parameter to just show the chart or result grid. I could see adding some sort of "public" option where a visitor could run queries. This could be a site wide thing or just queries that were marked as public too. 

I'm going to be revisiting a lot of SqlPad stuff June/July - I'll make sure this is one of them.

**Comment by rickbergfalk** [comment]
@philjensen I'm starting on this functionality - I currently have a setting exposed that will allow the table result and chart result urls to work without login. They don't have any export links on them yet though. I'll have to think about how to add those (these views were originally started for embedding in an iframe and building a dashboard of sorts)

Its basically a secret url you'd share with whoever you'd want to have access to the query results if the require-login setting is disabled. 

If interested, this will be available to try out in the v2 beta I'll be publishing to npm tomorrow.

I still think it'd be nice to have a read-only public view of all the queries but that'll be a larger effort.

**Comment by rickbergfalk** [comment]
I've refined the table-only/chart-only pages a bit in beta 2 that has recently been published to npm. the table/chart only pages now show the query title and gives an export button to download the csv/xlsx data file and the image if viewing the chart.
